// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_audits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAIAuditsForLocation = `-- name: CountAIAuditsForLocation :one
SELECT COUNT(*)
FROM ai_audits
WHERE project_id = $1::uuid
  AND location_id = $2::uuid
  AND ($3::text = '' OR status = $3::text)
`

type CountAIAuditsForLocationParams struct {
	ProjectID    pgtype.UUID
	LocationID   pgtype.UUID
	StatusFilter string
}

func (q *Queries) CountAIAuditsForLocation(ctx context.Context, arg CountAIAuditsForLocationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAIAuditsForLocation, arg.ProjectID, arg.LocationID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAIAuditsForProject = `-- name: CountAIAuditsForProject :one
SELECT COUNT(*)
FROM ai_audits
WHERE project_id = $1
  AND location_id IS NULL
  AND ($2 = '' OR status = $2)
`

type CountAIAuditsForProjectParams struct {
	ProjectID pgtype.UUID
	Column2   interface{}
}

func (q *Queries) CountAIAuditsForProject(ctx context.Context, arg CountAIAuditsForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAIAuditsForProject, arg.ProjectID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIAudit = `-- name: CreateAIAudit :one
INSERT INTO ai_audits (
    project_id,
    crawl_id,
    status,
    score,
    error_message,
    started_at,
    completed_at,
    location_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, project_id, crawl_id, status, score, error_message, started_at, completed_at, created_at, updated_at, location_id
`

type CreateAIAuditParams struct {
	ProjectID    pgtype.UUID
	CrawlID      pgtype.UUID
	Status       string
	Score        pgtype.Int4
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	LocationID   pgtype.UUID
}

func (q *Queries) CreateAIAudit(ctx context.Context, arg CreateAIAuditParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, createAIAudit,
		arg.ProjectID,
		arg.CrawlID,
		arg.Status,
		arg.Score,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.LocationID,
	)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const failActiveAIAuditsForCrawl = `-- name: FailActiveAIAuditsForCrawl :execrows
UPDATE ai_audits
SET status = 'failed',
    error_message = 'superseded by project setup retry',
    completed_at = now(),
    updated_at = now()
WHERE project_id = $1
  AND crawl_id = $2
  AND location_id IS NULL
  AND status IN ('queued', 'running')
`

type FailActiveAIAuditsForCrawlParams struct {
	ProjectID pgtype.UUID
	CrawlID   pgtype.UUID
}

// Setup retry path: a queued/running audit orphaned by a crashed or failed
// visibility job would otherwise block creating the fresh retry audit on the
// one-active-per-crawl index. Terminal audits are never touched, so history
// stays append-only and a failed run is never reused.
func (q *Queries) FailActiveAIAuditsForCrawl(ctx context.Context, arg FailActiveAIAuditsForCrawlParams) (int64, error) {
	result, err := q.db.Exec(ctx, failActiveAIAuditsForCrawl, arg.ProjectID, arg.CrawlID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAIAuditByCrawlAndProject = `-- name: GetAIAuditByCrawlAndProject :one
SELECT id, project_id, crawl_id, status, score, error_message, started_at, completed_at, created_at, updated_at, location_id
FROM ai_audits
WHERE project_id = $1 AND crawl_id = $2 AND location_id IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetAIAuditByCrawlAndProjectParams struct {
	ProjectID pgtype.UUID
	CrawlID   pgtype.UUID
}

func (q *Queries) GetAIAuditByCrawlAndProject(ctx context.Context, arg GetAIAuditByCrawlAndProjectParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, getAIAuditByCrawlAndProject, arg.ProjectID, arg.CrawlID)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const getAIAuditByIDForUser = `-- name: GetAIAuditByIDForUser :one
SELECT
    aa.id,
    aa.project_id,
    aa.crawl_id,
    aa.status,
    aa.score,
    aa.error_message,
    aa.started_at,
    aa.completed_at,
    aa.created_at,
    aa.updated_at,
    aa.location_id
FROM ai_audits AS aa
INNER JOIN projects AS p ON p.id = aa.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE aa.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetAIAuditByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetAIAuditByIDForUser(ctx context.Context, arg GetAIAuditByIDForUserParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, getAIAuditByIDForUser, arg.ID, arg.UserID)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const getAIAuditByLocationCrawlAndProject = `-- name: GetAIAuditByLocationCrawlAndProject :one
SELECT id, project_id, crawl_id, status, score, error_message, started_at, completed_at, created_at, updated_at, location_id
FROM ai_audits
WHERE project_id = $1::uuid
  AND location_id = $2::uuid
  AND crawl_id = $3::uuid
ORDER BY created_at DESC
LIMIT 1
`

type GetAIAuditByLocationCrawlAndProjectParams struct {
	ProjectID  pgtype.UUID
	LocationID pgtype.UUID
	CrawlID    pgtype.UUID
}

func (q *Queries) GetAIAuditByLocationCrawlAndProject(ctx context.Context, arg GetAIAuditByLocationCrawlAndProjectParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, getAIAuditByLocationCrawlAndProject, arg.ProjectID, arg.LocationID, arg.CrawlID)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const getAIAuditForWorker = `-- name: GetAIAuditForWorker :one
SELECT id, project_id, crawl_id, status, score, error_message, started_at, completed_at, created_at, updated_at, location_id
FROM ai_audits
WHERE id = $1::uuid
  AND project_id = $2::uuid
LIMIT 1
`

type GetAIAuditForWorkerParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetAIAuditForWorker(ctx context.Context, arg GetAIAuditForWorkerParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, getAIAuditForWorker, arg.ID, arg.ProjectID)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const getActiveAIAuditByCrawlAndProject = `-- name: GetActiveAIAuditByCrawlAndProject :one
SELECT id, project_id, crawl_id, status, score, error_message, started_at, completed_at, created_at, updated_at, location_id
FROM ai_audits
WHERE project_id = $1 AND crawl_id = $2 AND location_id IS NULL AND status IN ('queued', 'running')
LIMIT 1
`

type GetActiveAIAuditByCrawlAndProjectParams struct {
	ProjectID pgtype.UUID
	CrawlID   pgtype.UUID
}

func (q *Queries) GetActiveAIAuditByCrawlAndProject(ctx context.Context, arg GetActiveAIAuditByCrawlAndProjectParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, getActiveAIAuditByCrawlAndProject, arg.ProjectID, arg.CrawlID)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const getActiveAIAuditByLocationAndProject = `-- name: GetActiveAIAuditByLocationAndProject :one
SELECT id, project_id, crawl_id, status, score, error_message, started_at, completed_at, created_at, updated_at, location_id
FROM ai_audits
WHERE project_id = $1::uuid
  AND location_id = $2::uuid
  AND status IN ('queued', 'running')
LIMIT 1
`

type GetActiveAIAuditByLocationAndProjectParams struct {
	ProjectID  pgtype.UUID
	LocationID pgtype.UUID
}

func (q *Queries) GetActiveAIAuditByLocationAndProject(ctx context.Context, arg GetActiveAIAuditByLocationAndProjectParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, getActiveAIAuditByLocationAndProject, arg.ProjectID, arg.LocationID)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const listAIAuditsForLocation = `-- name: ListAIAuditsForLocation :many
SELECT
    id,
    project_id,
    crawl_id,
    status,
    score,
    error_message,
    started_at,
    completed_at,
    created_at,
    updated_at,
    location_id
FROM ai_audits
WHERE project_id = $1::uuid
  AND location_id = $2::uuid
  AND ($3::text = '' OR status = $3::text)
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListAIAuditsForLocationParams struct {
	ProjectID    pgtype.UUID
	LocationID   pgtype.UUID
	StatusFilter string
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListAIAuditsForLocation(ctx context.Context, arg ListAIAuditsForLocationParams) ([]AiAudit, error) {
	rows, err := q.db.Query(ctx, listAIAuditsForLocation,
		arg.ProjectID,
		arg.LocationID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiAudit
	for rows.Next() {
		var i AiAudit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CrawlID,
			&i.Status,
			&i.Score,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIAuditsForProject = `-- name: ListAIAuditsForProject :many
SELECT
    id,
    project_id,
    crawl_id,
    status,
    score,
    error_message,
    started_at,
    completed_at,
    created_at,
    updated_at,
    location_id
FROM ai_audits
WHERE project_id = $1
  AND location_id IS NULL
  AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListAIAuditsForProjectParams struct {
	ProjectID pgtype.UUID
	Column2   interface{}
	Limit     int32
	Offset    int32
}

func (q *Queries) ListAIAuditsForProject(ctx context.Context, arg ListAIAuditsForProjectParams) ([]AiAudit, error) {
	rows, err := q.db.Query(ctx, listAIAuditsForProject,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiAudit
	for rows.Next() {
		var i AiAudit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CrawlID,
			&i.Status,
			&i.Score,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reclaimStaleRunningAIAudits = `-- name: ReclaimStaleRunningAIAudits :exec
UPDATE ai_audits
SET status = 'failed', error_message = 'reclaimed: stale running audit', completed_at = NOW(), updated_at = NOW()
WHERE status = 'running'
  AND started_at < $1
`

// Marks ai_audits rows orphaned by a crashed worker process (stuck in
// 'running' past the cutoff) as failed, mirroring ReclaimStaleRunningAIWorkerJobs.
func (q *Queries) ReclaimStaleRunningAIAudits(ctx context.Context, startedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, reclaimStaleRunningAIAudits, startedAt)
	return err
}

const reserveAIWorkspaceMonthlyAudit = `-- name: ReserveAIWorkspaceMonthlyAudit :one
INSERT INTO ai_workspace_monthly_usage (organization_id, period_start, used_audits)
SELECT
    $1,
    date_trunc('month', now() AT TIME ZONE 'UTC')::date,
    1
WHERE $2::integer > 0
ON CONFLICT (organization_id, period_start) DO UPDATE
SET used_audits = ai_workspace_monthly_usage.used_audits + 1,
    updated_at = now()
WHERE ai_workspace_monthly_usage.used_audits < $2::integer
RETURNING used_audits
`

type ReserveAIWorkspaceMonthlyAuditParams struct {
	OrganizationID pgtype.UUID
	MonthlyLimit   int32
}

// Atomically reserves one visibility audit for the month. Returns no rows
// when the workspace limit is 0 (audits disabled) or already exhausted,
// mirroring ReserveAIWorkspaceMonthlyMessage.
func (q *Queries) ReserveAIWorkspaceMonthlyAudit(ctx context.Context, arg ReserveAIWorkspaceMonthlyAuditParams) (int32, error) {
	row := q.db.QueryRow(ctx, reserveAIWorkspaceMonthlyAudit, arg.OrganizationID, arg.MonthlyLimit)
	var used_audits int32
	err := row.Scan(&used_audits)
	return used_audits, err
}

const updateAIAuditStatus = `-- name: UpdateAIAuditStatus :exec
UPDATE ai_audits
SET status = $2, error_message = $3, started_at = $4, completed_at = $5, updated_at = NOW()
WHERE id = $1
`

type UpdateAIAuditStatusParams struct {
	ID           pgtype.UUID
	Status       string
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateAIAuditStatus(ctx context.Context, arg UpdateAIAuditStatusParams) error {
	_, err := q.db.Exec(ctx, updateAIAuditStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}
