// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_audit_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAIAuditRunsByAuditID = `-- name: ListAIAuditRunsByAuditID :many
SELECT
    aar.id,
    aar.audit_id,
    aar.prompt_id,
    aar.model_name,
    aar.status,
    aar.raw_response,
    aar.parsed_response_json,
    aar.mentioned_target,
    aar.target_rank,
    aar.visibility_score,
    aar.error_message,
    aar.started_at,
    aar.completed_at,
    aar.created_at,
    aar.updated_at
FROM ai_audit_runs AS aar
INNER JOIN ai_audit_prompts AS aap ON aap.id = aar.prompt_id
WHERE aar.audit_id = $1
ORDER BY aap.display_order ASC, aar.model_name ASC, aar.created_at ASC
`

func (q *Queries) ListAIAuditRunsByAuditID(ctx context.Context, auditID pgtype.UUID) ([]AiAuditRun, error) {
	rows, err := q.db.Query(ctx, listAIAuditRunsByAuditID, auditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiAuditRun
	for rows.Next() {
		var i AiAuditRun
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.PromptID,
			&i.ModelName,
			&i.Status,
			&i.RawResponse,
			&i.ParsedResponseJson,
			&i.MentionedTarget,
			&i.TargetRank,
			&i.VisibilityScore,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
