// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_audit_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAIAuditRunsByAuditID = `-- name: ListAIAuditRunsByAuditID :many
SELECT
    id,
    audit_id,
    question_text,
    display_order,
    model_name,
    status,
    raw_response,
    parsed_response_json,
    mentioned_target,
    target_rank,
    visibility_score,
    error_message,
    started_at,
    completed_at,
    created_at,
    updated_at
FROM ai_audit_runs
WHERE audit_id = $1
ORDER BY display_order ASC, model_name ASC
`

func (q *Queries) ListAIAuditRunsByAuditID(ctx context.Context, auditID pgtype.UUID) ([]AiAuditRun, error) {
	rows, err := q.db.Query(ctx, listAIAuditRunsByAuditID, auditID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiAuditRun
	for rows.Next() {
		var i AiAuditRun
		if err := rows.Scan(
			&i.ID,
			&i.AuditID,
			&i.QuestionText,
			&i.DisplayOrder,
			&i.ModelName,
			&i.Status,
			&i.RawResponse,
			&i.ParsedResponseJson,
			&i.MentionedTarget,
			&i.TargetRank,
			&i.VisibilityScore,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
