// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_audits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAIAuditsForProject = `-- name: CountAIAuditsForProject :one
SELECT COUNT(*)
FROM ai_audits
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
`

type CountAIAuditsForProjectParams struct {
	ProjectID pgtype.UUID
	Column2   interface{}
}

func (q *Queries) CountAIAuditsForProject(ctx context.Context, arg CountAIAuditsForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAIAuditsForProject, arg.ProjectID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIAudit = `-- name: CreateAIAudit :one
INSERT INTO ai_audits (
    project_id,
    crawl_id,
    status,
    score,
    error_message,
    started_at,
    completed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, project_id, crawl_id, status, score, error_message, started_at, completed_at, created_at, updated_at
`

type CreateAIAuditParams struct {
	ProjectID    pgtype.UUID
	CrawlID      pgtype.UUID
	Status       string
	Score        pgtype.Int4
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
}

func (q *Queries) CreateAIAudit(ctx context.Context, arg CreateAIAuditParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, createAIAudit,
		arg.ProjectID,
		arg.CrawlID,
		arg.Status,
		arg.Score,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIAuditByIDForUser = `-- name: GetAIAuditByIDForUser :one
SELECT
    aa.id,
    aa.project_id,
    aa.crawl_id,
    aa.status,
    aa.score,
    aa.error_message,
    aa.started_at,
    aa.completed_at,
    aa.created_at,
    aa.updated_at
FROM ai_audits AS aa
INNER JOIN projects AS p ON p.id = aa.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE aa.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetAIAuditByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetAIAuditByIDForUser(ctx context.Context, arg GetAIAuditByIDForUserParams) (AiAudit, error) {
	row := q.db.QueryRow(ctx, getAIAuditByIDForUser, arg.ID, arg.UserID)
	var i AiAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CrawlID,
		&i.Status,
		&i.Score,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIAuditsForProject = `-- name: ListAIAuditsForProject :many
SELECT
    id,
    project_id,
    crawl_id,
    status,
    score,
    error_message,
    started_at,
    completed_at,
    created_at,
    updated_at
FROM ai_audits
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListAIAuditsForProjectParams struct {
	ProjectID pgtype.UUID
	Column2   interface{}
	Limit     int32
	Offset    int32
}

func (q *Queries) ListAIAuditsForProject(ctx context.Context, arg ListAIAuditsForProjectParams) ([]AiAudit, error) {
	rows, err := q.db.Query(ctx, listAIAuditsForProject,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiAudit
	for rows.Next() {
		var i AiAudit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CrawlID,
			&i.Status,
			&i.Score,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
