// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAIConversationsForProjectForUser = `-- name: CountAIConversationsForProjectForUser :one
SELECT COUNT(*)
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ac.project_id = $1
  AND om.user_id = $2
  AND ac.location_id IS NOT DISTINCT FROM $3
`

type CountAIConversationsForProjectForUserParams struct {
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
	LocationID pgtype.UUID
}

func (q *Queries) CountAIConversationsForProjectForUser(ctx context.Context, arg CountAIConversationsForProjectForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAIConversationsForProjectForUser, arg.ProjectID, arg.UserID, arg.LocationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIConversationForUser = `-- name: CreateAIConversationForUser :one
INSERT INTO ai_conversations (project_id, created_by_user_id, title, location_id)
SELECT p.id, $1, 'New conversation', $2::uuid
FROM projects AS p
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE p.id = $3
  AND om.user_id = $1
RETURNING id, project_id, created_by_user_id, title, created_at, updated_at, location_id
`

type CreateAIConversationForUserParams struct {
	UserID     pgtype.UUID
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
}

func (q *Queries) CreateAIConversationForUser(ctx context.Context, arg CreateAIConversationForUserParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, createAIConversationForUser, arg.UserID, arg.LocationID, arg.ProjectID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedByUserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LocationID,
	)
	return i, err
}

const deleteAIConversationByIDForUser = `-- name: DeleteAIConversationByIDForUser :execrows
DELETE FROM ai_conversations AS ac
USING projects AS p, organization_members AS om
WHERE ac.id = $1
  AND ac.project_id = p.id
  AND om.org_id = p.organization_id
  AND om.user_id = $2
`

type DeleteAIConversationByIDForUserParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) DeleteAIConversationByIDForUser(ctx context.Context, arg DeleteAIConversationByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAIConversationByIDForUser, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAIConversationByIDForUser = `-- name: GetAIConversationByIDForUser :one
SELECT
    ac.id,
    ac.project_id,
    ac.created_by_user_id,
    ac.location_id,
    COALESCE(
        (
            SELECT COALESCE(
                NULLIF(left(regexp_replace(btrim(m.content), '[[:space:]]+', ' ', 'g'), 120), ''),
                CASE WHEN m.content_blocks IS NOT NULL AND jsonb_typeof(m.content_blocks) = 'array' AND jsonb_array_length(m.content_blocks) > 0 THEN 'Sent an image' END,
                ac.title
            )
            FROM ai_turns AS t
            INNER JOIN ai_messages AS m ON m.turn_id = t.id AND m.role = 'user'
            WHERE t.conversation_id = ac.id
            ORDER BY t.created_at ASC, t.id ASC, m.created_at ASC, m.id ASC
            LIMIT 1
        ),
        ac.title
    ) AS title,
    ac.created_at,
    ac.updated_at
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ac.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetAIConversationByIDForUserParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

type GetAIConversationByIDForUserRow struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	CreatedByUserID pgtype.UUID
	LocationID      pgtype.UUID
	Title           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetAIConversationByIDForUser(ctx context.Context, arg GetAIConversationByIDForUserParams) (GetAIConversationByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getAIConversationByIDForUser, arg.ConversationID, arg.UserID)
	var i GetAIConversationByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedByUserID,
		&i.LocationID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIConversationsForProjectForUser = `-- name: ListAIConversationsForProjectForUser :many
SELECT
    ac.id,
    ac.project_id,
    ac.created_by_user_id,
    ac.location_id,
    COALESCE(
        (
            SELECT COALESCE(
                NULLIF(left(regexp_replace(btrim(m.content), '[[:space:]]+', ' ', 'g'), 120), ''),
                CASE WHEN m.content_blocks IS NOT NULL AND jsonb_typeof(m.content_blocks) = 'array' AND jsonb_array_length(m.content_blocks) > 0 THEN 'Sent an image' END,
                ac.title
            )
            FROM ai_turns AS t
            INNER JOIN ai_messages AS m ON m.turn_id = t.id AND m.role = 'user'
            WHERE t.conversation_id = ac.id
            ORDER BY t.created_at ASC, t.id ASC, m.created_at ASC, m.id ASC
            LIMIT 1
        ),
        ac.title
    ) AS title,
    ac.created_at,
    ac.updated_at
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ac.project_id = $1
  AND om.user_id = $2
  AND ac.location_id IS NOT DISTINCT FROM $3
ORDER BY ac.updated_at DESC, ac.id DESC
LIMIT $5 OFFSET $4
`

type ListAIConversationsForProjectForUserParams struct {
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
	LocationID pgtype.UUID
	PageOffset int32
	PageLimit  int32
}

type ListAIConversationsForProjectForUserRow struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	CreatedByUserID pgtype.UUID
	LocationID      pgtype.UUID
	Title           string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListAIConversationsForProjectForUser(ctx context.Context, arg ListAIConversationsForProjectForUserParams) ([]ListAIConversationsForProjectForUserRow, error) {
	rows, err := q.db.Query(ctx, listAIConversationsForProjectForUser,
		arg.ProjectID,
		arg.UserID,
		arg.LocationID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIConversationsForProjectForUserRow
	for rows.Next() {
		var i ListAIConversationsForProjectForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatedByUserID,
			&i.LocationID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTurnsForConversations = `-- name: ListActiveTurnsForConversations :many
SELECT t.id AS turn_id, t.conversation_id, t.status
FROM ai_turns AS t
WHERE conversation_id = ANY($1::uuid[])
  AND status IN ('queued', 'running', 'waiting', 'waiting_for_user')
`

type ListActiveTurnsForConversationsRow struct {
	TurnID         pgtype.UUID
	ConversationID pgtype.UUID
	Status         string
}

func (q *Queries) ListActiveTurnsForConversations(ctx context.Context, conversationIds []pgtype.UUID) ([]ListActiveTurnsForConversationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTurnsForConversations, conversationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTurnsForConversationsRow
	for rows.Next() {
		var i ListActiveTurnsForConversationsRow
		if err := rows.Scan(&i.TurnID, &i.ConversationID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
