// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAIConversationsForProjectForUser = `-- name: CountAIConversationsForProjectForUser :one
SELECT COUNT(*)
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ac.project_id = $1
  AND om.user_id = $2
`

type CountAIConversationsForProjectForUserParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) CountAIConversationsForProjectForUser(ctx context.Context, arg CountAIConversationsForProjectForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAIConversationsForProjectForUser, arg.ProjectID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIConversationForUser = `-- name: CreateAIConversationForUser :one
INSERT INTO ai_conversations (project_id, created_by_user_id, title)
SELECT p.id, $1, 'New conversation'
FROM projects AS p
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE p.id = $2
  AND om.user_id = $1
RETURNING id, project_id, created_by_user_id, title, created_at, updated_at
`

type CreateAIConversationForUserParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) CreateAIConversationForUser(ctx context.Context, arg CreateAIConversationForUserParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, createAIConversationForUser, arg.UserID, arg.ProjectID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedByUserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAIConversationByIDForUser = `-- name: DeleteAIConversationByIDForUser :execrows
DELETE FROM ai_conversations AS ac
USING projects AS p, organization_members AS om
WHERE ac.id = $1
  AND ac.project_id = p.id
  AND om.org_id = p.organization_id
  AND om.user_id = $2
`

type DeleteAIConversationByIDForUserParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) DeleteAIConversationByIDForUser(ctx context.Context, arg DeleteAIConversationByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAIConversationByIDForUser, arg.ConversationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAIConversationByIDForUser = `-- name: GetAIConversationByIDForUser :one
SELECT
    ac.id,
    ac.project_id,
    ac.created_by_user_id,
    ac.title,
    ac.created_at,
    ac.updated_at
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ac.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetAIConversationByIDForUserParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) GetAIConversationByIDForUser(ctx context.Context, arg GetAIConversationByIDForUserParams) (AiConversation, error) {
	row := q.db.QueryRow(ctx, getAIConversationByIDForUser, arg.ConversationID, arg.UserID)
	var i AiConversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedByUserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIConversationsForProjectForUser = `-- name: ListAIConversationsForProjectForUser :many
SELECT
    ac.id,
    ac.project_id,
    ac.created_by_user_id,
    ac.title,
    ac.created_at,
    ac.updated_at
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ac.project_id = $1
  AND om.user_id = $2
ORDER BY ac.updated_at DESC, ac.id DESC
LIMIT $4 OFFSET $3
`

type ListAIConversationsForProjectForUserParams struct {
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListAIConversationsForProjectForUser(ctx context.Context, arg ListAIConversationsForProjectForUserParams) ([]AiConversation, error) {
	rows, err := q.db.Query(ctx, listAIConversationsForProjectForUser,
		arg.ProjectID,
		arg.UserID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiConversation
	for rows.Next() {
		var i AiConversation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CreatedByUserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
