// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIConversation = `-- name: CreateAIConversation :one
INSERT INTO ai_conversations (
    org_id,
    created_by_user_id,
    title
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, org_id, created_by_user_id, title, created_at, updated_at
`

type CreateAIConversationParams struct {
	OrgID           pgtype.UUID
	CreatedByUserID pgtype.UUID
	Title           pgtype.Text
}

type CreateAIConversationRow struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	CreatedByUserID pgtype.UUID
	Title           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateAIConversation(ctx context.Context, arg CreateAIConversationParams) (CreateAIConversationRow, error) {
	row := q.db.QueryRow(ctx, createAIConversation, arg.OrgID, arg.CreatedByUserID, arg.Title)
	var i CreateAIConversationRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedByUserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIMessage = `-- name: CreateAIMessage :one
INSERT INTO ai_messages (
    conversation_id,
    role,
    content,
    crawl_id,
    scope,
    model,
    reasoning_content,
    tool_calls,
    tool_call_id,
    tool_name
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, conversation_id, role, content, crawl_id, scope, model, reasoning_content, tool_calls, tool_call_id, tool_name, created_at
`

type CreateAIMessageParams struct {
	ConversationID   pgtype.UUID
	Role             string
	Content          string
	CrawlID          pgtype.UUID
	Scope            []byte
	Model            pgtype.Text
	ReasoningContent pgtype.Text
	ToolCalls        []byte
	ToolCallID       pgtype.Text
	ToolName         pgtype.Text
}

type CreateAIMessageRow struct {
	ID               pgtype.UUID
	ConversationID   pgtype.UUID
	Role             string
	Content          string
	CrawlID          pgtype.UUID
	Scope            []byte
	Model            pgtype.Text
	ReasoningContent pgtype.Text
	ToolCalls        []byte
	ToolCallID       pgtype.Text
	ToolName         pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateAIMessage(ctx context.Context, arg CreateAIMessageParams) (CreateAIMessageRow, error) {
	row := q.db.QueryRow(ctx, createAIMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.CrawlID,
		arg.Scope,
		arg.Model,
		arg.ReasoningContent,
		arg.ToolCalls,
		arg.ToolCallID,
		arg.ToolName,
	)
	var i CreateAIMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CrawlID,
		&i.Scope,
		&i.Model,
		&i.ReasoningContent,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.ToolName,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAIConversationForUser = `-- name: DeleteAIConversationForUser :one
DELETE FROM ai_conversations AS ac
USING organization_members AS om
WHERE ac.id = $1
  AND om.org_id = ac.org_id
  AND om.user_id = $2
RETURNING ac.id
`

type DeleteAIConversationForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteAIConversationForUser(ctx context.Context, arg DeleteAIConversationForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteAIConversationForUser, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAIConversationForUser = `-- name: GetAIConversationForUser :one
SELECT
    ac.id,
    ac.org_id,
    ac.created_by_user_id,
    ac.title,
    ac.created_at,
    ac.updated_at
FROM ai_conversations AS ac
INNER JOIN organization_members AS om ON om.org_id = ac.org_id
WHERE ac.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetAIConversationForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetAIConversationForUserRow struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	CreatedByUserID pgtype.UUID
	Title           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetAIConversationForUser(ctx context.Context, arg GetAIConversationForUserParams) (GetAIConversationForUserRow, error) {
	row := q.db.QueryRow(ctx, getAIConversationForUser, arg.ID, arg.UserID)
	var i GetAIConversationForUserRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedByUserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIConversationForUserForUpdate = `-- name: GetAIConversationForUserForUpdate :one
SELECT
    ac.id,
    ac.org_id,
    ac.created_by_user_id,
    ac.title,
    ac.created_at,
    ac.updated_at
FROM ai_conversations AS ac
INNER JOIN organization_members AS om ON om.org_id = ac.org_id
WHERE ac.id = $1
  AND om.user_id = $2
LIMIT 1
FOR UPDATE OF ac
`

type GetAIConversationForUserForUpdateParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetAIConversationForUserForUpdateRow struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	CreatedByUserID pgtype.UUID
	Title           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetAIConversationForUserForUpdate(ctx context.Context, arg GetAIConversationForUserForUpdateParams) (GetAIConversationForUserForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAIConversationForUserForUpdate, arg.ID, arg.UserID)
	var i GetAIConversationForUserForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedByUserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIConversationsForOrgForUser = `-- name: ListAIConversationsForOrgForUser :many
SELECT
    ac.id,
    ac.org_id,
    ac.created_by_user_id,
    ac.title,
    ac.created_at,
    ac.updated_at,
    (SELECT COUNT(*) FROM ai_messages am WHERE am.conversation_id = ac.id)::int AS message_count
FROM ai_conversations AS ac
INNER JOIN organization_members AS om ON om.org_id = ac.org_id
WHERE ac.org_id = $1
  AND om.user_id = $2
ORDER BY ac.updated_at DESC
LIMIT $3
OFFSET $4
`

type ListAIConversationsForOrgForUserParams struct {
	OrgID  pgtype.UUID
	UserID pgtype.UUID
	Limit  int32
	Offset int32
}

type ListAIConversationsForOrgForUserRow struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	CreatedByUserID pgtype.UUID
	Title           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	MessageCount    int32
}

func (q *Queries) ListAIConversationsForOrgForUser(ctx context.Context, arg ListAIConversationsForOrgForUserParams) ([]ListAIConversationsForOrgForUserRow, error) {
	rows, err := q.db.Query(ctx, listAIConversationsForOrgForUser,
		arg.OrgID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIConversationsForOrgForUserRow
	for rows.Next() {
		var i ListAIConversationsForOrgForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.CreatedByUserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIMessagesForConversationForUser = `-- name: ListAIMessagesForConversationForUser :many
SELECT
    am.id,
    am.conversation_id,
    am.role,
    am.content,
    am.crawl_id,
    am.scope,
    am.model,
    am.reasoning_content,
    am.tool_calls,
    am.tool_call_id,
    am.tool_name,
    am.created_at
FROM ai_messages AS am
INNER JOIN ai_conversations AS ac ON ac.id = am.conversation_id
INNER JOIN organization_members AS om ON om.org_id = ac.org_id
WHERE am.conversation_id = $1
  AND om.user_id = $2
ORDER BY am.created_at ASC
`

type ListAIMessagesForConversationForUserParams struct {
	ConversationID pgtype.UUID
	UserID         pgtype.UUID
}

type ListAIMessagesForConversationForUserRow struct {
	ID               pgtype.UUID
	ConversationID   pgtype.UUID
	Role             string
	Content          string
	CrawlID          pgtype.UUID
	Scope            []byte
	Model            pgtype.Text
	ReasoningContent pgtype.Text
	ToolCalls        []byte
	ToolCallID       pgtype.Text
	ToolName         pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListAIMessagesForConversationForUser(ctx context.Context, arg ListAIMessagesForConversationForUserParams) ([]ListAIMessagesForConversationForUserRow, error) {
	rows, err := q.db.Query(ctx, listAIMessagesForConversationForUser, arg.ConversationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIMessagesForConversationForUserRow
	for rows.Next() {
		var i ListAIMessagesForConversationForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CrawlID,
			&i.Scope,
			&i.Model,
			&i.ReasoningContent,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.ToolName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIConversationTouched = `-- name: UpdateAIConversationTouched :one
UPDATE ai_conversations
SET updated_at = now()
WHERE id = $1
RETURNING id, org_id, created_by_user_id, title, created_at, updated_at
`

type UpdateAIConversationTouchedRow struct {
	ID              pgtype.UUID
	OrgID           pgtype.UUID
	CreatedByUserID pgtype.UUID
	Title           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateAIConversationTouched(ctx context.Context, id pgtype.UUID) (UpdateAIConversationTouchedRow, error) {
	row := q.db.QueryRow(ctx, updateAIConversationTouched, id)
	var i UpdateAIConversationTouchedRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.CreatedByUserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
