// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_turns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIMessage = `-- name: CreateAIMessage :one
INSERT INTO ai_messages (turn_id, role, status, content)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id
`

type CreateAIMessageParams struct {
	TurnID  pgtype.UUID
	Role    string
	Status  string
	Content string
}

func (q *Queries) CreateAIMessage(ctx context.Context, arg CreateAIMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAIMessage,
		arg.TurnID,
		arg.Role,
		arg.Status,
		arg.Content,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createAITurn = `-- name: CreateAITurn :one
INSERT INTO ai_turns (
    conversation_id,
    created_by_user_id,
    status,
    requested_effort,
    effective_effort,
    model,
    prompt_version,
    crawl_id,
    client_request_id,
    request_hash,
    disabled_ai_tools
) VALUES (
    $1,
    $2,
    'queued',
    $3,
    $4,
    $5,
    'chat-v1',
    $6,
    $7,
    $8,
    COALESCE($9::TEXT[], ARRAY[]::TEXT[])
)
RETURNING id
`

type CreateAITurnParams struct {
	ConversationID  pgtype.UUID
	UserID          pgtype.UUID
	RequestedEffort string
	EffectiveEffort string
	Model           string
	CrawlID         pgtype.UUID
	ClientRequestID string
	RequestHash     []byte
	DisabledAiTools []string
}

func (q *Queries) CreateAITurn(ctx context.Context, arg CreateAITurnParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAITurn,
		arg.ConversationID,
		arg.UserID,
		arg.RequestedEffort,
		arg.EffectiveEffort,
		arg.Model,
		arg.CrawlID,
		arg.ClientRequestID,
		arg.RequestHash,
		arg.DisabledAiTools,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createCancelledAITurnEvent = `-- name: CreateCancelledAITurnEvent :exec
INSERT INTO ai_turn_events (turn_id, event_type, payload)
VALUES ($1, 'stopped', '{"error_code":"cancelled"}'::jsonb)
`

func (q *Queries) CreateCancelledAITurnEvent(ctx context.Context, turnID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, createCancelledAITurnEvent, turnID)
	return err
}

const findAITurnByClientRequestID = `-- name: FindAITurnByClientRequestID :one
SELECT
    t.id AS turn_id,
    user_message.id AS user_message_id,
    assistant_message.id AS assistant_message_id,
    t.request_hash
FROM ai_turns AS t
INNER JOIN ai_messages AS user_message ON user_message.turn_id = t.id
    AND user_message.role = 'user'
INNER JOIN ai_messages AS assistant_message ON assistant_message.turn_id = t.id
    AND assistant_message.role = 'assistant'
WHERE t.conversation_id = $1
  AND t.created_by_user_id = $2
  AND t.client_request_id = $3
`

type FindAITurnByClientRequestIDParams struct {
	ConversationID  pgtype.UUID
	UserID          pgtype.UUID
	ClientRequestID string
}

type FindAITurnByClientRequestIDRow struct {
	TurnID             pgtype.UUID
	UserMessageID      pgtype.UUID
	AssistantMessageID pgtype.UUID
	RequestHash        []byte
}

func (q *Queries) FindAITurnByClientRequestID(ctx context.Context, arg FindAITurnByClientRequestIDParams) (FindAITurnByClientRequestIDRow, error) {
	row := q.db.QueryRow(ctx, findAITurnByClientRequestID, arg.ConversationID, arg.UserID, arg.ClientRequestID)
	var i FindAITurnByClientRequestIDRow
	err := row.Scan(
		&i.TurnID,
		&i.UserMessageID,
		&i.AssistantMessageID,
		&i.RequestHash,
	)
	return i, err
}

const getAITurnForUser = `-- name: GetAITurnForUser :one
SELECT
    t.id,
    t.conversation_id,
    t.status,
    t.requested_effort,
    t.effective_effort,
    t.model,
    t.attempt_count,
    (t.cancel_requested_at IS NOT NULL)::boolean AS cancel_requested,
    t.prompt_tokens,
    t.reasoning_tokens,
    t.completion_tokens,
    t.total_tokens,
    t.error_code,
    t.queued_at,
    t.started_at,
    t.completed_at,
    t.created_at,
    t.updated_at
FROM ai_turns AS t
INNER JOIN ai_conversations AS c ON c.id = t.conversation_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    AND om.user_id = $1
WHERE t.id = $2
`

type GetAITurnForUserParams struct {
	UserID pgtype.UUID
	TurnID pgtype.UUID
}

type GetAITurnForUserRow struct {
	ID               pgtype.UUID
	ConversationID   pgtype.UUID
	Status           string
	RequestedEffort  string
	EffectiveEffort  string
	Model            string
	AttemptCount     int32
	CancelRequested  bool
	PromptTokens     pgtype.Int4
	ReasoningTokens  pgtype.Int4
	CompletionTokens pgtype.Int4
	TotalTokens      pgtype.Int4
	ErrorCode        pgtype.Text
	QueuedAt         pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetAITurnForUser(ctx context.Context, arg GetAITurnForUserParams) (GetAITurnForUserRow, error) {
	row := q.db.QueryRow(ctx, getAITurnForUser, arg.UserID, arg.TurnID)
	var i GetAITurnForUserRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.RequestedEffort,
		&i.EffectiveEffort,
		&i.Model,
		&i.AttemptCount,
		&i.CancelRequested,
		&i.PromptTokens,
		&i.ReasoningTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.ErrorCode,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompletedCrawlForProject = `-- name: GetCompletedCrawlForProject :one
SELECT id
FROM crawls
WHERE id = $1
  AND project_id = $2
  AND status = 'completed'
`

type GetCompletedCrawlForProjectParams struct {
	CrawlID   pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetCompletedCrawlForProject(ctx context.Context, arg GetCompletedCrawlForProjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCompletedCrawlForProject, arg.CrawlID, arg.ProjectID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLatestCompletedCrawlForProject = `-- name: GetLatestCompletedCrawlForProject :one
SELECT id
FROM crawls
WHERE project_id = $1
  AND status = 'completed'
ORDER BY completed_at DESC NULLS LAST, id DESC
LIMIT 1
`

func (q *Queries) GetLatestCompletedCrawlForProject(ctx context.Context, projectID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedCrawlForProject, projectID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const hasActiveAITurnForConversation = `-- name: HasActiveAITurnForConversation :one
SELECT EXISTS(
    SELECT 1
    FROM ai_turns
    WHERE conversation_id = $1
      AND status IN ('queued', 'running')
)
`

func (q *Queries) HasActiveAITurnForConversation(ctx context.Context, conversationID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAITurnForConversation, conversationID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAIMessagesForConversation = `-- name: ListAIMessagesForConversation :many
SELECT m.id, m.role, m.status, m.content, m.created_at, m.updated_at
FROM ai_messages AS m
INNER JOIN ai_turns AS t ON t.id = m.turn_id
WHERE t.conversation_id = $1
  AND m.role IN ('user', 'assistant')
ORDER BY t.created_at ASC, t.id ASC, m.created_at ASC, m.id ASC
`

type ListAIMessagesForConversationRow struct {
	ID        pgtype.UUID
	Role      string
	Status    string
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListAIMessagesForConversation(ctx context.Context, conversationID pgtype.UUID) ([]ListAIMessagesForConversationRow, error) {
	rows, err := q.db.Query(ctx, listAIMessagesForConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIMessagesForConversationRow
	for rows.Next() {
		var i ListAIMessagesForConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIMessagesForUser = `-- name: ListAIMessagesForUser :many
SELECT m.id, m.role, m.status, m.content, m.created_at, m.updated_at
FROM ai_messages AS m
INNER JOIN ai_turns AS t ON t.id = m.turn_id
INNER JOIN ai_conversations AS c ON c.id = t.conversation_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    AND om.user_id = $1
WHERE m.turn_id = $2
ORDER BY CASE m.role WHEN 'user' THEN 0 ELSE 1 END
`

type ListAIMessagesForUserParams struct {
	UserID pgtype.UUID
	TurnID pgtype.UUID
}

type ListAIMessagesForUserRow struct {
	ID        pgtype.UUID
	Role      string
	Status    string
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListAIMessagesForUser(ctx context.Context, arg ListAIMessagesForUserParams) ([]ListAIMessagesForUserRow, error) {
	rows, err := q.db.Query(ctx, listAIMessagesForUser, arg.UserID, arg.TurnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIMessagesForUserRow
	for rows.Next() {
		var i ListAIMessagesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAITurnEventsForUser = `-- name: ListAITurnEventsForUser :many
SELECT e.id, e.event_type, e.payload
FROM ai_turn_events AS e
INNER JOIN ai_turns AS t ON t.id = e.turn_id
INNER JOIN ai_conversations AS c ON c.id = t.conversation_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    AND om.user_id = $1
WHERE e.turn_id = $2
  AND e.id > $3::bigint
ORDER BY e.id ASC
LIMIT 100
`

type ListAITurnEventsForUserParams struct {
	UserID  pgtype.UUID
	TurnID  pgtype.UUID
	AfterID int64
}

type ListAITurnEventsForUserRow struct {
	ID        int64
	EventType string
	Payload   []byte
}

func (q *Queries) ListAITurnEventsForUser(ctx context.Context, arg ListAITurnEventsForUserParams) ([]ListAITurnEventsForUserRow, error) {
	rows, err := q.db.Query(ctx, listAITurnEventsForUser, arg.UserID, arg.TurnID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAITurnEventsForUserRow
	for rows.Next() {
		var i ListAITurnEventsForUserRow
		if err := rows.Scan(&i.ID, &i.EventType, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAIConversationForTurn = `-- name: LockAIConversationForTurn :one
SELECT
    ac.project_id,
    p.organization_id,
    COALESCE(f.ai_chat, TRUE)::boolean AS ai_chat,
    COALESCE(f.ai_monthly_message_limit, 50)::integer AS ai_monthly_message_limit,
    COALESCE(
        f.ai_allowed_reasoning_efforts,
        ARRAY['none', 'low', 'high', 'max']::TEXT[]
    ) AS ai_allowed_reasoning_efforts,
    COALESCE(f.disabled_ai_tools, ARRAY[]::TEXT[]) AS disabled_ai_tools
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    AND om.user_id = $1
LEFT JOIN organization_features AS f ON f.org_id = p.organization_id
WHERE ac.id = $2
FOR UPDATE OF ac
FOR KEY SHARE OF om
`

type LockAIConversationForTurnParams struct {
	UserID         pgtype.UUID
	ConversationID pgtype.UUID
}

type LockAIConversationForTurnRow struct {
	ProjectID                 pgtype.UUID
	OrganizationID            pgtype.UUID
	AiChat                    bool
	AiMonthlyMessageLimit     int32
	AiAllowedReasoningEfforts []string
	DisabledAiTools           []string
}

func (q *Queries) LockAIConversationForTurn(ctx context.Context, arg LockAIConversationForTurnParams) (LockAIConversationForTurnRow, error) {
	row := q.db.QueryRow(ctx, lockAIConversationForTurn, arg.UserID, arg.ConversationID)
	var i LockAIConversationForTurnRow
	err := row.Scan(
		&i.ProjectID,
		&i.OrganizationID,
		&i.AiChat,
		&i.AiMonthlyMessageLimit,
		&i.AiAllowedReasoningEfforts,
		&i.DisabledAiTools,
	)
	return i, err
}

const lockAITurnForUser = `-- name: LockAITurnForUser :one
SELECT
    t.id,
    t.conversation_id,
    t.status,
    t.requested_effort,
    t.effective_effort,
    t.model,
    t.attempt_count,
    (t.cancel_requested_at IS NOT NULL)::boolean AS cancel_requested,
    t.prompt_tokens,
    t.reasoning_tokens,
    t.completion_tokens,
    t.total_tokens,
    t.error_code,
    t.queued_at,
    t.started_at,
    t.completed_at,
    t.created_at,
    t.updated_at
FROM ai_turns AS t
INNER JOIN ai_conversations AS c ON c.id = t.conversation_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    AND om.user_id = $1
WHERE t.id = $2
FOR UPDATE OF t
FOR KEY SHARE OF om
`

type LockAITurnForUserParams struct {
	UserID pgtype.UUID
	TurnID pgtype.UUID
}

type LockAITurnForUserRow struct {
	ID               pgtype.UUID
	ConversationID   pgtype.UUID
	Status           string
	RequestedEffort  string
	EffectiveEffort  string
	Model            string
	AttemptCount     int32
	CancelRequested  bool
	PromptTokens     pgtype.Int4
	ReasoningTokens  pgtype.Int4
	CompletionTokens pgtype.Int4
	TotalTokens      pgtype.Int4
	ErrorCode        pgtype.Text
	QueuedAt         pgtype.Timestamptz
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) LockAITurnForUser(ctx context.Context, arg LockAITurnForUserParams) (LockAITurnForUserRow, error) {
	row := q.db.QueryRow(ctx, lockAITurnForUser, arg.UserID, arg.TurnID)
	var i LockAITurnForUserRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Status,
		&i.RequestedEffort,
		&i.EffectiveEffort,
		&i.Model,
		&i.AttemptCount,
		&i.CancelRequested,
		&i.PromptTokens,
		&i.ReasoningTokens,
		&i.CompletionTokens,
		&i.TotalTokens,
		&i.ErrorCode,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markCancelledAssistantMessage = `-- name: MarkCancelledAssistantMessage :exec
UPDATE ai_messages
SET status = 'partial', updated_at = now()
WHERE turn_id = $1 AND role = 'assistant' AND status = 'pending'
`

func (q *Queries) MarkCancelledAssistantMessage(ctx context.Context, turnID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCancelledAssistantMessage, turnID)
	return err
}

const requestCancelRunningAITurn = `-- name: RequestCancelRunningAITurn :execrows
UPDATE ai_turns
SET cancel_requested_at = COALESCE(cancel_requested_at, now()),
    updated_at = now()
WHERE id = $1 AND status = 'running'
`

func (q *Queries) RequestCancelRunningAITurn(ctx context.Context, turnID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requestCancelRunningAITurn, turnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveAIWorkspaceMonthlyMessage = `-- name: ReserveAIWorkspaceMonthlyMessage :one
INSERT INTO ai_workspace_monthly_usage (organization_id, period_start, used_messages)
SELECT
    $1,
    date_trunc('month', now() AT TIME ZONE 'UTC')::date,
    1
WHERE $2::integer > 0
ON CONFLICT (organization_id, period_start) DO UPDATE
SET used_messages = ai_workspace_monthly_usage.used_messages + 1,
    updated_at = now()
WHERE ai_workspace_monthly_usage.used_messages < $2::integer
RETURNING used_messages
`

type ReserveAIWorkspaceMonthlyMessageParams struct {
	OrganizationID pgtype.UUID
	MonthlyLimit   int32
}

func (q *Queries) ReserveAIWorkspaceMonthlyMessage(ctx context.Context, arg ReserveAIWorkspaceMonthlyMessageParams) (int32, error) {
	row := q.db.QueryRow(ctx, reserveAIWorkspaceMonthlyMessage, arg.OrganizationID, arg.MonthlyLimit)
	var used_messages int32
	err := row.Scan(&used_messages)
	return used_messages, err
}

const stopQueuedAITurn = `-- name: StopQueuedAITurn :execrows
UPDATE ai_turns
SET cancel_requested_at = COALESCE(cancel_requested_at, now()),
    status = 'stopped',
    error_code = 'cancelled',
    completed_at = now(),
    updated_at = now()
WHERE id = $1 AND status = 'queued'
`

func (q *Queries) StopQueuedAITurn(ctx context.Context, turnID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, stopQueuedAITurn, turnID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAIConversation = `-- name: TouchAIConversation :exec
UPDATE ai_conversations
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchAIConversation(ctx context.Context, conversationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAIConversation, conversationID)
	return err
}
