// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_tool_calls.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAIToolCall = `-- name: CompleteAIToolCall :exec
UPDATE ai_tool_calls
SET status = $1,
    result_content = $2,
    summary = $3,
    updated_at = now()
WHERE id = $4
`

type CompleteAIToolCallParams struct {
	Status        string
	ResultContent string
	Summary       string
	ID            pgtype.UUID
}

func (q *Queries) CompleteAIToolCall(ctx context.Context, arg CompleteAIToolCallParams) error {
	_, err := q.db.Exec(ctx, completeAIToolCall,
		arg.Status,
		arg.ResultContent,
		arg.Summary,
		arg.ID,
	)
	return err
}

const insertAIToolCall = `-- name: InsertAIToolCall :one
INSERT INTO ai_tool_calls (turn_id, seq, call_id, name, args, status)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::jsonb,
    $6
)
RETURNING id
`

type InsertAIToolCallParams struct {
	TurnID pgtype.UUID
	Seq    int32
	CallID string
	Name   string
	Args   []byte
	Status string
}

func (q *Queries) InsertAIToolCall(ctx context.Context, arg InsertAIToolCallParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAIToolCall,
		arg.TurnID,
		arg.Seq,
		arg.CallID,
		arg.Name,
		arg.Args,
		arg.Status,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listAIToolCallsForTurn = `-- name: ListAIToolCallsForTurn :many
SELECT call_id, name, args, status, summary, seq, created_at
FROM ai_tool_calls
WHERE turn_id = $1
ORDER BY seq ASC
`

type ListAIToolCallsForTurnRow struct {
	CallID    string
	Name      string
	Args      []byte
	Status    string
	Summary   string
	Seq       int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAIToolCallsForTurn(ctx context.Context, turnID pgtype.UUID) ([]ListAIToolCallsForTurnRow, error) {
	rows, err := q.db.Query(ctx, listAIToolCallsForTurn, turnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIToolCallsForTurnRow
	for rows.Next() {
		var i ListAIToolCallsForTurnRow
		if err := rows.Scan(
			&i.CallID,
			&i.Name,
			&i.Args,
			&i.Status,
			&i.Summary,
			&i.Seq,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
