// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_worker_jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingAIWorkerJob = `-- name: ClaimNextPendingAIWorkerJob :one
UPDATE ai_worker_jobs
SET status = 'running', started_at = NOW(), updated_at = NOW()
WHERE id = (
    SELECT id FROM ai_worker_jobs
    WHERE status = 'pending'
    ORDER BY created_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, job_type, project_id, status, error_message, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimNextPendingAIWorkerJob(ctx context.Context) (AiWorkerJob, error) {
	row := q.db.QueryRow(ctx, claimNextPendingAIWorkerJob)
	var i AiWorkerJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.ProjectID,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueAIWorkerJob = `-- name: EnqueueAIWorkerJob :one
INSERT INTO ai_worker_jobs (job_type, project_id)
VALUES ($1, $2)
RETURNING id, job_type, project_id, status, error_message, started_at, completed_at, created_at, updated_at
`

type EnqueueAIWorkerJobParams struct {
	JobType   string
	ProjectID pgtype.UUID
}

func (q *Queries) EnqueueAIWorkerJob(ctx context.Context, arg EnqueueAIWorkerJobParams) (AiWorkerJob, error) {
	row := q.db.QueryRow(ctx, enqueueAIWorkerJob, arg.JobType, arg.ProjectID)
	var i AiWorkerJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.ProjectID,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAIWorkerJobCompleted = `-- name: MarkAIWorkerJobCompleted :exec
UPDATE ai_worker_jobs
SET status = 'completed', completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAIWorkerJobCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAIWorkerJobCompleted, id)
	return err
}

const markAIWorkerJobFailed = `-- name: MarkAIWorkerJobFailed :exec
UPDATE ai_worker_jobs
SET status = 'failed', error_message = $2, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type MarkAIWorkerJobFailedParams struct {
	ID           pgtype.UUID
	ErrorMessage pgtype.Text
}

func (q *Queries) MarkAIWorkerJobFailed(ctx context.Context, arg MarkAIWorkerJobFailedParams) error {
	_, err := q.db.Exec(ctx, markAIWorkerJobFailed, arg.ID, arg.ErrorMessage)
	return err
}
