// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, token_prefix, token_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, token_prefix, created_at, last_used_at, revoked_at
`

type CreateAPIKeyParams struct {
	UserID      pgtype.UUID
	Name        string
	TokenPrefix string
	TokenHash   string
}

type CreateAPIKeyRow struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	TokenPrefix string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.TokenPrefix,
		arg.TokenHash,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAgentSetupCode = `-- name: CreateAgentSetupCode :one
INSERT INTO agent_setup_codes (user_id, name, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, expires_at, redeemed_at, created_at
`

type CreateAgentSetupCodeParams struct {
	UserID    pgtype.UUID
	Name      string
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
}

type CreateAgentSetupCodeRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	ExpiresAt  pgtype.Timestamptz
	RedeemedAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateAgentSetupCode(ctx context.Context, arg CreateAgentSetupCodeParams) (CreateAgentSetupCodeRow, error) {
	row := q.db.QueryRow(ctx, createAgentSetupCode,
		arg.UserID,
		arg.Name,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i CreateAgentSetupCodeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAgentSetupCodes = `-- name: DeleteExpiredAgentSetupCodes :execrows
DELETE FROM agent_setup_codes
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAgentSetupCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAgentSetupCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAPIKeyWithUserByTokenHash = `-- name: GetActiveAPIKeyWithUserByTokenHash :one
SELECT
    ak.id AS api_key_id,
    ak.user_id,
    ak.token_prefix,
    ak.last_used_at,
    u.auth_provider,
    u.auth_subject,
    u.email,
    u.name,
    u.status
FROM api_keys AS ak
INNER JOIN users AS u ON u.id = ak.user_id
WHERE ak.token_hash = $1
  AND ak.revoked_at IS NULL
LIMIT 1
`

type GetActiveAPIKeyWithUserByTokenHashRow struct {
	ApiKeyID     pgtype.UUID
	UserID       pgtype.UUID
	TokenPrefix  string
	LastUsedAt   pgtype.Timestamptz
	AuthProvider string
	AuthSubject  string
	Email        string
	Name         pgtype.Text
	Status       string
}

func (q *Queries) GetActiveAPIKeyWithUserByTokenHash(ctx context.Context, tokenHash string) (GetActiveAPIKeyWithUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyWithUserByTokenHash, tokenHash)
	var i GetActiveAPIKeyWithUserByTokenHashRow
	err := row.Scan(
		&i.ApiKeyID,
		&i.UserID,
		&i.TokenPrefix,
		&i.LastUsedAt,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getAgentSetupCodeForUpdate = `-- name: GetAgentSetupCodeForUpdate :one
SELECT
    ascodes.id,
    ascodes.user_id,
    ascodes.name,
    ascodes.expires_at,
    ascodes.redeemed_at,
    u.status AS user_status
FROM agent_setup_codes AS ascodes
INNER JOIN users AS u ON u.id = ascodes.user_id
WHERE ascodes.code_hash = $1
FOR UPDATE OF ascodes
`

type GetAgentSetupCodeForUpdateRow struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Name       string
	ExpiresAt  pgtype.Timestamptz
	RedeemedAt pgtype.Timestamptz
	UserStatus string
}

func (q *Queries) GetAgentSetupCodeForUpdate(ctx context.Context, codeHash string) (GetAgentSetupCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAgentSetupCodeForUpdate, codeHash)
	var i GetAgentSetupCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.UserStatus,
	)
	return i, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, name, token_prefix, created_at, last_used_at, revoked_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysForUserRow struct {
	ID          pgtype.UUID
	Name        string
	TokenPrefix string
	CreatedAt   pgtype.Timestamptz
	LastUsedAt  pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
}

func (q *Queries) ListAPIKeysForUser(ctx context.Context, userID pgtype.UUID) ([]ListAPIKeysForUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysForUserRow
	for rows.Next() {
		var i ListAPIKeysForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentSetupCodeRedeemed = `-- name: MarkAgentSetupCodeRedeemed :execrows
UPDATE agent_setup_codes
SET redeemed_at = now()
WHERE id = $1
  AND redeemed_at IS NULL
`

func (q *Queries) MarkAgentSetupCodeRedeemed(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAgentSetupCodeRedeemed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIKeyForUser = `-- name: RevokeAPIKeyForUser :execrows
UPDATE api_keys
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
  AND user_id = $2
`

type RevokeAPIKeyForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) RevokeAPIKeyForUser(ctx context.Context, arg RevokeAPIKeyForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIKeyForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIKeyLastUsedAt = `-- name: TouchAPIKeyLastUsedAt :execrows
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND (last_used_at IS NULL OR last_used_at <= now() - interval '5 minutes')
`

func (q *Queries) TouchAPIKeyLastUsedAt(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchAPIKeyLastUsedAt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
