// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_profile.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectBusinessProfileByProjectID = `-- name: GetProjectBusinessProfileByProjectID :one
SELECT id, project_id, brand_name, website_url, primary_category, primary_location, business_description, seed_prompts, created_at, updated_at
FROM project_business_profile
WHERE project_id = $1
LIMIT 1
`

type GetProjectBusinessProfileByProjectIDRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	BrandName           string
	WebsiteUrl          string
	PrimaryCategory     pgtype.Text
	PrimaryLocation     pgtype.Text
	BusinessDescription pgtype.Text
	SeedPrompts         []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetProjectBusinessProfileByProjectID(ctx context.Context, projectID pgtype.UUID) (GetProjectBusinessProfileByProjectIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectBusinessProfileByProjectID, projectID)
	var i GetProjectBusinessProfileByProjectIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BrandName,
		&i.WebsiteUrl,
		&i.PrimaryCategory,
		&i.PrimaryLocation,
		&i.BusinessDescription,
		&i.SeedPrompts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectBusinessProfile = `-- name: UpsertProjectBusinessProfile :one
INSERT INTO project_business_profile (
    project_id,
    brand_name,
    website_url,
    primary_category,
    primary_location,
    business_description,
    seed_prompts
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (project_id) DO UPDATE SET
    brand_name = excluded.brand_name,
    website_url = excluded.website_url,
    primary_category = excluded.primary_category,
    primary_location = excluded.primary_location,
    business_description = excluded.business_description,
    seed_prompts = excluded.seed_prompts,
    updated_at = now()
RETURNING id, project_id, brand_name, website_url, primary_category, primary_location, business_description, seed_prompts, created_at, updated_at
`

type UpsertProjectBusinessProfileParams struct {
	ProjectID           pgtype.UUID
	BrandName           string
	WebsiteUrl          string
	PrimaryCategory     pgtype.Text
	PrimaryLocation     pgtype.Text
	BusinessDescription pgtype.Text
	SeedPrompts         []byte
}

type UpsertProjectBusinessProfileRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	BrandName           string
	WebsiteUrl          string
	PrimaryCategory     pgtype.Text
	PrimaryLocation     pgtype.Text
	BusinessDescription pgtype.Text
	SeedPrompts         []byte
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) UpsertProjectBusinessProfile(ctx context.Context, arg UpsertProjectBusinessProfileParams) (UpsertProjectBusinessProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectBusinessProfile,
		arg.ProjectID,
		arg.BrandName,
		arg.WebsiteUrl,
		arg.PrimaryCategory,
		arg.PrimaryLocation,
		arg.BusinessDescription,
		arg.SeedPrompts,
	)
	var i UpsertProjectBusinessProfileRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BrandName,
		&i.WebsiteUrl,
		&i.PrimaryCategory,
		&i.PrimaryLocation,
		&i.BusinessDescription,
		&i.SeedPrompts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
