// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawls.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelCrawlByIDForUser = `-- name: CancelCrawlByIDForUser :one
UPDATE crawls AS c
SET status = 'cancelled',
    completed_at = now()
FROM projects AS p, organization_members AS om
WHERE c.id = $1
  AND c.project_id = p.id
  AND p.organization_id = om.org_id
  AND om.user_id = $2
  AND c.status IN ('queued', 'running')
RETURNING c.id
`

type CancelCrawlByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) CancelCrawlByIDForUser(ctx context.Context, arg CancelCrawlByIDForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, cancelCrawlByIDForUser, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const claimNextQueuedCrawlAuto = `-- name: ClaimNextQueuedCrawlAuto :one
WITH candidate AS (
    SELECT c.id
    FROM crawls AS c
    WHERE c.status = 'queued'
      AND c.source = 'auto'
      AND NOT EXISTS (
          SELECT 1
          FROM crawls AS running
          WHERE running.status = 'running'
            AND running.project_id = c.project_id
      )
    ORDER BY c.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE crawls AS c
SET status = 'running',
    started_at = now(),
    completed_at = NULL
FROM candidate, projects AS p
WHERE c.id = candidate.id
  AND p.id = c.project_id
RETURNING c.id, c.project_id, c.requested_by_user_id, c.config_snapshot, p.base_url
`

type ClaimNextQueuedCrawlAutoRow struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	RequestedByUserID pgtype.UUID
	ConfigSnapshot    []byte
	BaseUrl           string
}

func (q *Queries) ClaimNextQueuedCrawlAuto(ctx context.Context) (ClaimNextQueuedCrawlAutoRow, error) {
	row := q.db.QueryRow(ctx, claimNextQueuedCrawlAuto)
	var i ClaimNextQueuedCrawlAutoRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.ConfigSnapshot,
		&i.BaseUrl,
	)
	return i, err
}

const claimNextQueuedCrawlManual = `-- name: ClaimNextQueuedCrawlManual :one
WITH candidate AS (
    SELECT c.id
    FROM crawls AS c
    WHERE c.status = 'queued'
      AND c.source = 'manual'
      AND NOT EXISTS (
          SELECT 1
          FROM crawls AS running
          WHERE running.status = 'running'
            AND running.requested_by_user_id = c.requested_by_user_id
            AND c.requested_by_user_id IS NOT NULL
      )
    ORDER BY c.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE crawls AS c
SET status = 'running',
    started_at = now(),
    completed_at = NULL
FROM candidate, projects AS p
WHERE c.id = candidate.id
  AND p.id = c.project_id
RETURNING c.id, c.project_id, c.requested_by_user_id, c.config_snapshot, p.base_url
`

type ClaimNextQueuedCrawlManualRow struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	RequestedByUserID pgtype.UUID
	ConfigSnapshot    []byte
	BaseUrl           string
}

func (q *Queries) ClaimNextQueuedCrawlManual(ctx context.Context) (ClaimNextQueuedCrawlManualRow, error) {
	row := q.db.QueryRow(ctx, claimNextQueuedCrawlManual)
	var i ClaimNextQueuedCrawlManualRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.ConfigSnapshot,
		&i.BaseUrl,
	)
	return i, err
}

const countCrawlsForProject = `-- name: CountCrawlsForProject :one
SELECT COUNT(*)
FROM crawls
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
`

type CountCrawlsForProjectParams struct {
	ProjectID pgtype.UUID
	Column2   interface{}
}

func (q *Queries) CountCrawlsForProject(ctx context.Context, arg CountCrawlsForProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlsForProject, arg.ProjectID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCrawl = `-- name: CreateCrawl :one
INSERT INTO crawls (
    project_id,
    requested_by_user_id,
    source,
    status,
    config_snapshot,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, project_id, status, phase, config_snapshot, urls_discovered, urls_crawled, max_depth_reached, google_psi_results, has_llms_txt, seo_score, aeo_score, pagespeed_score, overall_score, started_at, completed_at, created_at
`

type CreateCrawlParams struct {
	ProjectID         pgtype.UUID
	RequestedByUserID pgtype.UUID
	Source            string
	Status            string
	ConfigSnapshot    []byte
	StartedAt         pgtype.Timestamptz
}

type CreateCrawlRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	Phase            pgtype.Text
	ConfigSnapshot   []byte
	UrlsDiscovered   int32
	UrlsCrawled      int32
	MaxDepthReached  int32
	GooglePsiResults []byte
	HasLlmsTxt       pgtype.Bool
	SeoScore         pgtype.Int4
	AeoScore         pgtype.Int4
	PagespeedScore   pgtype.Int4
	OverallScore     pgtype.Int4
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCrawl(ctx context.Context, arg CreateCrawlParams) (CreateCrawlRow, error) {
	row := q.db.QueryRow(ctx, createCrawl,
		arg.ProjectID,
		arg.RequestedByUserID,
		arg.Source,
		arg.Status,
		arg.ConfigSnapshot,
		arg.StartedAt,
	)
	var i CreateCrawlRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.Phase,
		&i.ConfigSnapshot,
		&i.UrlsDiscovered,
		&i.UrlsCrawled,
		&i.MaxDepthReached,
		&i.GooglePsiResults,
		&i.HasLlmsTxt,
		&i.SeoScore,
		&i.AeoScore,
		&i.PagespeedScore,
		&i.OverallScore,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCrawlByIDForUser = `-- name: DeleteCrawlByIDForUser :one
DELETE FROM crawls AS c
USING projects AS p, organization_members AS om
WHERE c.id = $1
  AND c.project_id = p.id
  AND p.organization_id = om.org_id
  AND om.user_id = $2
  AND c.status NOT IN ('queued', 'running')
RETURNING c.id
`

type DeleteCrawlByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteCrawlByIDForUser(ctx context.Context, arg DeleteCrawlByIDForUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCrawlByIDForUser, arg.ID, arg.UserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCrawlByIDForUser = `-- name: GetCrawlByIDForUser :one
SELECT
    c.id,
    c.project_id,
    c.status,
    c.phase,
    c.config_snapshot,
    c.urls_discovered,
    c.urls_crawled,
    c.max_depth_reached,
    c.google_psi_results,
    c.has_llms_txt,
    c.seo_score,
    c.aeo_score,
    c.pagespeed_score,
    c.overall_score,
    c.started_at,
    c.completed_at,
    c.created_at
FROM crawls AS c
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE c.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetCrawlByIDForUserRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	Phase            pgtype.Text
	ConfigSnapshot   []byte
	UrlsDiscovered   int32
	UrlsCrawled      int32
	MaxDepthReached  int32
	GooglePsiResults []byte
	HasLlmsTxt       pgtype.Bool
	SeoScore         pgtype.Int4
	AeoScore         pgtype.Int4
	PagespeedScore   pgtype.Int4
	OverallScore     pgtype.Int4
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetCrawlByIDForUser(ctx context.Context, arg GetCrawlByIDForUserParams) (GetCrawlByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getCrawlByIDForUser, arg.ID, arg.UserID)
	var i GetCrawlByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.Phase,
		&i.ConfigSnapshot,
		&i.UrlsDiscovered,
		&i.UrlsCrawled,
		&i.MaxDepthReached,
		&i.GooglePsiResults,
		&i.HasLlmsTxt,
		&i.SeoScore,
		&i.AeoScore,
		&i.PagespeedScore,
		&i.OverallScore,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlOrgID = `-- name: GetCrawlOrgID :one
SELECT p.organization_id
FROM crawls c
INNER JOIN projects p ON p.id = c.project_id
WHERE c.id = $1
LIMIT 1
`

func (q *Queries) GetCrawlOrgID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCrawlOrgID, id)
	var organization_id pgtype.UUID
	err := row.Scan(&organization_id)
	return organization_id, err
}

const listActiveCrawlsForOrganization = `-- name: ListActiveCrawlsForOrganization :many
SELECT
    c.id,
    c.project_id,
    c.status,
    c.phase,
    c.urls_discovered,
    c.urls_crawled,
    c.created_at
FROM crawls AS c
INNER JOIN projects AS p ON p.id = c.project_id
WHERE p.organization_id = $1
  AND c.status IN ('queued', 'running')
ORDER BY c.created_at DESC
`

type ListActiveCrawlsForOrganizationRow struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	Status         string
	Phase          pgtype.Text
	UrlsDiscovered int32
	UrlsCrawled    int32
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListActiveCrawlsForOrganization(ctx context.Context, organizationID pgtype.UUID) ([]ListActiveCrawlsForOrganizationRow, error) {
	rows, err := q.db.Query(ctx, listActiveCrawlsForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCrawlsForOrganizationRow
	for rows.Next() {
		var i ListActiveCrawlsForOrganizationRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.Phase,
			&i.UrlsDiscovered,
			&i.UrlsCrawled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlsForProject = `-- name: ListCrawlsForProject :many
SELECT
    id,
    project_id,
    status,
    phase,
    config_snapshot,
    urls_discovered,
    urls_crawled,
    max_depth_reached,
    google_psi_results,
    has_llms_txt,
    seo_score,
    aeo_score,
    pagespeed_score,
    overall_score,
    started_at,
    completed_at,
    created_at
FROM crawls
WHERE project_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListCrawlsForProjectParams struct {
	ProjectID pgtype.UUID
	Column2   interface{}
	Limit     int32
	Offset    int32
}

type ListCrawlsForProjectRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	Phase            pgtype.Text
	ConfigSnapshot   []byte
	UrlsDiscovered   int32
	UrlsCrawled      int32
	MaxDepthReached  int32
	GooglePsiResults []byte
	HasLlmsTxt       pgtype.Bool
	SeoScore         pgtype.Int4
	AeoScore         pgtype.Int4
	PagespeedScore   pgtype.Int4
	OverallScore     pgtype.Int4
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListCrawlsForProject(ctx context.Context, arg ListCrawlsForProjectParams) ([]ListCrawlsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listCrawlsForProject,
		arg.ProjectID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlsForProjectRow
	for rows.Next() {
		var i ListCrawlsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.Phase,
			&i.ConfigSnapshot,
			&i.UrlsDiscovered,
			&i.UrlsCrawled,
			&i.MaxDepthReached,
			&i.GooglePsiResults,
			&i.HasLlmsTxt,
			&i.SeoScore,
			&i.AeoScore,
			&i.PagespeedScore,
			&i.OverallScore,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCrawlCompleted = `-- name: MarkCrawlCompleted :exec
UPDATE crawls
SET status = 'completed',
    urls_discovered = $2,
    urls_crawled = $3,
    max_depth_reached = $4,
    completed_at = now()
WHERE id = $1
  AND status = 'running'
`

type MarkCrawlCompletedParams struct {
	ID              pgtype.UUID
	UrlsDiscovered  int32
	UrlsCrawled     int32
	MaxDepthReached int32
}

func (q *Queries) MarkCrawlCompleted(ctx context.Context, arg MarkCrawlCompletedParams) error {
	_, err := q.db.Exec(ctx, markCrawlCompleted,
		arg.ID,
		arg.UrlsDiscovered,
		arg.UrlsCrawled,
		arg.MaxDepthReached,
	)
	return err
}

const markCrawlFailed = `-- name: MarkCrawlFailed :exec
UPDATE crawls
SET status = 'failed',
    urls_discovered = $2,
    urls_crawled = $3,
    max_depth_reached = $4,
    completed_at = now()
WHERE id = $1
  AND status = 'running'
`

type MarkCrawlFailedParams struct {
	ID              pgtype.UUID
	UrlsDiscovered  int32
	UrlsCrawled     int32
	MaxDepthReached int32
}

func (q *Queries) MarkCrawlFailed(ctx context.Context, arg MarkCrawlFailedParams) error {
	_, err := q.db.Exec(ctx, markCrawlFailed,
		arg.ID,
		arg.UrlsDiscovered,
		arg.UrlsCrawled,
		arg.MaxDepthReached,
	)
	return err
}

const markCrawlRunning = `-- name: MarkCrawlRunning :exec
UPDATE crawls
SET status = 'running',
    started_at = now(),
    completed_at = NULL
WHERE id = $1
`

func (q *Queries) MarkCrawlRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markCrawlRunning, id)
	return err
}

const reclaimStaleRunningCrawls = `-- name: ReclaimStaleRunningCrawls :exec
UPDATE crawls
SET status = 'failed',
    completed_at = now()
WHERE status = 'running'
  AND started_at < $1
`

func (q *Queries) ReclaimStaleRunningCrawls(ctx context.Context, startedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, reclaimStaleRunningCrawls, startedAt)
	return err
}

const updateCrawlGooglePSIResults = `-- name: UpdateCrawlGooglePSIResults :exec
UPDATE crawls
SET google_psi_results = $2
WHERE id = $1
`

type UpdateCrawlGooglePSIResultsParams struct {
	ID               pgtype.UUID
	GooglePsiResults []byte
}

func (q *Queries) UpdateCrawlGooglePSIResults(ctx context.Context, arg UpdateCrawlGooglePSIResultsParams) error {
	_, err := q.db.Exec(ctx, updateCrawlGooglePSIResults, arg.ID, arg.GooglePsiResults)
	return err
}

const updateCrawlPhase = `-- name: UpdateCrawlPhase :exec
UPDATE crawls
SET phase = $2
WHERE id = $1
  AND status = 'running'
`

type UpdateCrawlPhaseParams struct {
	ID    pgtype.UUID
	Phase pgtype.Text
}

func (q *Queries) UpdateCrawlPhase(ctx context.Context, arg UpdateCrawlPhaseParams) error {
	_, err := q.db.Exec(ctx, updateCrawlPhase, arg.ID, arg.Phase)
	return err
}

const updateCrawlProgress = `-- name: UpdateCrawlProgress :exec
UPDATE crawls
SET urls_crawled = $2,
    urls_discovered = $3
WHERE id = $1
  AND status = 'running'
`

type UpdateCrawlProgressParams struct {
	ID             pgtype.UUID
	UrlsCrawled    int32
	UrlsDiscovered int32
}

func (q *Queries) UpdateCrawlProgress(ctx context.Context, arg UpdateCrawlProgressParams) error {
	_, err := q.db.Exec(ctx, updateCrawlProgress, arg.ID, arg.UrlsCrawled, arg.UrlsDiscovered)
	return err
}

const updateCrawlScores = `-- name: UpdateCrawlScores :exec
UPDATE crawls
SET seo_score = $2,
    aeo_score = $3,
    pagespeed_score = $4,
    overall_score = $5
WHERE id = $1
`

type UpdateCrawlScoresParams struct {
	ID             pgtype.UUID
	SeoScore       pgtype.Int4
	AeoScore       pgtype.Int4
	PagespeedScore pgtype.Int4
	OverallScore   pgtype.Int4
}

func (q *Queries) UpdateCrawlScores(ctx context.Context, arg UpdateCrawlScoresParams) error {
	_, err := q.db.Exec(ctx, updateCrawlScores,
		arg.ID,
		arg.SeoScore,
		arg.AeoScore,
		arg.PagespeedScore,
		arg.OverallScore,
	)
	return err
}
