// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawl_score_breakdowns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompareCrawlIssueURLsByTypeForCrawlByUser = `-- name: CountCompareCrawlIssueURLsByTypeForCrawlByUser :one
WITH baseline_urls AS (
    SELECT DISTINCT ON (ci.url)
        ci.url,
        ci.severity,
        CASE ci.severity
            WHEN 'critical' THEN 4
            WHEN 'high' THEN 3
            WHEN 'medium' THEN 2
            WHEN 'low' THEN 1
            ELSE 0
        END AS severity_rank,
        ci.message,
        ci.details
    FROM crawl_issues AS ci
    INNER JOIN crawls AS c ON c.id = ci.crawl_id
    INNER JOIN projects AS p ON p.id = c.project_id
    INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    WHERE ci.crawl_id = $1
      AND om.user_id = $3
      AND ci.pillar = $4
      AND ci.bucket = $5
      AND ci.issue_type = $6
    ORDER BY ci.url ASC, ci.created_at ASC
),
current_urls AS (
    SELECT DISTINCT ON (ci.url)
        ci.url,
        ci.severity,
        CASE ci.severity
            WHEN 'critical' THEN 4
            WHEN 'high' THEN 3
            WHEN 'medium' THEN 2
            WHEN 'low' THEN 1
            ELSE 0
        END AS severity_rank,
        ci.message,
        ci.details
    FROM crawl_issues AS ci
    INNER JOIN crawls AS c ON c.id = ci.crawl_id
    INNER JOIN projects AS p ON p.id = c.project_id
    INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    WHERE ci.crawl_id = $2
      AND om.user_id = $3
      AND ci.pillar = $4
      AND ci.bucket = $5
      AND ci.issue_type = $6
    ORDER BY ci.url ASC, ci.created_at ASC
),
diff_urls AS (
    SELECT
        CASE
            WHEN baseline_urls.url IS NULL THEN 'new'
            WHEN current_urls.url IS NULL THEN 'resolved'
            WHEN current_urls.severity_rank < baseline_urls.severity_rank THEN 'improved'
            WHEN current_urls.severity_rank > baseline_urls.severity_rank THEN 'regressed'
            WHEN baseline_urls.message <> current_urls.message
              OR baseline_urls.details <> current_urls.details THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM baseline_urls
    FULL OUTER JOIN current_urls ON current_urls.url = baseline_urls.url
),
ranked_urls AS (
    SELECT
        change_type,
        CASE
            WHEN change_type IN ('regressed', 'new') THEN 'regressed'
            WHEN change_type IN ('improved', 'resolved') THEN 'improved'
            ELSE change_type
        END AS contribution_type
    FROM diff_urls
)
SELECT COUNT(*)
FROM ranked_urls
WHERE $7 = '' OR change_type = $7 OR contribution_type = $7
`

type CountCompareCrawlIssueURLsByTypeForCrawlByUserParams struct {
	CrawlID   pgtype.UUID
	CrawlID_2 pgtype.UUID
	UserID    pgtype.UUID
	Pillar    string
	Bucket    string
	IssueType string
	Column7   interface{}
}

func (q *Queries) CountCompareCrawlIssueURLsByTypeForCrawlByUser(ctx context.Context, arg CountCompareCrawlIssueURLsByTypeForCrawlByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompareCrawlIssueURLsByTypeForCrawlByUser,
		arg.CrawlID,
		arg.CrawlID_2,
		arg.UserID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDistinctCrawlIssueURLsByTypeForCrawlByUser = `-- name: CountDistinctCrawlIssueURLsByTypeForCrawlByUser :one
SELECT COUNT(DISTINCT ci.url)
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
  AND ci.pillar = $3
  AND ci.bucket = $4
  AND ci.issue_type = $5
`

type CountDistinctCrawlIssueURLsByTypeForCrawlByUserParams struct {
	CrawlID   pgtype.UUID
	UserID    pgtype.UUID
	Pillar    string
	Bucket    string
	IssueType string
}

func (q *Queries) CountDistinctCrawlIssueURLsByTypeForCrawlByUser(ctx context.Context, arg CountDistinctCrawlIssueURLsByTypeForCrawlByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctCrawlIssueURLsByTypeForCrawlByUser,
		arg.CrawlID,
		arg.UserID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCrawlScoreBreakdownByCrawl = `-- name: GetCrawlScoreBreakdownByCrawl :one
SELECT
    csb.crawl_id,
    csb.scoring_version,
    csb.breakdown_json,
    csb.created_at,
    csb.updated_at
FROM crawl_score_breakdowns AS csb
WHERE csb.crawl_id = $1
LIMIT 1
`

func (q *Queries) GetCrawlScoreBreakdownByCrawl(ctx context.Context, crawlID pgtype.UUID) (CrawlScoreBreakdown, error) {
	row := q.db.QueryRow(ctx, getCrawlScoreBreakdownByCrawl, crawlID)
	var i CrawlScoreBreakdown
	err := row.Scan(
		&i.CrawlID,
		&i.ScoringVersion,
		&i.BreakdownJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCrawlScoreBreakdownByCrawlForUser = `-- name: GetCrawlScoreBreakdownByCrawlForUser :one
SELECT
    csb.crawl_id,
    csb.scoring_version,
    csb.breakdown_json,
    csb.created_at,
    csb.updated_at
FROM crawl_score_breakdowns AS csb
INNER JOIN crawls AS c ON c.id = csb.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE csb.crawl_id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlScoreBreakdownByCrawlForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetCrawlScoreBreakdownByCrawlForUser(ctx context.Context, arg GetCrawlScoreBreakdownByCrawlForUserParams) (CrawlScoreBreakdown, error) {
	row := q.db.QueryRow(ctx, getCrawlScoreBreakdownByCrawlForUser, arg.CrawlID, arg.UserID)
	var i CrawlScoreBreakdown
	err := row.Scan(
		&i.CrawlID,
		&i.ScoringVersion,
		&i.BreakdownJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompareCrawlIssueURLsByTypeForCrawlByUser = `-- name: ListCompareCrawlIssueURLsByTypeForCrawlByUser :many
WITH baseline_urls AS (
    SELECT DISTINCT ON (ci.url)
        ci.url,
        ci.crawl_page_id,
        ci.severity,
        CASE ci.severity
            WHEN 'critical' THEN 4
            WHEN 'high' THEN 3
            WHEN 'medium' THEN 2
            WHEN 'low' THEN 1
            ELSE 0
        END AS severity_rank,
        ci.message,
        ci.details
    FROM crawl_issues AS ci
    INNER JOIN crawls AS c ON c.id = ci.crawl_id
    INNER JOIN projects AS p ON p.id = c.project_id
    INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    WHERE ci.crawl_id = $1
      AND om.user_id = $3
      AND ci.pillar = $4
      AND ci.bucket = $5
      AND ci.issue_type = $6
    ORDER BY ci.url ASC, ci.created_at ASC
),
current_urls AS (
    SELECT DISTINCT ON (ci.url)
        ci.url,
        ci.crawl_page_id,
        ci.severity,
        CASE ci.severity
            WHEN 'critical' THEN 4
            WHEN 'high' THEN 3
            WHEN 'medium' THEN 2
            WHEN 'low' THEN 1
            ELSE 0
        END AS severity_rank,
        ci.message,
        ci.details
    FROM crawl_issues AS ci
    INNER JOIN crawls AS c ON c.id = ci.crawl_id
    INNER JOIN projects AS p ON p.id = c.project_id
    INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    WHERE ci.crawl_id = $2
      AND om.user_id = $3
      AND ci.pillar = $4
      AND ci.bucket = $5
      AND ci.issue_type = $6
    ORDER BY ci.url ASC, ci.created_at ASC
),
diff_urls AS (
    SELECT
        COALESCE(baseline_urls.url, current_urls.url) AS url,
        baseline_urls.crawl_page_id AS baseline_crawl_page_id,
        baseline_urls.severity AS baseline_severity,
        baseline_urls.message AS baseline_message,
        baseline_urls.details AS baseline_details,
        current_urls.crawl_page_id AS current_crawl_page_id,
        current_urls.severity AS current_severity,
        current_urls.message AS current_message,
        current_urls.details AS current_details,
        CASE
            WHEN baseline_urls.url IS NULL THEN 'new'
            WHEN current_urls.url IS NULL THEN 'resolved'
            WHEN current_urls.severity_rank < baseline_urls.severity_rank THEN 'improved'
            WHEN current_urls.severity_rank > baseline_urls.severity_rank THEN 'regressed'
            WHEN baseline_urls.message <> current_urls.message
              OR baseline_urls.details <> current_urls.details THEN 'changed'
            ELSE 'unchanged'
        END AS change_type
    FROM baseline_urls
    FULL OUTER JOIN current_urls ON current_urls.url = baseline_urls.url
),
ranked_urls AS (
    SELECT
        url, baseline_crawl_page_id, baseline_severity, baseline_message, baseline_details, current_crawl_page_id, current_severity, current_message, current_details, change_type,
        CASE
            WHEN change_type IN ('regressed', 'new') THEN 'regressed'
            WHEN change_type IN ('improved', 'resolved') THEN 'improved'
            ELSE change_type
        END AS contribution_type
    FROM diff_urls
)
SELECT
    url,
    baseline_crawl_page_id,
    baseline_severity,
    baseline_message,
    baseline_details,
    current_crawl_page_id,
    current_severity,
    current_message,
    current_details,
    change_type
FROM ranked_urls
WHERE $7 = '' OR change_type = $7 OR contribution_type = $7
ORDER BY url ASC
LIMIT $8
OFFSET $9
`

type ListCompareCrawlIssueURLsByTypeForCrawlByUserParams struct {
	CrawlID   pgtype.UUID
	CrawlID_2 pgtype.UUID
	UserID    pgtype.UUID
	Pillar    string
	Bucket    string
	IssueType string
	Column7   interface{}
	Limit     int32
	Offset    int32
}

type ListCompareCrawlIssueURLsByTypeForCrawlByUserRow struct {
	Url                 string
	BaselineCrawlPageID pgtype.UUID
	BaselineSeverity    pgtype.Text
	BaselineMessage     pgtype.Text
	BaselineDetails     pgtype.Text
	CurrentCrawlPageID  pgtype.UUID
	CurrentSeverity     pgtype.Text
	CurrentMessage      pgtype.Text
	CurrentDetails      pgtype.Text
	ChangeType          string
}

func (q *Queries) ListCompareCrawlIssueURLsByTypeForCrawlByUser(ctx context.Context, arg ListCompareCrawlIssueURLsByTypeForCrawlByUserParams) ([]ListCompareCrawlIssueURLsByTypeForCrawlByUserRow, error) {
	rows, err := q.db.Query(ctx, listCompareCrawlIssueURLsByTypeForCrawlByUser,
		arg.CrawlID,
		arg.CrawlID_2,
		arg.UserID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompareCrawlIssueURLsByTypeForCrawlByUserRow
	for rows.Next() {
		var i ListCompareCrawlIssueURLsByTypeForCrawlByUserRow
		if err := rows.Scan(
			&i.Url,
			&i.BaselineCrawlPageID,
			&i.BaselineSeverity,
			&i.BaselineMessage,
			&i.BaselineDetails,
			&i.CurrentCrawlPageID,
			&i.CurrentSeverity,
			&i.CurrentMessage,
			&i.CurrentDetails,
			&i.ChangeType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedProjectCrawlScoreBreakdownsForUser = `-- name: ListCompletedProjectCrawlScoreBreakdownsForUser :many
SELECT
    c.id AS crawl_id,
    c.created_at,
    c.completed_at,
    csb.breakdown_json
FROM crawl_score_breakdowns AS csb
INNER JOIN crawls AS c ON c.id = csb.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE c.project_id = $1
  AND om.user_id = $2
  AND c.status = 'completed'
ORDER BY c.created_at DESC
LIMIT $3
OFFSET $4
`

type ListCompletedProjectCrawlScoreBreakdownsForUserParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Limit     int32
	Offset    int32
}

type ListCompletedProjectCrawlScoreBreakdownsForUserRow struct {
	CrawlID       pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
	BreakdownJson []byte
}

func (q *Queries) ListCompletedProjectCrawlScoreBreakdownsForUser(ctx context.Context, arg ListCompletedProjectCrawlScoreBreakdownsForUserParams) ([]ListCompletedProjectCrawlScoreBreakdownsForUserRow, error) {
	rows, err := q.db.Query(ctx, listCompletedProjectCrawlScoreBreakdownsForUser,
		arg.ProjectID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompletedProjectCrawlScoreBreakdownsForUserRow
	for rows.Next() {
		var i ListCompletedProjectCrawlScoreBreakdownsForUserRow
		if err := rows.Scan(
			&i.CrawlID,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.BreakdownJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCrawlIssueURLsByTypeForCrawlByUser = `-- name: ListDistinctCrawlIssueURLsByTypeForCrawlByUser :many
SELECT DISTINCT ON (ci.url)
    ci.url,
    ci.crawl_page_id,
    ci.severity,
    ci.message,
    ci.details
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
  AND ci.pillar = $3
  AND ci.bucket = $4
  AND ci.issue_type = $5
ORDER BY
    ci.url ASC,
    CASE ci.severity
        WHEN 'high' THEN 3
        WHEN 'medium' THEN 2
        WHEN 'low' THEN 1
        ELSE 0
    END DESC,
    ci.created_at ASC
LIMIT $6
OFFSET $7
`

type ListDistinctCrawlIssueURLsByTypeForCrawlByUserParams struct {
	CrawlID   pgtype.UUID
	UserID    pgtype.UUID
	Pillar    string
	Bucket    string
	IssueType string
	Limit     int32
	Offset    int32
}

type ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow struct {
	Url         string
	CrawlPageID pgtype.UUID
	Severity    string
	Message     string
	Details     string
}

func (q *Queries) ListDistinctCrawlIssueURLsByTypeForCrawlByUser(ctx context.Context, arg ListDistinctCrawlIssueURLsByTypeForCrawlByUserParams) ([]ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow, error) {
	rows, err := q.db.Query(ctx, listDistinctCrawlIssueURLsByTypeForCrawlByUser,
		arg.CrawlID,
		arg.UserID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow
	for rows.Next() {
		var i ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow
		if err := rows.Scan(
			&i.Url,
			&i.CrawlPageID,
			&i.Severity,
			&i.Message,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCrawlScoreBreakdown = `-- name: UpsertCrawlScoreBreakdown :exec
INSERT INTO crawl_score_breakdowns (
    crawl_id,
    scoring_version,
    breakdown_json
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (crawl_id) DO UPDATE SET
    scoring_version = EXCLUDED.scoring_version,
    breakdown_json = EXCLUDED.breakdown_json,
    updated_at = now()
`

type UpsertCrawlScoreBreakdownParams struct {
	CrawlID        pgtype.UUID
	ScoringVersion string
	BreakdownJson  []byte
}

func (q *Queries) UpsertCrawlScoreBreakdown(ctx context.Context, arg UpsertCrawlScoreBreakdownParams) error {
	_, err := q.db.Exec(ctx, upsertCrawlScoreBreakdown, arg.CrawlID, arg.ScoringVersion, arg.BreakdownJson)
	return err
}
