// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawls.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCrawl = `-- name: CreateCrawl :one
INSERT INTO crawls (
    project_id,
    status,
    config_snapshot,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, project_id, status, config_snapshot, seo_score, aeo_score, pagespeed_score, overall_score, started_at, completed_at, created_at
`

type CreateCrawlParams struct {
	ProjectID      pgtype.UUID
	Status         string
	ConfigSnapshot []byte
	StartedAt      pgtype.Timestamptz
}

func (q *Queries) CreateCrawl(ctx context.Context, arg CreateCrawlParams) (Crawl, error) {
	row := q.db.QueryRow(ctx, createCrawl,
		arg.ProjectID,
		arg.Status,
		arg.ConfigSnapshot,
		arg.StartedAt,
	)
	var i Crawl
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.ConfigSnapshot,
		&i.SeoScore,
		&i.AeoScore,
		&i.PagespeedScore,
		&i.OverallScore,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlByIDForUser = `-- name: GetCrawlByIDForUser :one
SELECT
    c.id,
    c.project_id,
    c.status,
    c.config_snapshot,
    c.seo_score,
    c.aeo_score,
    c.pagespeed_score,
    c.overall_score,
    c.started_at,
    c.completed_at,
    c.created_at
FROM crawls AS c
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE c.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetCrawlByIDForUser(ctx context.Context, arg GetCrawlByIDForUserParams) (Crawl, error) {
	row := q.db.QueryRow(ctx, getCrawlByIDForUser, arg.ID, arg.UserID)
	var i Crawl
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.ConfigSnapshot,
		&i.SeoScore,
		&i.AeoScore,
		&i.PagespeedScore,
		&i.OverallScore,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCrawlsForProject = `-- name: ListCrawlsForProject :many
SELECT
    id,
    project_id,
    status,
    config_snapshot,
    seo_score,
    aeo_score,
    pagespeed_score,
    overall_score,
    started_at,
    completed_at,
    created_at
FROM crawls
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCrawlsForProject(ctx context.Context, projectID pgtype.UUID) ([]Crawl, error) {
	rows, err := q.db.Query(ctx, listCrawlsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crawl
	for rows.Next() {
		var i Crawl
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.ConfigSnapshot,
			&i.SeoScore,
			&i.AeoScore,
			&i.PagespeedScore,
			&i.OverallScore,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
