// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawls.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCrawl = `-- name: CreateCrawl :one
INSERT INTO crawls (
    project_id,
    status,
    config_snapshot,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, project_id, status, config_snapshot, urls_discovered, urls_crawled, max_depth_reached, google_psi_results, has_llms_txt, seo_score, aeo_score, pagespeed_score, overall_score, started_at, completed_at, created_at
`

type CreateCrawlParams struct {
	ProjectID      pgtype.UUID
	Status         string
	ConfigSnapshot []byte
	StartedAt      pgtype.Timestamptz
}

type CreateCrawlRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	ConfigSnapshot   []byte
	UrlsDiscovered   int32
	UrlsCrawled      int32
	MaxDepthReached  int32
	GooglePsiResults []byte
	HasLlmsTxt       pgtype.Bool
	SeoScore         pgtype.Int4
	AeoScore         pgtype.Int4
	PagespeedScore   pgtype.Int4
	OverallScore     pgtype.Int4
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) CreateCrawl(ctx context.Context, arg CreateCrawlParams) (CreateCrawlRow, error) {
	row := q.db.QueryRow(ctx, createCrawl,
		arg.ProjectID,
		arg.Status,
		arg.ConfigSnapshot,
		arg.StartedAt,
	)
	var i CreateCrawlRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.ConfigSnapshot,
		&i.UrlsDiscovered,
		&i.UrlsCrawled,
		&i.MaxDepthReached,
		&i.GooglePsiResults,
		&i.HasLlmsTxt,
		&i.SeoScore,
		&i.AeoScore,
		&i.PagespeedScore,
		&i.OverallScore,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlByIDForUser = `-- name: GetCrawlByIDForUser :one
SELECT
    c.id,
    c.project_id,
    c.status,
    c.config_snapshot,
    c.urls_discovered,
    c.urls_crawled,
    c.max_depth_reached,
    c.google_psi_results,
    c.has_llms_txt,
    c.seo_score,
    c.aeo_score,
    c.pagespeed_score,
    c.overall_score,
    c.started_at,
    c.completed_at,
    c.created_at
FROM crawls AS c
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE c.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetCrawlByIDForUserRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	ConfigSnapshot   []byte
	UrlsDiscovered   int32
	UrlsCrawled      int32
	MaxDepthReached  int32
	GooglePsiResults []byte
	HasLlmsTxt       pgtype.Bool
	SeoScore         pgtype.Int4
	AeoScore         pgtype.Int4
	PagespeedScore   pgtype.Int4
	OverallScore     pgtype.Int4
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) GetCrawlByIDForUser(ctx context.Context, arg GetCrawlByIDForUserParams) (GetCrawlByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getCrawlByIDForUser, arg.ID, arg.UserID)
	var i GetCrawlByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.ConfigSnapshot,
		&i.UrlsDiscovered,
		&i.UrlsCrawled,
		&i.MaxDepthReached,
		&i.GooglePsiResults,
		&i.HasLlmsTxt,
		&i.SeoScore,
		&i.AeoScore,
		&i.PagespeedScore,
		&i.OverallScore,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCrawlsForProject = `-- name: ListCrawlsForProject :many
SELECT
    id,
    project_id,
    status,
    config_snapshot,
    urls_discovered,
    urls_crawled,
    max_depth_reached,
    google_psi_results,
    has_llms_txt,
    seo_score,
    aeo_score,
    pagespeed_score,
    overall_score,
    started_at,
    completed_at,
    created_at
FROM crawls
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListCrawlsForProjectRow struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	ConfigSnapshot   []byte
	UrlsDiscovered   int32
	UrlsCrawled      int32
	MaxDepthReached  int32
	GooglePsiResults []byte
	HasLlmsTxt       pgtype.Bool
	SeoScore         pgtype.Int4
	AeoScore         pgtype.Int4
	PagespeedScore   pgtype.Int4
	OverallScore     pgtype.Int4
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) ListCrawlsForProject(ctx context.Context, projectID pgtype.UUID) ([]ListCrawlsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listCrawlsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlsForProjectRow
	for rows.Next() {
		var i ListCrawlsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.ConfigSnapshot,
			&i.UrlsDiscovered,
			&i.UrlsCrawled,
			&i.MaxDepthReached,
			&i.GooglePsiResults,
			&i.HasLlmsTxt,
			&i.SeoScore,
			&i.AeoScore,
			&i.PagespeedScore,
			&i.OverallScore,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
