// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawl_page_worker_config.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCrawlPageWorkerConfig = `-- name: GetCrawlPageWorkerConfig :one
SELECT id, worker_count, updated_by_user_id, updated_at
FROM crawl_page_worker_config
WHERE id = TRUE
`

func (q *Queries) GetCrawlPageWorkerConfig(ctx context.Context) (CrawlPageWorkerConfig, error) {
	row := q.db.QueryRow(ctx, getCrawlPageWorkerConfig)
	var i CrawlPageWorkerConfig
	err := row.Scan(
		&i.ID,
		&i.WorkerCount,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}

const resetCrawlPageWorkerConfig = `-- name: ResetCrawlPageWorkerConfig :exec
DELETE FROM crawl_page_worker_config WHERE id = TRUE
`

func (q *Queries) ResetCrawlPageWorkerConfig(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetCrawlPageWorkerConfig)
	return err
}

const upsertCrawlPageWorkerConfig = `-- name: UpsertCrawlPageWorkerConfig :one
INSERT INTO crawl_page_worker_config (
    id,
    worker_count,
    updated_by_user_id
) VALUES (
    TRUE,
    $1,
    $2
)
ON CONFLICT (id) DO UPDATE SET
    worker_count = EXCLUDED.worker_count,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = NOW()
RETURNING id, worker_count, updated_by_user_id, updated_at
`

type UpsertCrawlPageWorkerConfigParams struct {
	WorkerCount     int32
	UpdatedByUserID pgtype.UUID
}

func (q *Queries) UpsertCrawlPageWorkerConfig(ctx context.Context, arg UpsertCrawlPageWorkerConfigParams) (CrawlPageWorkerConfig, error) {
	row := q.db.QueryRow(ctx, upsertCrawlPageWorkerConfig, arg.WorkerCount, arg.UpdatedByUserID)
	var i CrawlPageWorkerConfig
	err := row.Scan(
		&i.ID,
		&i.WorkerCount,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}
