// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawl_pages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCrawlPage = `-- name: CreateCrawlPage :one
INSERT INTO crawl_pages (
    crawl_id,
    url,
    status_code,
    content_type,
    size_bytes,
    is_internal,
    depth,
    title,
    meta_description,
    h1,
    h1_count,
    h2_count,
    h3_count,
    word_count,
    author,
    canonical_url,
    lang,
    viewport,
    robots,
    image_count,
    images_without_alt_count,
    images_without_dimensions,
    external_links,
    internal_links,
    response_time_ms,
    javascript_rendered,
    h2_headings,
    h3_headings,
    heading_outline,
    og_tags,
    json_ld
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31
)
RETURNING id, crawl_id, url, status_code, content_type, size_bytes, is_internal, depth, title, meta_description, h1, h1_count, h2_count, h3_count, word_count, author, canonical_url, lang, viewport, robots, image_count, images_without_alt_count, images_without_dimensions, external_links, internal_links, response_time_ms, javascript_rendered, h2_headings, h3_headings, heading_outline, og_tags, json_ld, created_at
`

type CreateCrawlPageParams struct {
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
}

func (q *Queries) CreateCrawlPage(ctx context.Context, arg CreateCrawlPageParams) (CrawlPage, error) {
	row := q.db.QueryRow(ctx, createCrawlPage,
		arg.CrawlID,
		arg.Url,
		arg.StatusCode,
		arg.ContentType,
		arg.SizeBytes,
		arg.IsInternal,
		arg.Depth,
		arg.Title,
		arg.MetaDescription,
		arg.H1,
		arg.H1Count,
		arg.H2Count,
		arg.H3Count,
		arg.WordCount,
		arg.Author,
		arg.CanonicalUrl,
		arg.Lang,
		arg.Viewport,
		arg.Robots,
		arg.ImageCount,
		arg.ImagesWithoutAltCount,
		arg.ImagesWithoutDimensions,
		arg.ExternalLinks,
		arg.InternalLinks,
		arg.ResponseTimeMs,
		arg.JavascriptRendered,
		arg.H2Headings,
		arg.H3Headings,
		arg.HeadingOutline,
		arg.OgTags,
		arg.JsonLd,
	)
	var i CrawlPage
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.Url,
		&i.StatusCode,
		&i.ContentType,
		&i.SizeBytes,
		&i.IsInternal,
		&i.Depth,
		&i.Title,
		&i.MetaDescription,
		&i.H1,
		&i.H1Count,
		&i.H2Count,
		&i.H3Count,
		&i.WordCount,
		&i.Author,
		&i.CanonicalUrl,
		&i.Lang,
		&i.Viewport,
		&i.Robots,
		&i.ImageCount,
		&i.ImagesWithoutAltCount,
		&i.ImagesWithoutDimensions,
		&i.ExternalLinks,
		&i.InternalLinks,
		&i.ResponseTimeMs,
		&i.JavascriptRendered,
		&i.H2Headings,
		&i.H3Headings,
		&i.HeadingOutline,
		&i.OgTags,
		&i.JsonLd,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlPageByIDForUser = `-- name: GetCrawlPageByIDForUser :one
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.status_code,
    cp.content_type,
    cp.size_bytes,
    cp.is_internal,
    cp.depth,
    cp.title,
    cp.meta_description,
    cp.h1,
    cp.h1_count,
    cp.h2_count,
    cp.h3_count,
    cp.word_count,
    cp.author,
    cp.canonical_url,
    cp.lang,
    cp.viewport,
    cp.robots,
    cp.image_count,
    cp.images_without_alt_count,
    cp.images_without_dimensions,
    cp.external_links,
    cp.internal_links,
    cp.response_time_ms,
    cp.javascript_rendered,
    cp.h2_headings,
    cp.h3_headings,
    cp.heading_outline,
    cp.og_tags,
    cp.json_ld,
    cp.created_at
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlPageByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetCrawlPageByIDForUser(ctx context.Context, arg GetCrawlPageByIDForUserParams) (CrawlPage, error) {
	row := q.db.QueryRow(ctx, getCrawlPageByIDForUser, arg.ID, arg.UserID)
	var i CrawlPage
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.Url,
		&i.StatusCode,
		&i.ContentType,
		&i.SizeBytes,
		&i.IsInternal,
		&i.Depth,
		&i.Title,
		&i.MetaDescription,
		&i.H1,
		&i.H1Count,
		&i.H2Count,
		&i.H3Count,
		&i.WordCount,
		&i.Author,
		&i.CanonicalUrl,
		&i.Lang,
		&i.Viewport,
		&i.Robots,
		&i.ImageCount,
		&i.ImagesWithoutAltCount,
		&i.ImagesWithoutDimensions,
		&i.ExternalLinks,
		&i.InternalLinks,
		&i.ResponseTimeMs,
		&i.JavascriptRendered,
		&i.H2Headings,
		&i.H3Headings,
		&i.HeadingOutline,
		&i.OgTags,
		&i.JsonLd,
		&i.CreatedAt,
	)
	return i, err
}

const listCrawlPagesForCrawlByUser = `-- name: ListCrawlPagesForCrawlByUser :many
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.status_code,
    cp.content_type,
    cp.size_bytes,
    cp.is_internal,
    cp.depth,
    cp.title,
    cp.meta_description,
    cp.h1,
    cp.h1_count,
    cp.h2_count,
    cp.h3_count,
    cp.word_count,
    cp.author,
    cp.canonical_url,
    cp.lang,
    cp.viewport,
    cp.robots,
    cp.image_count,
    cp.images_without_alt_count,
    cp.images_without_dimensions,
    cp.external_links,
    cp.internal_links,
    cp.response_time_ms,
    cp.javascript_rendered,
    cp.h2_headings,
    cp.h3_headings,
    cp.heading_outline,
    cp.og_tags,
    cp.json_ld,
    cp.created_at
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND om.user_id = $2
ORDER BY cp.created_at ASC
`

type ListCrawlPagesForCrawlByUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) ListCrawlPagesForCrawlByUser(ctx context.Context, arg ListCrawlPagesForCrawlByUserParams) ([]CrawlPage, error) {
	rows, err := q.db.Query(ctx, listCrawlPagesForCrawlByUser, arg.CrawlID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawlPage
	for rows.Next() {
		var i CrawlPage
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.Url,
			&i.StatusCode,
			&i.ContentType,
			&i.SizeBytes,
			&i.IsInternal,
			&i.Depth,
			&i.Title,
			&i.MetaDescription,
			&i.H1,
			&i.H1Count,
			&i.H2Count,
			&i.H3Count,
			&i.WordCount,
			&i.Author,
			&i.CanonicalUrl,
			&i.Lang,
			&i.Viewport,
			&i.Robots,
			&i.ImageCount,
			&i.ImagesWithoutAltCount,
			&i.ImagesWithoutDimensions,
			&i.ExternalLinks,
			&i.InternalLinks,
			&i.ResponseTimeMs,
			&i.JavascriptRendered,
			&i.H2Headings,
			&i.H3Headings,
			&i.HeadingOutline,
			&i.OgTags,
			&i.JsonLd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
