// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawl_pages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateCrawlPageContentFingerprints = `-- name: BulkUpdateCrawlPageContentFingerprints :exec
UPDATE crawl_pages AS cp
SET content_sha256 = NULLIF(data.content_sha256, '')
FROM (
    SELECT unnest($1::uuid[]) AS id, unnest($2::text[]) AS content_sha256
) AS data
WHERE cp.id = data.id
`

type BulkUpdateCrawlPageContentFingerprintsParams struct {
	Column1 []pgtype.UUID
	Column2 []string
}

func (q *Queries) BulkUpdateCrawlPageContentFingerprints(ctx context.Context, arg BulkUpdateCrawlPageContentFingerprintsParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateCrawlPageContentFingerprints, arg.Column1, arg.Column2)
	return err
}

const bulkUpdateCrawlPageHealthScores = `-- name: BulkUpdateCrawlPageHealthScores :exec
UPDATE crawl_pages AS cp
SET health_score = data.health_score
FROM (
    SELECT unnest($1::uuid[]) AS id, unnest($2::smallint[]) AS health_score
) AS data
WHERE cp.id = data.id
`

type BulkUpdateCrawlPageHealthScoresParams struct {
	PageIds      []pgtype.UUID
	HealthScores []int16
}

func (q *Queries) BulkUpdateCrawlPageHealthScores(ctx context.Context, arg BulkUpdateCrawlPageHealthScoresParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateCrawlPageHealthScores, arg.PageIds, arg.HealthScores)
	return err
}

const copyCrawlPageFromBaseline = `-- name: CopyCrawlPageFromBaseline :execrows
INSERT INTO crawl_pages (
    crawl_id,
    url,
    status_code,
    content_type,
    size_bytes,
    is_internal,
    depth,
    title,
    meta_description,
    h1,
    h1_count,
    h2_count,
    h3_count,
    word_count,
    visible_text,
    content_sha256,
    author,
    canonical_url,
    lang,
    viewport,
    robots,
    image_count,
    images_without_alt_count,
    images_without_dimensions,
    external_links,
    internal_links,
    response_time_ms,
    javascript_rendered,
    h2_headings,
    h3_headings,
    heading_outline,
    og_tags,
    json_ld,
    content_blocks,
    etag,
    last_modified,
    soft_404,
    fetch_error
)
SELECT
    $1,
    url,
    status_code,
    content_type,
    size_bytes,
    is_internal,
    $2,
    title,
    meta_description,
    h1,
    h1_count,
    h2_count,
    h3_count,
    word_count,
    visible_text,
    content_sha256,
    author,
    canonical_url,
    lang,
    viewport,
    robots,
    image_count,
    images_without_alt_count,
    images_without_dimensions,
    external_links,
    internal_links,
    response_time_ms,
    javascript_rendered,
    h2_headings,
    h3_headings,
    heading_outline,
    og_tags,
    json_ld,
    content_blocks,
    COALESCE($3::text, crawl_pages.etag),
    last_modified,
    -- A 304 means the body is unchanged, so a soft 404 stays a soft 404. The
    -- fetch itself succeeded, so no fetch error is carried forward.
    soft_404,
    NULL
FROM crawl_pages
WHERE crawl_pages.crawl_id = $4
  AND crawl_pages.url = $5
ON CONFLICT (crawl_id, url) DO NOTHING
`

type CopyCrawlPageFromBaselineParams struct {
	CrawlID         pgtype.UUID
	Depth           pgtype.Int4
	FreshEtag       pgtype.Text
	BaselineCrawlID pgtype.UUID
	Url             string
}

func (q *Queries) CopyCrawlPageFromBaseline(ctx context.Context, arg CopyCrawlPageFromBaselineParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyCrawlPageFromBaseline,
		arg.CrawlID,
		arg.Depth,
		arg.FreshEtag,
		arg.BaselineCrawlID,
		arg.Url,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCrawlPagesFilteredForUser = `-- name: CountCrawlPagesFilteredForUser :one
SELECT COUNT(*)
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND om.user_id = $2
  AND ($3 = '' OR cp.url ILIKE '%' || $3 || '%')
`

type CountCrawlPagesFilteredForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Column3 interface{}
}

func (q *Queries) CountCrawlPagesFilteredForUser(ctx context.Context, arg CountCrawlPagesFilteredForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlPagesFilteredForUser, arg.CrawlID, arg.UserID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCrawlPagesForCrawlByUser = `-- name: CountCrawlPagesForCrawlByUser :one
SELECT COUNT(*)
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND om.user_id = $2
`

type CountCrawlPagesForCrawlByUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) CountCrawlPagesForCrawlByUser(ctx context.Context, arg CountCrawlPagesForCrawlByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlPagesForCrawlByUser, arg.CrawlID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCrawlPagesSearchForUser = `-- name: CountCrawlPagesSearchForUser :one
SELECT COUNT(*)::bigint
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND om.user_id = $2
  AND (
      $3::text = ''
      OR strpos(lower(cp.url), lower($3::text)) > 0
      OR strpos(lower(COALESCE(cp.title, '')), lower($3::text)) > 0
  )
`

type CountCrawlPagesSearchForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Query   string
}

func (q *Queries) CountCrawlPagesSearchForUser(ctx context.Context, arg CountCrawlPagesSearchForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlPagesSearchForUser, arg.CrawlID, arg.UserID, arg.Query)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCrawlPage = `-- name: CreateCrawlPage :one
INSERT INTO crawl_pages (
    crawl_id,
    url,
    status_code,
    content_type,
    size_bytes,
    is_internal,
    depth,
    title,
    meta_description,
    h1,
    h1_count,
    h2_count,
    h3_count,
    word_count,
    visible_text,
    content_sha256,
    author,
    canonical_url,
    lang,
    viewport,
    robots,
    image_count,
    images_without_alt_count,
    images_without_dimensions,
    external_links,
    internal_links,
    response_time_ms,
    javascript_rendered,
    h2_headings,
    h3_headings,
    heading_outline,
    og_tags,
    json_ld,
    content_blocks,
    etag,
    last_modified,
    soft_404,
    fetch_error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33,
    $34,
    $35,
    $36,
    $37,
    $38
)
RETURNING id, crawl_id, url, status_code, content_type, size_bytes, is_internal, depth, title, meta_description, h1, h1_count, h2_count, h3_count, word_count, visible_text, content_sha256, author, canonical_url, lang, viewport, robots, image_count, images_without_alt_count, images_without_dimensions, external_links, internal_links, response_time_ms, javascript_rendered, h2_headings, h3_headings, heading_outline, og_tags, json_ld, content_blocks, etag, last_modified, soft_404, fetch_error, created_at
`

type CreateCrawlPageParams struct {
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	VisibleText             pgtype.Text
	ContentSha256           pgtype.Text
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	ContentBlocks           []byte
	Etag                    pgtype.Text
	LastModified            pgtype.Text
	Soft404                 bool
	FetchError              pgtype.Text
}

type CreateCrawlPageRow struct {
	ID                      pgtype.UUID
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	VisibleText             pgtype.Text
	ContentSha256           pgtype.Text
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	ContentBlocks           []byte
	Etag                    pgtype.Text
	LastModified            pgtype.Text
	Soft404                 bool
	FetchError              pgtype.Text
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) CreateCrawlPage(ctx context.Context, arg CreateCrawlPageParams) (CreateCrawlPageRow, error) {
	row := q.db.QueryRow(ctx, createCrawlPage,
		arg.CrawlID,
		arg.Url,
		arg.StatusCode,
		arg.ContentType,
		arg.SizeBytes,
		arg.IsInternal,
		arg.Depth,
		arg.Title,
		arg.MetaDescription,
		arg.H1,
		arg.H1Count,
		arg.H2Count,
		arg.H3Count,
		arg.WordCount,
		arg.VisibleText,
		arg.ContentSha256,
		arg.Author,
		arg.CanonicalUrl,
		arg.Lang,
		arg.Viewport,
		arg.Robots,
		arg.ImageCount,
		arg.ImagesWithoutAltCount,
		arg.ImagesWithoutDimensions,
		arg.ExternalLinks,
		arg.InternalLinks,
		arg.ResponseTimeMs,
		arg.JavascriptRendered,
		arg.H2Headings,
		arg.H3Headings,
		arg.HeadingOutline,
		arg.OgTags,
		arg.JsonLd,
		arg.ContentBlocks,
		arg.Etag,
		arg.LastModified,
		arg.Soft404,
		arg.FetchError,
	)
	var i CreateCrawlPageRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.Url,
		&i.StatusCode,
		&i.ContentType,
		&i.SizeBytes,
		&i.IsInternal,
		&i.Depth,
		&i.Title,
		&i.MetaDescription,
		&i.H1,
		&i.H1Count,
		&i.H2Count,
		&i.H3Count,
		&i.WordCount,
		&i.VisibleText,
		&i.ContentSha256,
		&i.Author,
		&i.CanonicalUrl,
		&i.Lang,
		&i.Viewport,
		&i.Robots,
		&i.ImageCount,
		&i.ImagesWithoutAltCount,
		&i.ImagesWithoutDimensions,
		&i.ExternalLinks,
		&i.InternalLinks,
		&i.ResponseTimeMs,
		&i.JavascriptRendered,
		&i.H2Headings,
		&i.H3Headings,
		&i.HeadingOutline,
		&i.OgTags,
		&i.JsonLd,
		&i.ContentBlocks,
		&i.Etag,
		&i.LastModified,
		&i.Soft404,
		&i.FetchError,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlPageByIDForUser = `-- name: GetCrawlPageByIDForUser :one
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.status_code,
    cp.content_type,
    cp.size_bytes,
    cp.is_internal,
    cp.depth,
    cp.title,
    cp.meta_description,
    cp.h1,
    cp.h1_count,
    cp.h2_count,
    cp.h3_count,
    cp.word_count,
    cp.visible_text,
    cp.content_sha256,
    cp.author,
    cp.canonical_url,
    cp.lang,
    cp.viewport,
    cp.robots,
    cp.image_count,
    cp.images_without_alt_count,
    cp.images_without_dimensions,
    cp.external_links,
    cp.internal_links,
    cp.response_time_ms,
    cp.javascript_rendered,
    cp.h2_headings,
    cp.h3_headings,
    cp.heading_outline,
    cp.og_tags,
    cp.json_ld,
    cp.content_blocks,
    cp.created_at
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlPageByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetCrawlPageByIDForUserRow struct {
	ID                      pgtype.UUID
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	VisibleText             pgtype.Text
	ContentSha256           pgtype.Text
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	ContentBlocks           []byte
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) GetCrawlPageByIDForUser(ctx context.Context, arg GetCrawlPageByIDForUserParams) (GetCrawlPageByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getCrawlPageByIDForUser, arg.ID, arg.UserID)
	var i GetCrawlPageByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.Url,
		&i.StatusCode,
		&i.ContentType,
		&i.SizeBytes,
		&i.IsInternal,
		&i.Depth,
		&i.Title,
		&i.MetaDescription,
		&i.H1,
		&i.H1Count,
		&i.H2Count,
		&i.H3Count,
		&i.WordCount,
		&i.VisibleText,
		&i.ContentSha256,
		&i.Author,
		&i.CanonicalUrl,
		&i.Lang,
		&i.Viewport,
		&i.Robots,
		&i.ImageCount,
		&i.ImagesWithoutAltCount,
		&i.ImagesWithoutDimensions,
		&i.ExternalLinks,
		&i.InternalLinks,
		&i.ResponseTimeMs,
		&i.JavascriptRendered,
		&i.H2Headings,
		&i.H3Headings,
		&i.HeadingOutline,
		&i.OgTags,
		&i.JsonLd,
		&i.ContentBlocks,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlPageByURLForUser = `-- name: GetCrawlPageByURLForUser :one
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.status_code,
    cp.content_type,
    cp.size_bytes,
    cp.is_internal,
    cp.depth,
    cp.title,
    cp.meta_description,
    cp.h1,
    cp.h1_count,
    cp.h2_count,
    cp.h3_count,
    cp.word_count,
    cp.visible_text,
    cp.content_sha256,
    cp.author,
    cp.canonical_url,
    cp.lang,
    cp.viewport,
    cp.robots,
    cp.image_count,
    cp.images_without_alt_count,
    cp.images_without_dimensions,
    cp.external_links,
    cp.internal_links,
    cp.response_time_ms,
    cp.javascript_rendered,
    cp.h2_headings,
    cp.h3_headings,
    cp.heading_outline,
    cp.og_tags,
    cp.json_ld,
    cp.content_blocks,
    cp.created_at
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND cp.url = $2
  AND om.user_id = $3
LIMIT 1
`

type GetCrawlPageByURLForUserParams struct {
	CrawlID pgtype.UUID
	Url     string
	UserID  pgtype.UUID
}

type GetCrawlPageByURLForUserRow struct {
	ID                      pgtype.UUID
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	VisibleText             pgtype.Text
	ContentSha256           pgtype.Text
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	ContentBlocks           []byte
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) GetCrawlPageByURLForUser(ctx context.Context, arg GetCrawlPageByURLForUserParams) (GetCrawlPageByURLForUserRow, error) {
	row := q.db.QueryRow(ctx, getCrawlPageByURLForUser, arg.CrawlID, arg.Url, arg.UserID)
	var i GetCrawlPageByURLForUserRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.Url,
		&i.StatusCode,
		&i.ContentType,
		&i.SizeBytes,
		&i.IsInternal,
		&i.Depth,
		&i.Title,
		&i.MetaDescription,
		&i.H1,
		&i.H1Count,
		&i.H2Count,
		&i.H3Count,
		&i.WordCount,
		&i.VisibleText,
		&i.ContentSha256,
		&i.Author,
		&i.CanonicalUrl,
		&i.Lang,
		&i.Viewport,
		&i.Robots,
		&i.ImageCount,
		&i.ImagesWithoutAltCount,
		&i.ImagesWithoutDimensions,
		&i.ExternalLinks,
		&i.InternalLinks,
		&i.ResponseTimeMs,
		&i.JavascriptRendered,
		&i.H2Headings,
		&i.H3Headings,
		&i.HeadingOutline,
		&i.OgTags,
		&i.JsonLd,
		&i.ContentBlocks,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlPageContentByURLForUser = `-- name: GetCrawlPageContentByURLForUser :one
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.title,
    cp.meta_description,
    cp.h1,
    cp.word_count,
    cp.status_code,
    cp.content_type,
    cp.fetch_error,
    (CASE WHEN $1::boolean THEN cp.content_blocks ELSE NULL END)::jsonb AS content_blocks,
    (CASE
        WHEN $1::boolean THEN
            cp.content_blocks IS NOT NULL
            AND jsonb_typeof(cp.content_blocks) = 'array'
            AND jsonb_array_length(cp.content_blocks) > 0
        ELSE cp.content_blocks IS NOT NULL
    END)::boolean AS content_available,
    cp.created_at
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $2
  AND cp.url = $3
  AND om.user_id = $4
LIMIT 1
`

type GetCrawlPageContentByURLForUserParams struct {
	IncludeContent bool
	CrawlID        pgtype.UUID
	Url            string
	UserID         pgtype.UUID
}

type GetCrawlPageContentByURLForUserRow struct {
	ID               pgtype.UUID
	CrawlID          pgtype.UUID
	Url              string
	Title            pgtype.Text
	MetaDescription  pgtype.Text
	H1               pgtype.Text
	WordCount        pgtype.Int4
	StatusCode       pgtype.Int4
	ContentType      pgtype.Text
	FetchError       pgtype.Text
	ContentBlocks    []byte
	ContentAvailable bool
	CreatedAt        pgtype.Timestamptz
}

// content_blocks gated by include_content; metadata mode avoids large blob fetch, content_available reports presence.
func (q *Queries) GetCrawlPageContentByURLForUser(ctx context.Context, arg GetCrawlPageContentByURLForUserParams) (GetCrawlPageContentByURLForUserRow, error) {
	row := q.db.QueryRow(ctx, getCrawlPageContentByURLForUser,
		arg.IncludeContent,
		arg.CrawlID,
		arg.Url,
		arg.UserID,
	)
	var i GetCrawlPageContentByURLForUserRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.Url,
		&i.Title,
		&i.MetaDescription,
		&i.H1,
		&i.WordCount,
		&i.StatusCode,
		&i.ContentType,
		&i.FetchError,
		&i.ContentBlocks,
		&i.ContentAvailable,
		&i.CreatedAt,
	)
	return i, err
}

const getCrawlPageHealthForUser = `-- name: GetCrawlPageHealthForUser :one
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.health_score
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND cp.id = $2
  AND om.user_id = $3
  AND cp.health_score IS NOT NULL
LIMIT 1
`

type GetCrawlPageHealthForUserParams struct {
	CrawlID pgtype.UUID
	PageID  pgtype.UUID
	UserID  pgtype.UUID
}

type GetCrawlPageHealthForUserRow struct {
	ID          pgtype.UUID
	CrawlID     pgtype.UUID
	Url         string
	HealthScore pgtype.Int2
}

func (q *Queries) GetCrawlPageHealthForUser(ctx context.Context, arg GetCrawlPageHealthForUserParams) (GetCrawlPageHealthForUserRow, error) {
	row := q.db.QueryRow(ctx, getCrawlPageHealthForUser, arg.CrawlID, arg.PageID, arg.UserID)
	var i GetCrawlPageHealthForUserRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.Url,
		&i.HealthScore,
	)
	return i, err
}

const getCrawlPageIssueHistogramForUser = `-- name: GetCrawlPageIssueHistogramForUser :many
WITH scoreable_pages AS (
    SELECT cp.id
    FROM crawl_pages AS cp
    INNER JOIN crawls AS c ON c.id = cp.crawl_id
    INNER JOIN projects AS p ON p.id = c.project_id
    INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    WHERE cp.crawl_id = $1
      AND om.user_id = $2
      AND (cp.content_type IS NULL OR cp.content_type = '' OR cp.content_type ILIKE '%text/html%')
),
page_issue_counts AS (
    SELECT sp.id, COUNT(ci.id) AS issue_count
    FROM scoreable_pages AS sp
    LEFT JOIN crawl_issues AS ci ON ci.crawl_page_id = sp.id
    GROUP BY sp.id
)
SELECT
    LEAST(issue_count, 20)::int AS issue_count,
    COUNT(*)::bigint AS page_count
FROM page_issue_counts
GROUP BY 1
ORDER BY 1
`

type GetCrawlPageIssueHistogramForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

type GetCrawlPageIssueHistogramForUserRow struct {
	IssueCount int32
	PageCount  int64
}

// Distribution of scoreable pages by how many issues each carries, capped at 20+.
// Mirrors the scoreable-content-type filter used by crawl scoring so the totals
// agree with score_breakdown.total_scored_pages.
func (q *Queries) GetCrawlPageIssueHistogramForUser(ctx context.Context, arg GetCrawlPageIssueHistogramForUserParams) ([]GetCrawlPageIssueHistogramForUserRow, error) {
	rows, err := q.db.Query(ctx, getCrawlPageIssueHistogramForUser, arg.CrawlID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCrawlPageIssueHistogramForUserRow
	for rows.Next() {
		var i GetCrawlPageIssueHistogramForUserRow
		if err := rows.Scan(&i.IssueCount, &i.PageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCompletedCrawlIDForProject = `-- name: GetLatestCompletedCrawlIDForProject :one
SELECT id
FROM crawls
WHERE project_id = $1
  AND status = 'completed'
  AND id <> $2
ORDER BY completed_at DESC NULLS LAST
LIMIT 1
`

type GetLatestCompletedCrawlIDForProjectParams struct {
	ProjectID      pgtype.UUID
	ExcludeCrawlID pgtype.UUID
}

func (q *Queries) GetLatestCompletedCrawlIDForProject(ctx context.Context, arg GetLatestCompletedCrawlIDForProjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedCrawlIDForProject, arg.ProjectID, arg.ExcludeCrawlID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listCrawlPageSignalsForCrawl = `-- name: ListCrawlPageSignalsForCrawl :many
SELECT
    url,
    status_code,
    content_type,
    word_count,
    response_time_ms,
    size_bytes,
    soft_404,
    fetch_error
FROM crawl_pages
WHERE crawl_id = $1
ORDER BY created_at ASC
`

type ListCrawlPageSignalsForCrawlRow struct {
	Url            string
	StatusCode     pgtype.Int4
	ContentType    pgtype.Text
	WordCount      pgtype.Int4
	ResponseTimeMs pgtype.Int4
	SizeBytes      pgtype.Int4
	Soft404        bool
	FetchError     pgtype.Text
}

func (q *Queries) ListCrawlPageSignalsForCrawl(ctx context.Context, crawlID pgtype.UUID) ([]ListCrawlPageSignalsForCrawlRow, error) {
	rows, err := q.db.Query(ctx, listCrawlPageSignalsForCrawl, crawlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlPageSignalsForCrawlRow
	for rows.Next() {
		var i ListCrawlPageSignalsForCrawlRow
		if err := rows.Scan(
			&i.Url,
			&i.StatusCode,
			&i.ContentType,
			&i.WordCount,
			&i.ResponseTimeMs,
			&i.SizeBytes,
			&i.Soft404,
			&i.FetchError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlPagesFilteredForUser = `-- name: ListCrawlPagesFilteredForUser :many
SELECT
    cp.url,
    cp.title,
    cp.word_count
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND om.user_id = $2
  AND ($3 = '' OR cp.url ILIKE '%' || $3 || '%')
ORDER BY cp.url ASC
LIMIT $4
`

type ListCrawlPagesFilteredForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Column3 interface{}
	Limit   int32
}

type ListCrawlPagesFilteredForUserRow struct {
	Url       string
	Title     pgtype.Text
	WordCount pgtype.Int4
}

func (q *Queries) ListCrawlPagesFilteredForUser(ctx context.Context, arg ListCrawlPagesFilteredForUserParams) ([]ListCrawlPagesFilteredForUserRow, error) {
	rows, err := q.db.Query(ctx, listCrawlPagesFilteredForUser,
		arg.CrawlID,
		arg.UserID,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlPagesFilteredForUserRow
	for rows.Next() {
		var i ListCrawlPagesFilteredForUserRow
		if err := rows.Scan(&i.Url, &i.Title, &i.WordCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlPagesForCrawl = `-- name: ListCrawlPagesForCrawl :many
SELECT
    id,
    crawl_id,
    url,
    status_code,
    content_type,
    size_bytes,
    is_internal,
    depth,
    title,
    meta_description,
    h1,
    h1_count,
    h2_count,
    h3_count,
    word_count,
    visible_text,
    content_sha256,
    author,
    canonical_url,
    lang,
    viewport,
    robots,
    image_count,
    images_without_alt_count,
    images_without_dimensions,
    external_links,
    internal_links,
    response_time_ms,
    javascript_rendered,
    soft_404,
    fetch_error,
    h2_headings,
    h3_headings,
    heading_outline,
    og_tags,
    json_ld,
    content_blocks,
    created_at
FROM crawl_pages
WHERE crawl_id = $1
ORDER BY created_at ASC
`

type ListCrawlPagesForCrawlRow struct {
	ID                      pgtype.UUID
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	VisibleText             pgtype.Text
	ContentSha256           pgtype.Text
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	Soft404                 bool
	FetchError              pgtype.Text
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	ContentBlocks           []byte
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) ListCrawlPagesForCrawl(ctx context.Context, crawlID pgtype.UUID) ([]ListCrawlPagesForCrawlRow, error) {
	rows, err := q.db.Query(ctx, listCrawlPagesForCrawl, crawlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlPagesForCrawlRow
	for rows.Next() {
		var i ListCrawlPagesForCrawlRow
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.Url,
			&i.StatusCode,
			&i.ContentType,
			&i.SizeBytes,
			&i.IsInternal,
			&i.Depth,
			&i.Title,
			&i.MetaDescription,
			&i.H1,
			&i.H1Count,
			&i.H2Count,
			&i.H3Count,
			&i.WordCount,
			&i.VisibleText,
			&i.ContentSha256,
			&i.Author,
			&i.CanonicalUrl,
			&i.Lang,
			&i.Viewport,
			&i.Robots,
			&i.ImageCount,
			&i.ImagesWithoutAltCount,
			&i.ImagesWithoutDimensions,
			&i.ExternalLinks,
			&i.InternalLinks,
			&i.ResponseTimeMs,
			&i.JavascriptRendered,
			&i.Soft404,
			&i.FetchError,
			&i.H2Headings,
			&i.H3Headings,
			&i.HeadingOutline,
			&i.OgTags,
			&i.JsonLd,
			&i.ContentBlocks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlPagesForCrawlByUser = `-- name: ListCrawlPagesForCrawlByUser :many
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.status_code,
    cp.content_type,
    cp.size_bytes,
    cp.is_internal,
    cp.depth,
    cp.title,
    cp.meta_description,
    cp.h1,
    cp.h1_count,
    cp.h2_count,
    cp.h3_count,
    cp.word_count,
    cp.visible_text,
    cp.content_sha256,
    cp.author,
    cp.canonical_url,
    cp.lang,
    cp.viewport,
    cp.robots,
    cp.image_count,
    cp.images_without_alt_count,
    cp.images_without_dimensions,
    cp.external_links,
    cp.internal_links,
    cp.response_time_ms,
    cp.javascript_rendered,
    cp.soft_404,
    cp.fetch_error,
    cp.h2_headings,
    cp.h3_headings,
    cp.heading_outline,
    cp.og_tags,
    cp.json_ld,
    cp.content_blocks,
    cp.created_at
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND om.user_id = $2
ORDER BY cp.created_at ASC
LIMIT $3
OFFSET $4
`

type ListCrawlPagesForCrawlByUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListCrawlPagesForCrawlByUserRow struct {
	ID                      pgtype.UUID
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	VisibleText             pgtype.Text
	ContentSha256           pgtype.Text
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	Soft404                 bool
	FetchError              pgtype.Text
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	ContentBlocks           []byte
	CreatedAt               pgtype.Timestamptz
}

func (q *Queries) ListCrawlPagesForCrawlByUser(ctx context.Context, arg ListCrawlPagesForCrawlByUserParams) ([]ListCrawlPagesForCrawlByUserRow, error) {
	rows, err := q.db.Query(ctx, listCrawlPagesForCrawlByUser,
		arg.CrawlID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlPagesForCrawlByUserRow
	for rows.Next() {
		var i ListCrawlPagesForCrawlByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.Url,
			&i.StatusCode,
			&i.ContentType,
			&i.SizeBytes,
			&i.IsInternal,
			&i.Depth,
			&i.Title,
			&i.MetaDescription,
			&i.H1,
			&i.H1Count,
			&i.H2Count,
			&i.H3Count,
			&i.WordCount,
			&i.VisibleText,
			&i.ContentSha256,
			&i.Author,
			&i.CanonicalUrl,
			&i.Lang,
			&i.Viewport,
			&i.Robots,
			&i.ImageCount,
			&i.ImagesWithoutAltCount,
			&i.ImagesWithoutDimensions,
			&i.ExternalLinks,
			&i.InternalLinks,
			&i.ResponseTimeMs,
			&i.JavascriptRendered,
			&i.Soft404,
			&i.FetchError,
			&i.H2Headings,
			&i.H3Headings,
			&i.HeadingOutline,
			&i.OgTags,
			&i.JsonLd,
			&i.ContentBlocks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageValidatorsForCrawl = `-- name: ListPageValidatorsForCrawl :many
SELECT url, etag, last_modified
FROM crawl_pages
WHERE crawl_id = $1
  AND status_code BETWEEN 200 AND 299
  AND (etag IS NOT NULL OR last_modified IS NOT NULL)
`

type ListPageValidatorsForCrawlRow struct {
	Url          string
	Etag         pgtype.Text
	LastModified pgtype.Text
}

func (q *Queries) ListPageValidatorsForCrawl(ctx context.Context, crawlID pgtype.UUID) ([]ListPageValidatorsForCrawlRow, error) {
	rows, err := q.db.Query(ctx, listPageValidatorsForCrawl, crawlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPageValidatorsForCrawlRow
	for rows.Next() {
		var i ListPageValidatorsForCrawlRow
		if err := rows.Scan(&i.Url, &i.Etag, &i.LastModified); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCrawlPagesForUser = `-- name: SearchCrawlPagesForUser :many
SELECT
    cp.id,
    cp.crawl_id,
    cp.url,
    cp.title
FROM crawl_pages AS cp
INNER JOIN crawls AS c ON c.id = cp.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE cp.crawl_id = $1
  AND om.user_id = $2
  AND (
      $3::text = ''
      OR strpos(lower(cp.url), lower($3::text)) > 0
      OR strpos(lower(COALESCE(cp.title, '')), lower($3::text)) > 0
  )
ORDER BY
    CASE
        WHEN $3::text = '' THEN 4
        WHEN lower(cp.url) = lower($3::text) THEN 0
        WHEN strpos(lower(cp.url), lower($3::text)) = 1 THEN 1
        WHEN strpos(lower(cp.url), lower($3::text)) > 0 THEN 2
        WHEN strpos(lower(COALESCE(cp.title, '')), lower($3::text)) > 0 THEN 3
        ELSE 4
    END,
    cp.url ASC
LIMIT $5
OFFSET $4
`

type SearchCrawlPagesForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Query   string
	Offset  int32
	Limit   int32
}

type SearchCrawlPagesForUserRow struct {
	ID      pgtype.UUID
	CrawlID pgtype.UUID
	Url     string
	Title   pgtype.Text
}

func (q *Queries) SearchCrawlPagesForUser(ctx context.Context, arg SearchCrawlPagesForUserParams) ([]SearchCrawlPagesForUserRow, error) {
	rows, err := q.db.Query(ctx, searchCrawlPagesForUser,
		arg.CrawlID,
		arg.UserID,
		arg.Query,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCrawlPagesForUserRow
	for rows.Next() {
		var i SearchCrawlPagesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.Url,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrawlPageContentFingerprints = `-- name: UpdateCrawlPageContentFingerprints :exec
UPDATE crawl_pages
SET content_sha256 = $2
WHERE id = $1
`

type UpdateCrawlPageContentFingerprintsParams struct {
	ID            pgtype.UUID
	ContentSha256 pgtype.Text
}

func (q *Queries) UpdateCrawlPageContentFingerprints(ctx context.Context, arg UpdateCrawlPageContentFingerprintsParams) error {
	_, err := q.db.Exec(ctx, updateCrawlPageContentFingerprints, arg.ID, arg.ContentSha256)
	return err
}
