// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawl_score_breakdowns.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDistinctCrawlIssueURLsByTypeForCrawlByUser = `-- name: CountDistinctCrawlIssueURLsByTypeForCrawlByUser :one
SELECT COUNT(DISTINCT ci.url)
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
  AND ci.pillar = $3
  AND ci.bucket = $4
  AND ci.issue_type = $5
`

type CountDistinctCrawlIssueURLsByTypeForCrawlByUserParams struct {
	CrawlID   pgtype.UUID
	UserID    pgtype.UUID
	Pillar    string
	Bucket    string
	IssueType string
}

func (q *Queries) CountDistinctCrawlIssueURLsByTypeForCrawlByUser(ctx context.Context, arg CountDistinctCrawlIssueURLsByTypeForCrawlByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDistinctCrawlIssueURLsByTypeForCrawlByUser,
		arg.CrawlID,
		arg.UserID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCrawlScoreBreakdownByCrawlForUser = `-- name: GetCrawlScoreBreakdownByCrawlForUser :one
SELECT
    csb.crawl_id,
    csb.scoring_version,
    csb.breakdown_json,
    csb.created_at,
    csb.updated_at
FROM crawl_score_breakdowns AS csb
INNER JOIN crawls AS c ON c.id = csb.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE csb.crawl_id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlScoreBreakdownByCrawlForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetCrawlScoreBreakdownByCrawlForUser(ctx context.Context, arg GetCrawlScoreBreakdownByCrawlForUserParams) (CrawlScoreBreakdown, error) {
	row := q.db.QueryRow(ctx, getCrawlScoreBreakdownByCrawlForUser, arg.CrawlID, arg.UserID)
	var i CrawlScoreBreakdown
	err := row.Scan(
		&i.CrawlID,
		&i.ScoringVersion,
		&i.BreakdownJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDistinctCrawlIssueURLsByTypeForCrawlByUser = `-- name: ListDistinctCrawlIssueURLsByTypeForCrawlByUser :many
SELECT DISTINCT ON (ci.url)
    ci.url,
    ci.crawl_page_id,
    ci.severity,
    ci.message,
    ci.details
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
  AND ci.pillar = $3
  AND ci.bucket = $4
  AND ci.issue_type = $5
ORDER BY
    ci.url ASC,
    CASE ci.severity
        WHEN 'high' THEN 3
        WHEN 'medium' THEN 2
        WHEN 'low' THEN 1
        ELSE 0
    END DESC,
    ci.created_at ASC
LIMIT $6
OFFSET $7
`

type ListDistinctCrawlIssueURLsByTypeForCrawlByUserParams struct {
	CrawlID   pgtype.UUID
	UserID    pgtype.UUID
	Pillar    string
	Bucket    string
	IssueType string
	Limit     int32
	Offset    int32
}

type ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow struct {
	Url         string
	CrawlPageID pgtype.UUID
	Severity    string
	Message     string
	Details     string
}

func (q *Queries) ListDistinctCrawlIssueURLsByTypeForCrawlByUser(ctx context.Context, arg ListDistinctCrawlIssueURLsByTypeForCrawlByUserParams) ([]ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow, error) {
	rows, err := q.db.Query(ctx, listDistinctCrawlIssueURLsByTypeForCrawlByUser,
		arg.CrawlID,
		arg.UserID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow
	for rows.Next() {
		var i ListDistinctCrawlIssueURLsByTypeForCrawlByUserRow
		if err := rows.Scan(
			&i.Url,
			&i.CrawlPageID,
			&i.Severity,
			&i.Message,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCrawlScoreBreakdown = `-- name: UpsertCrawlScoreBreakdown :exec
INSERT INTO crawl_score_breakdowns (
    crawl_id,
    scoring_version,
    breakdown_json
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (crawl_id) DO UPDATE SET
    scoring_version = EXCLUDED.scoring_version,
    breakdown_json = EXCLUDED.breakdown_json,
    updated_at = now()
`

type UpsertCrawlScoreBreakdownParams struct {
	CrawlID        pgtype.UUID
	ScoringVersion string
	BreakdownJson  []byte
}

func (q *Queries) UpsertCrawlScoreBreakdown(ctx context.Context, arg UpsertCrawlScoreBreakdownParams) error {
	_, err := q.db.Exec(ctx, upsertCrawlScoreBreakdown, arg.CrawlID, arg.ScoringVersion, arg.BreakdownJson)
	return err
}
