// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawl_issues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCrawlIssuesForCrawlByUser = `-- name: CountCrawlIssuesForCrawlByUser :one
SELECT COUNT(*)
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
`

type CountCrawlIssuesForCrawlByUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) CountCrawlIssuesForCrawlByUser(ctx context.Context, arg CountCrawlIssuesForCrawlByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlIssuesForCrawlByUser, arg.CrawlID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCrawlIssue = `-- name: CreateCrawlIssue :one
INSERT INTO crawl_issues (
    crawl_id,
    crawl_page_id,
    url,
    severity,
    category,
    code,
    message,
    details
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, crawl_id, crawl_page_id, url, severity, category, code, message, details, created_at
`

type CreateCrawlIssueParams struct {
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Severity    string
	Category    string
	Code        string
	Message     string
	Details     string
}

func (q *Queries) CreateCrawlIssue(ctx context.Context, arg CreateCrawlIssueParams) (CrawlIssue, error) {
	row := q.db.QueryRow(ctx, createCrawlIssue,
		arg.CrawlID,
		arg.CrawlPageID,
		arg.Url,
		arg.Severity,
		arg.Category,
		arg.Code,
		arg.Message,
		arg.Details,
	)
	var i CrawlIssue
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.CrawlPageID,
		&i.Url,
		&i.Severity,
		&i.Category,
		&i.Code,
		&i.Message,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCrawlIssuesForCrawl = `-- name: DeleteCrawlIssuesForCrawl :exec
DELETE FROM crawl_issues
WHERE crawl_id = $1
`

func (q *Queries) DeleteCrawlIssuesForCrawl(ctx context.Context, crawlID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCrawlIssuesForCrawl, crawlID)
	return err
}

const getCrawlIssueByIDForUser = `-- name: GetCrawlIssueByIDForUser :one
SELECT
    ci.id,
    ci.crawl_id,
    ci.crawl_page_id,
    ci.url,
    ci.severity,
    ci.category,
    ci.code,
    ci.message,
    ci.details,
    ci.created_at
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlIssueByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetCrawlIssueByIDForUser(ctx context.Context, arg GetCrawlIssueByIDForUserParams) (CrawlIssue, error) {
	row := q.db.QueryRow(ctx, getCrawlIssueByIDForUser, arg.ID, arg.UserID)
	var i CrawlIssue
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.CrawlPageID,
		&i.Url,
		&i.Severity,
		&i.Category,
		&i.Code,
		&i.Message,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listCrawlIssuesForCrawl = `-- name: ListCrawlIssuesForCrawl :many
SELECT
    id,
    crawl_id,
    crawl_page_id,
    url,
    severity,
    category,
    code,
    message,
    details,
    created_at
FROM crawl_issues
WHERE crawl_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListCrawlIssuesForCrawl(ctx context.Context, crawlID pgtype.UUID) ([]CrawlIssue, error) {
	rows, err := q.db.Query(ctx, listCrawlIssuesForCrawl, crawlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawlIssue
	for rows.Next() {
		var i CrawlIssue
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.CrawlPageID,
			&i.Url,
			&i.Severity,
			&i.Category,
			&i.Code,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlIssuesForCrawlByUser = `-- name: ListCrawlIssuesForCrawlByUser :many
SELECT
    ci.id,
    ci.crawl_id,
    ci.crawl_page_id,
    ci.url,
    ci.severity,
    ci.category,
    ci.code,
    ci.message,
    ci.details,
    ci.created_at
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
ORDER BY ci.created_at ASC
LIMIT $3
OFFSET $4
`

type ListCrawlIssuesForCrawlByUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListCrawlIssuesForCrawlByUser(ctx context.Context, arg ListCrawlIssuesForCrawlByUserParams) ([]CrawlIssue, error) {
	rows, err := q.db.Query(ctx, listCrawlIssuesForCrawlByUser,
		arg.CrawlID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrawlIssue
	for rows.Next() {
		var i CrawlIssue
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.CrawlPageID,
			&i.Url,
			&i.Severity,
			&i.Category,
			&i.Code,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
