// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crawl_issues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const breakdownCrawlIssuesFilteredForUser = `-- name: BreakdownCrawlIssuesFilteredForUser :many
SELECT
    ci.pillar,
    ci.bucket,
    ci.issue_type,
    ci.severity,
    COUNT(*) AS issue_count
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
  AND ($3 = '' OR ci.pillar = $3)
  AND ($4 = '' OR ci.bucket = $4)
  AND ($5 = '' OR ci.issue_type = $5)
  AND ($6 = '' OR ci.severity = $6)
  AND ($7 = '' OR ci.url = $7)
  AND (coalesce(cardinality($8::text[]), 0) = 0 OR ci.url = ANY($8::text[]))
GROUP BY ci.pillar, ci.bucket, ci.issue_type, ci.severity
`

type BreakdownCrawlIssuesFilteredForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 interface{}
	Column7 interface{}
	Column8 []string
}

type BreakdownCrawlIssuesFilteredForUserRow struct {
	Pillar     string
	Bucket     string
	IssueType  string
	Severity   string
	IssueCount int64
}

func (q *Queries) BreakdownCrawlIssuesFilteredForUser(ctx context.Context, arg BreakdownCrawlIssuesFilteredForUserParams) ([]BreakdownCrawlIssuesFilteredForUserRow, error) {
	rows, err := q.db.Query(ctx, breakdownCrawlIssuesFilteredForUser,
		arg.CrawlID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BreakdownCrawlIssuesFilteredForUserRow
	for rows.Next() {
		var i BreakdownCrawlIssuesFilteredForUserRow
		if err := rows.Scan(
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.Severity,
			&i.IssueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCrawlIssuesFilteredForUser = `-- name: CountCrawlIssuesFilteredForUser :one
SELECT COUNT(*)
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
  AND ($3 = '' OR ci.pillar = $3)
  AND ($4 = '' OR ci.bucket = $4)
  AND ($5 = '' OR ci.issue_type = $5)
  AND ($6 = '' OR ci.severity = $6)
  AND (coalesce(cardinality($7::text[]), 0) = 0 OR ci.url = ANY($7::text[]))
`

type CountCrawlIssuesFilteredForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 interface{}
	Column7 []string
}

func (q *Queries) CountCrawlIssuesFilteredForUser(ctx context.Context, arg CountCrawlIssuesFilteredForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlIssuesFilteredForUser,
		arg.CrawlID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCrawlIssuesForCrawlByUser = `-- name: CountCrawlIssuesForCrawlByUser :one
SELECT COUNT(*)
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
`

type CountCrawlIssuesForCrawlByUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) CountCrawlIssuesForCrawlByUser(ctx context.Context, arg CountCrawlIssuesForCrawlByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCrawlIssuesForCrawlByUser, arg.CrawlID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCrawlIssue = `-- name: CreateCrawlIssue :one
INSERT INTO crawl_issues (
    crawl_id,
    crawl_page_id,
    url,
    pillar,
    bucket,
    issue_type,
    severity,
    message,
    details
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, crawl_id, crawl_page_id, url, pillar, bucket, issue_type, severity, message, details, created_at
`

type CreateCrawlIssueParams struct {
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Pillar      string
	Bucket      string
	IssueType   string
	Severity    string
	Message     string
	Details     string
}

type CreateCrawlIssueRow struct {
	ID          pgtype.UUID
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Pillar      string
	Bucket      string
	IssueType   string
	Severity    string
	Message     string
	Details     string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateCrawlIssue(ctx context.Context, arg CreateCrawlIssueParams) (CreateCrawlIssueRow, error) {
	row := q.db.QueryRow(ctx, createCrawlIssue,
		arg.CrawlID,
		arg.CrawlPageID,
		arg.Url,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
		arg.Severity,
		arg.Message,
		arg.Details,
	)
	var i CreateCrawlIssueRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.CrawlPageID,
		&i.Url,
		&i.Pillar,
		&i.Bucket,
		&i.IssueType,
		&i.Severity,
		&i.Message,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

type CreateCrawlIssuesParams struct {
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Pillar      string
	Bucket      string
	IssueType   string
	Severity    string
	Message     string
	Details     string
}

const deleteCrawlIssuesForCrawl = `-- name: DeleteCrawlIssuesForCrawl :exec
DELETE FROM crawl_issues
WHERE crawl_id = $1
`

func (q *Queries) DeleteCrawlIssuesForCrawl(ctx context.Context, crawlID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCrawlIssuesForCrawl, crawlID)
	return err
}

const getCrawlIssueByIDForUser = `-- name: GetCrawlIssueByIDForUser :one
SELECT
    ci.id,
    ci.crawl_id,
    ci.crawl_page_id,
    ci.url,
    ci.pillar,
    ci.bucket,
    ci.issue_type,
    ci.severity,
    ci.message,
    ci.details,
    ci.created_at
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetCrawlIssueByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetCrawlIssueByIDForUserRow struct {
	ID          pgtype.UUID
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Pillar      string
	Bucket      string
	IssueType   string
	Severity    string
	Message     string
	Details     string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetCrawlIssueByIDForUser(ctx context.Context, arg GetCrawlIssueByIDForUserParams) (GetCrawlIssueByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getCrawlIssueByIDForUser, arg.ID, arg.UserID)
	var i GetCrawlIssueByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.CrawlPageID,
		&i.Url,
		&i.Pillar,
		&i.Bucket,
		&i.IssueType,
		&i.Severity,
		&i.Message,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const listCrawlIssuesFilteredForUser = `-- name: ListCrawlIssuesFilteredForUser :many
SELECT
    ci.id,
    ci.crawl_id,
    ci.crawl_page_id,
    ci.url,
    ci.pillar,
    ci.bucket,
    ci.issue_type,
    ci.severity,
    ci.message,
    ci.details,
    ci.created_at
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
  AND ($3 = '' OR ci.pillar = $3)
  AND ($4 = '' OR ci.bucket = $4)
  AND ($5 = '' OR ci.issue_type = $5)
  AND ($6 = '' OR ci.severity = $6)
  AND ($7 = '' OR ci.url = $7)
  AND (coalesce(cardinality($8::text[]), 0) = 0 OR ci.url = ANY($8::text[]))
ORDER BY
    CASE ci.severity WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END DESC,
    ci.bucket,
    ci.issue_type,
    ci.url,
    ci.id
LIMIT $9
OFFSET $10
`

type ListCrawlIssuesFilteredForUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 interface{}
	Column7 interface{}
	Column8 []string
	Limit   int32
	Offset  int32
}

type ListCrawlIssuesFilteredForUserRow struct {
	ID          pgtype.UUID
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Pillar      string
	Bucket      string
	IssueType   string
	Severity    string
	Message     string
	Details     string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListCrawlIssuesFilteredForUser(ctx context.Context, arg ListCrawlIssuesFilteredForUserParams) ([]ListCrawlIssuesFilteredForUserRow, error) {
	rows, err := q.db.Query(ctx, listCrawlIssuesFilteredForUser,
		arg.CrawlID,
		arg.UserID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlIssuesFilteredForUserRow
	for rows.Next() {
		var i ListCrawlIssuesFilteredForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.CrawlPageID,
			&i.Url,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.Severity,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlIssuesForCrawl = `-- name: ListCrawlIssuesForCrawl :many
SELECT
    id,
    crawl_id,
    crawl_page_id,
    url,
    pillar,
    bucket,
    issue_type,
    severity,
    message,
    details,
    created_at
FROM crawl_issues
WHERE crawl_id = $1
ORDER BY created_at ASC
`

type ListCrawlIssuesForCrawlRow struct {
	ID          pgtype.UUID
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Pillar      string
	Bucket      string
	IssueType   string
	Severity    string
	Message     string
	Details     string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListCrawlIssuesForCrawl(ctx context.Context, crawlID pgtype.UUID) ([]ListCrawlIssuesForCrawlRow, error) {
	rows, err := q.db.Query(ctx, listCrawlIssuesForCrawl, crawlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlIssuesForCrawlRow
	for rows.Next() {
		var i ListCrawlIssuesForCrawlRow
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.CrawlPageID,
			&i.Url,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.Severity,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrawlIssuesForCrawlByUser = `-- name: ListCrawlIssuesForCrawlByUser :many
SELECT
    ci.id,
    ci.crawl_id,
    ci.crawl_page_id,
    ci.url,
    ci.pillar,
    ci.bucket,
    ci.issue_type,
    ci.severity,
    ci.message,
    ci.details,
    ci.created_at
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
ORDER BY ci.created_at ASC
LIMIT $3
OFFSET $4
`

type ListCrawlIssuesForCrawlByUserParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListCrawlIssuesForCrawlByUserRow struct {
	ID          pgtype.UUID
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Pillar      string
	Bucket      string
	IssueType   string
	Severity    string
	Message     string
	Details     string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListCrawlIssuesForCrawlByUser(ctx context.Context, arg ListCrawlIssuesForCrawlByUserParams) ([]ListCrawlIssuesForCrawlByUserRow, error) {
	rows, err := q.db.Query(ctx, listCrawlIssuesForCrawlByUser,
		arg.CrawlID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCrawlIssuesForCrawlByUserRow
	for rows.Next() {
		var i ListCrawlIssuesForCrawlByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CrawlID,
			&i.CrawlPageID,
			&i.Url,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.Severity,
			&i.Message,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctCrawlIssueDimensions = `-- name: ListDistinctCrawlIssueDimensions :many
SELECT DISTINCT
    ci.pillar,
    ci.bucket,
    ci.issue_type
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.crawl_id = $1
  AND om.user_id = $2
ORDER BY ci.pillar, ci.bucket, ci.issue_type
`

type ListDistinctCrawlIssueDimensionsParams struct {
	CrawlID pgtype.UUID
	UserID  pgtype.UUID
}

type ListDistinctCrawlIssueDimensionsRow struct {
	Pillar    string
	Bucket    string
	IssueType string
}

func (q *Queries) ListDistinctCrawlIssueDimensions(ctx context.Context, arg ListDistinctCrawlIssueDimensionsParams) ([]ListDistinctCrawlIssueDimensionsRow, error) {
	rows, err := q.db.Query(ctx, listDistinctCrawlIssueDimensions, arg.CrawlID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDistinctCrawlIssueDimensionsRow
	for rows.Next() {
		var i ListDistinctCrawlIssueDimensionsRow
		if err := rows.Scan(&i.Pillar, &i.Bucket, &i.IssueType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
