// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: google_analytics.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectGoogleAnalyticsConnectionByProjectID = `-- name: DeleteProjectGoogleAnalyticsConnectionByProjectID :execrows
DELETE FROM project_google_analytics_connections
WHERE project_id = $1
`

func (q *Queries) DeleteProjectGoogleAnalyticsConnectionByProjectID(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectGoogleAnalyticsConnectionByProjectID, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectGoogleAnalyticsConnectionByProjectID = `-- name: GetProjectGoogleAnalyticsConnectionByProjectID :one
SELECT id, project_id, google_connection_id, property_id, property_display_name, account_display_name, created_at, updated_at
FROM project_google_analytics_connections
WHERE project_id = $1
LIMIT 1
`

func (q *Queries) GetProjectGoogleAnalyticsConnectionByProjectID(ctx context.Context, projectID pgtype.UUID) (ProjectGoogleAnalyticsConnection, error) {
	row := q.db.QueryRow(ctx, getProjectGoogleAnalyticsConnectionByProjectID, projectID)
	var i ProjectGoogleAnalyticsConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoogleConnectionID,
		&i.PropertyID,
		&i.PropertyDisplayName,
		&i.AccountDisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectGoogleAnalyticsConnection = `-- name: UpsertProjectGoogleAnalyticsConnection :one
INSERT INTO project_google_analytics_connections (
    project_id,
    google_connection_id,
    property_id,
    property_display_name,
    account_display_name
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id) DO UPDATE SET
    google_connection_id = excluded.google_connection_id,
    property_id = excluded.property_id,
    property_display_name = excluded.property_display_name,
    account_display_name = excluded.account_display_name,
    updated_at = now()
RETURNING id, project_id, google_connection_id, property_id, property_display_name, account_display_name, created_at, updated_at
`

type UpsertProjectGoogleAnalyticsConnectionParams struct {
	ProjectID           pgtype.UUID
	GoogleConnectionID  pgtype.UUID
	PropertyID          string
	PropertyDisplayName string
	AccountDisplayName  pgtype.Text
}

func (q *Queries) UpsertProjectGoogleAnalyticsConnection(ctx context.Context, arg UpsertProjectGoogleAnalyticsConnectionParams) (ProjectGoogleAnalyticsConnection, error) {
	row := q.db.QueryRow(ctx, upsertProjectGoogleAnalyticsConnection,
		arg.ProjectID,
		arg.GoogleConnectionID,
		arg.PropertyID,
		arg.PropertyDisplayName,
		arg.AccountDisplayName,
	)
	var i ProjectGoogleAnalyticsConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoogleConnectionID,
		&i.PropertyID,
		&i.PropertyDisplayName,
		&i.AccountDisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
