// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gsc.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptGoogleConnectionIdentity = `-- name: AdoptGoogleConnectionIdentity :exec
UPDATE google_connections
SET google_account_email = $2,
    google_account_subject = $3,
    updated_at = now()
WHERE id = $1
`

type AdoptGoogleConnectionIdentityParams struct {
	ID                   pgtype.UUID
	GoogleAccountEmail   pgtype.Text
	GoogleAccountSubject pgtype.Text
}

func (q *Queries) AdoptGoogleConnectionIdentity(ctx context.Context, arg AdoptGoogleConnectionIdentityParams) error {
	_, err := q.db.Exec(ctx, adoptGoogleConnectionIdentity, arg.ID, arg.GoogleAccountEmail, arg.GoogleAccountSubject)
	return err
}

const createGoogleConnection = `-- name: CreateGoogleConnection :one
INSERT INTO google_connections (
    organization_id,
    connected_by_user_id,
    google_account_email,
    google_account_subject,
    encrypted_refresh_token,
    encrypted_access_token,
    access_token_expires_at,
    scope,
    status,
    last_error
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    'active',
    NULL
)
RETURNING id, organization_id, connected_by_user_id, google_account_email, google_account_subject, encrypted_refresh_token, encrypted_access_token, access_token_expires_at, scope, status, last_error, created_at, updated_at
`

type CreateGoogleConnectionParams struct {
	OrganizationID        pgtype.UUID
	ConnectedByUserID     pgtype.UUID
	GoogleAccountEmail    pgtype.Text
	GoogleAccountSubject  pgtype.Text
	EncryptedRefreshToken string
	EncryptedAccessToken  pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	Scope                 string
}

func (q *Queries) CreateGoogleConnection(ctx context.Context, arg CreateGoogleConnectionParams) (GoogleConnection, error) {
	row := q.db.QueryRow(ctx, createGoogleConnection,
		arg.OrganizationID,
		arg.ConnectedByUserID,
		arg.GoogleAccountEmail,
		arg.GoogleAccountSubject,
		arg.EncryptedRefreshToken,
		arg.EncryptedAccessToken,
		arg.AccessTokenExpiresAt,
		arg.Scope,
	)
	var i GoogleConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.GoogleAccountEmail,
		&i.GoogleAccountSubject,
		&i.EncryptedRefreshToken,
		&i.EncryptedAccessToken,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGoogleOAuthState = `-- name: CreateGoogleOAuthState :one
INSERT INTO google_oauth_states (
    state_token_hash,
    organization_id,
    user_id,
    project_id,
    return_path,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, state_token_hash, organization_id, user_id, project_id, return_path, expires_at, created_at
`

type CreateGoogleOAuthStateParams struct {
	StateTokenHash string
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	ProjectID      pgtype.UUID
	ReturnPath     string
	ExpiresAt      pgtype.Timestamptz
}

type CreateGoogleOAuthStateRow struct {
	ID             pgtype.UUID
	StateTokenHash string
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	ProjectID      pgtype.UUID
	ReturnPath     string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateGoogleOAuthState(ctx context.Context, arg CreateGoogleOAuthStateParams) (CreateGoogleOAuthStateRow, error) {
	row := q.db.QueryRow(ctx, createGoogleOAuthState,
		arg.StateTokenHash,
		arg.OrganizationID,
		arg.UserID,
		arg.ProjectID,
		arg.ReturnPath,
		arg.ExpiresAt,
	)
	var i CreateGoogleOAuthStateRow
	err := row.Scan(
		&i.ID,
		&i.StateTokenHash,
		&i.OrganizationID,
		&i.UserID,
		&i.ProjectID,
		&i.ReturnPath,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGoogleOAuthStateWithPurpose = `-- name: CreateGoogleOAuthStateWithPurpose :one
INSERT INTO google_oauth_states (
    state_token_hash,
    organization_id,
    user_id,
    project_id,
    return_path,
    purpose,
    google_connection_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, state_token_hash, organization_id, user_id, project_id, return_path, purpose, google_connection_id, expires_at, created_at
`

type CreateGoogleOAuthStateWithPurposeParams struct {
	StateTokenHash     string
	OrganizationID     pgtype.UUID
	UserID             pgtype.UUID
	ProjectID          pgtype.UUID
	ReturnPath         string
	Purpose            string
	GoogleConnectionID pgtype.UUID
	ExpiresAt          pgtype.Timestamptz
}

type CreateGoogleOAuthStateWithPurposeRow struct {
	ID                 pgtype.UUID
	StateTokenHash     string
	OrganizationID     pgtype.UUID
	UserID             pgtype.UUID
	ProjectID          pgtype.UUID
	ReturnPath         string
	Purpose            string
	GoogleConnectionID pgtype.UUID
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateGoogleOAuthStateWithPurpose(ctx context.Context, arg CreateGoogleOAuthStateWithPurposeParams) (CreateGoogleOAuthStateWithPurposeRow, error) {
	row := q.db.QueryRow(ctx, createGoogleOAuthStateWithPurpose,
		arg.StateTokenHash,
		arg.OrganizationID,
		arg.UserID,
		arg.ProjectID,
		arg.ReturnPath,
		arg.Purpose,
		arg.GoogleConnectionID,
		arg.ExpiresAt,
	)
	var i CreateGoogleOAuthStateWithPurposeRow
	err := row.Scan(
		&i.ID,
		&i.StateTokenHash,
		&i.OrganizationID,
		&i.UserID,
		&i.ProjectID,
		&i.ReturnPath,
		&i.Purpose,
		&i.GoogleConnectionID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGoogleOAuthStateByID = `-- name: DeleteGoogleOAuthStateByID :execrows
DELETE FROM google_oauth_states
WHERE id = $1
`

func (q *Queries) DeleteGoogleOAuthStateByID(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGoogleOAuthStateByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectGSCConnectionByProjectID = `-- name: DeleteProjectGSCConnectionByProjectID :execrows
DELETE FROM project_gsc_connections
WHERE project_id = $1
`

func (q *Queries) DeleteProjectGSCConnectionByProjectID(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectGSCConnectionByProjectID, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGoogleConnectionByID = `-- name: GetGoogleConnectionByID :one
SELECT id, organization_id, connected_by_user_id, google_account_email, google_account_subject, encrypted_refresh_token, encrypted_access_token, access_token_expires_at, scope, status, last_error, created_at, updated_at
FROM google_connections
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetGoogleConnectionByID(ctx context.Context, id pgtype.UUID) (GoogleConnection, error) {
	row := q.db.QueryRow(ctx, getGoogleConnectionByID, id)
	var i GoogleConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.GoogleAccountEmail,
		&i.GoogleAccountSubject,
		&i.EncryptedRefreshToken,
		&i.EncryptedAccessToken,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoogleConnectionByOrganizationID = `-- name: GetGoogleConnectionByOrganizationID :one
SELECT id, organization_id, connected_by_user_id, google_account_email, google_account_subject, encrypted_refresh_token, encrypted_access_token, access_token_expires_at, scope, status, last_error, created_at, updated_at
FROM google_connections
WHERE organization_id = $1
LIMIT 1
`

func (q *Queries) GetGoogleConnectionByOrganizationID(ctx context.Context, organizationID pgtype.UUID) (GoogleConnection, error) {
	row := q.db.QueryRow(ctx, getGoogleConnectionByOrganizationID, organizationID)
	var i GoogleConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.GoogleAccountEmail,
		&i.GoogleAccountSubject,
		&i.EncryptedRefreshToken,
		&i.EncryptedAccessToken,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoogleConnectionByOrganizationSubject = `-- name: GetGoogleConnectionByOrganizationSubject :one
SELECT id, organization_id, connected_by_user_id, google_account_email, google_account_subject, encrypted_refresh_token, encrypted_access_token, access_token_expires_at, scope, status, last_error, created_at, updated_at
FROM google_connections
WHERE organization_id = $1 AND google_account_subject = $2
LIMIT 1
`

type GetGoogleConnectionByOrganizationSubjectParams struct {
	OrganizationID       pgtype.UUID
	GoogleAccountSubject pgtype.Text
}

func (q *Queries) GetGoogleConnectionByOrganizationSubject(ctx context.Context, arg GetGoogleConnectionByOrganizationSubjectParams) (GoogleConnection, error) {
	row := q.db.QueryRow(ctx, getGoogleConnectionByOrganizationSubject, arg.OrganizationID, arg.GoogleAccountSubject)
	var i GoogleConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.GoogleAccountEmail,
		&i.GoogleAccountSubject,
		&i.EncryptedRefreshToken,
		&i.EncryptedAccessToken,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGoogleOAuthStateByTokenHash = `-- name: GetGoogleOAuthStateByTokenHash :one
SELECT id, state_token_hash, organization_id, user_id, project_id, return_path, expires_at, created_at
FROM google_oauth_states
WHERE state_token_hash = $1
LIMIT 1
`

type GetGoogleOAuthStateByTokenHashRow struct {
	ID             pgtype.UUID
	StateTokenHash string
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	ProjectID      pgtype.UUID
	ReturnPath     string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetGoogleOAuthStateByTokenHash(ctx context.Context, stateTokenHash string) (GetGoogleOAuthStateByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getGoogleOAuthStateByTokenHash, stateTokenHash)
	var i GetGoogleOAuthStateByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.StateTokenHash,
		&i.OrganizationID,
		&i.UserID,
		&i.ProjectID,
		&i.ReturnPath,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGoogleOAuthStateWithPurpose = `-- name: GetGoogleOAuthStateWithPurpose :one
SELECT id, state_token_hash, organization_id, user_id, project_id, return_path, purpose, google_connection_id, expires_at, created_at
FROM google_oauth_states
WHERE state_token_hash = $1
LIMIT 1
`

type GetGoogleOAuthStateWithPurposeRow struct {
	ID                 pgtype.UUID
	StateTokenHash     string
	OrganizationID     pgtype.UUID
	UserID             pgtype.UUID
	ProjectID          pgtype.UUID
	ReturnPath         string
	Purpose            string
	GoogleConnectionID pgtype.UUID
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) GetGoogleOAuthStateWithPurpose(ctx context.Context, stateTokenHash string) (GetGoogleOAuthStateWithPurposeRow, error) {
	row := q.db.QueryRow(ctx, getGoogleOAuthStateWithPurpose, stateTokenHash)
	var i GetGoogleOAuthStateWithPurposeRow
	err := row.Scan(
		&i.ID,
		&i.StateTokenHash,
		&i.OrganizationID,
		&i.UserID,
		&i.ProjectID,
		&i.ReturnPath,
		&i.Purpose,
		&i.GoogleConnectionID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectGSCConnectionByProjectID = `-- name: GetProjectGSCConnectionByProjectID :one
SELECT id, project_id, google_connection_id, site_url, permission_level, created_at, updated_at
FROM project_gsc_connections
WHERE project_id = $1
LIMIT 1
`

func (q *Queries) GetProjectGSCConnectionByProjectID(ctx context.Context, projectID pgtype.UUID) (ProjectGscConnection, error) {
	row := q.db.QueryRow(ctx, getProjectGSCConnectionByProjectID, projectID)
	var i ProjectGscConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoogleConnectionID,
		&i.SiteUrl,
		&i.PermissionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGoogleConnectionsByOrganizationID = `-- name: ListGoogleConnectionsByOrganizationID :many
SELECT id, organization_id, connected_by_user_id, google_account_email, google_account_subject, encrypted_refresh_token, encrypted_access_token, access_token_expires_at, scope, status, last_error, created_at, updated_at
FROM google_connections
WHERE organization_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListGoogleConnectionsByOrganizationID(ctx context.Context, organizationID pgtype.UUID) ([]GoogleConnection, error) {
	rows, err := q.db.Query(ctx, listGoogleConnectionsByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoogleConnection
	for rows.Next() {
		var i GoogleConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ConnectedByUserID,
			&i.GoogleAccountEmail,
			&i.GoogleAccountSubject,
			&i.EncryptedRefreshToken,
			&i.EncryptedAccessToken,
			&i.AccessTokenExpiresAt,
			&i.Scope,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeGoogleConnection = `-- name: RevokeGoogleConnection :exec
UPDATE google_connections
SET status = 'revoked',
    encrypted_access_token = NULL,
    access_token_expires_at = NULL,
    last_error = $2,
    updated_at = now()
WHERE id = $1
`

type RevokeGoogleConnectionParams struct {
	ID        pgtype.UUID
	LastError pgtype.Text
}

func (q *Queries) RevokeGoogleConnection(ctx context.Context, arg RevokeGoogleConnectionParams) error {
	_, err := q.db.Exec(ctx, revokeGoogleConnection, arg.ID, arg.LastError)
	return err
}

const updateGoogleConnectionStatus = `-- name: UpdateGoogleConnectionStatus :exec
UPDATE google_connections
SET status = $2,
    last_error = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateGoogleConnectionStatusParams struct {
	ID        pgtype.UUID
	Status    string
	LastError pgtype.Text
}

func (q *Queries) UpdateGoogleConnectionStatus(ctx context.Context, arg UpdateGoogleConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateGoogleConnectionStatus, arg.ID, arg.Status, arg.LastError)
	return err
}

const updateGoogleConnectionTokens = `-- name: UpdateGoogleConnectionTokens :one
UPDATE google_connections
SET encrypted_access_token = $2,
    encrypted_refresh_token = COALESCE($3, encrypted_refresh_token),
    access_token_expires_at = $4,
    scope = COALESCE($5, scope),
    status = $6,
    last_error = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, connected_by_user_id, google_account_email, google_account_subject, encrypted_refresh_token, encrypted_access_token, access_token_expires_at, scope, status, last_error, created_at, updated_at
`

type UpdateGoogleConnectionTokensParams struct {
	ID                    pgtype.UUID
	EncryptedAccessToken  pgtype.Text
	EncryptedRefreshToken string
	AccessTokenExpiresAt  pgtype.Timestamptz
	Scope                 string
	Status                string
	LastError             pgtype.Text
}

func (q *Queries) UpdateGoogleConnectionTokens(ctx context.Context, arg UpdateGoogleConnectionTokensParams) (GoogleConnection, error) {
	row := q.db.QueryRow(ctx, updateGoogleConnectionTokens,
		arg.ID,
		arg.EncryptedAccessToken,
		arg.EncryptedRefreshToken,
		arg.AccessTokenExpiresAt,
		arg.Scope,
		arg.Status,
		arg.LastError,
	)
	var i GoogleConnection
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.GoogleAccountEmail,
		&i.GoogleAccountSubject,
		&i.EncryptedRefreshToken,
		&i.EncryptedAccessToken,
		&i.AccessTokenExpiresAt,
		&i.Scope,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectGSCConnection = `-- name: UpsertProjectGSCConnection :one
INSERT INTO project_gsc_connections (
    project_id,
    google_connection_id,
    site_url,
    permission_level
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (project_id) DO UPDATE SET
    google_connection_id = excluded.google_connection_id,
    site_url = excluded.site_url,
    permission_level = excluded.permission_level,
    updated_at = now()
RETURNING id, project_id, google_connection_id, site_url, permission_level, created_at, updated_at
`

type UpsertProjectGSCConnectionParams struct {
	ProjectID          pgtype.UUID
	GoogleConnectionID pgtype.UUID
	SiteUrl            string
	PermissionLevel    pgtype.Text
}

func (q *Queries) UpsertProjectGSCConnection(ctx context.Context, arg UpsertProjectGSCConnectionParams) (ProjectGscConnection, error) {
	row := q.db.QueryRow(ctx, upsertProjectGSCConnection,
		arg.ProjectID,
		arg.GoogleConnectionID,
		arg.SiteUrl,
		arg.PermissionLevel,
	)
	var i ProjectGscConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.GoogleConnectionID,
		&i.SiteUrl,
		&i.PermissionLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
