// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_work.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addIssueWorkAttemptContributor = `-- name: AddIssueWorkAttemptContributor :one
INSERT INTO issue_work_attempt_contributors (attempt_id, user_id)
SELECT $1, $2
FROM issue_work_attempts AS attempt
WHERE attempt.id = $1
  AND attempt.locked_at IS NULL
  AND attempt.status IN ('awaiting_verification', 'not_verified')
FOR KEY SHARE OF attempt
ON CONFLICT (attempt_id, user_id) DO UPDATE
SET marked_done_at = issue_work_attempt_contributors.marked_done_at
RETURNING attempt_id, user_id, marked_done_at
`

type AddIssueWorkAttemptContributorParams struct {
	AttemptID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) AddIssueWorkAttemptContributor(ctx context.Context, arg AddIssueWorkAttemptContributorParams) (IssueWorkAttemptContributor, error) {
	row := q.db.QueryRow(ctx, addIssueWorkAttemptContributor, arg.AttemptID, arg.UserID)
	var i IssueWorkAttemptContributor
	err := row.Scan(&i.AttemptID, &i.UserID, &i.MarkedDoneAt)
	return i, err
}

const createIssueWorkAttempt = `-- name: CreateIssueWorkAttempt :one
INSERT INTO issue_work_attempts (work_item_id, source_crawl_id)
VALUES ($1, $2)
RETURNING id, work_item_id, source_crawl_id, status, verification_crawl_id, created_at, locked_at, verified_at
`

type CreateIssueWorkAttemptParams struct {
	WorkItemID    pgtype.UUID
	SourceCrawlID pgtype.UUID
}

func (q *Queries) CreateIssueWorkAttempt(ctx context.Context, arg CreateIssueWorkAttemptParams) (IssueWorkAttempt, error) {
	row := q.db.QueryRow(ctx, createIssueWorkAttempt, arg.WorkItemID, arg.SourceCrawlID)
	var i IssueWorkAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkItemID,
		&i.SourceCrawlID,
		&i.Status,
		&i.VerificationCrawlID,
		&i.CreatedAt,
		&i.LockedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const deleteEmptyUnlockedIssueWorkAttempt = `-- name: DeleteEmptyUnlockedIssueWorkAttempt :execrows
DELETE FROM issue_work_attempts AS attempt
WHERE attempt.id = $1
  AND attempt.locked_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM issue_work_attempt_contributors AS contributor
      WHERE contributor.attempt_id = attempt.id
  )
`

func (q *Queries) DeleteEmptyUnlockedIssueWorkAttempt(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEmptyUnlockedIssueWorkAttempt, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveIssueWorkAttemptForWorkItem = `-- name: GetActiveIssueWorkAttemptForWorkItem :one
SELECT id, work_item_id, source_crawl_id, status, verification_crawl_id, created_at, locked_at, verified_at
FROM issue_work_attempts
WHERE work_item_id = $1
  AND status IN ('awaiting_verification', 'not_verified')
  AND locked_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveIssueWorkAttemptForWorkItem(ctx context.Context, workItemID pgtype.UUID) (IssueWorkAttempt, error) {
	row := q.db.QueryRow(ctx, getActiveIssueWorkAttemptForWorkItem, workItemID)
	var i IssueWorkAttempt
	err := row.Scan(
		&i.ID,
		&i.WorkItemID,
		&i.SourceCrawlID,
		&i.Status,
		&i.VerificationCrawlID,
		&i.CreatedAt,
		&i.LockedAt,
		&i.VerifiedAt,
	)
	return i, err
}

const getDuplicateGroupVerificationEvidence = `-- name: GetDuplicateGroupVerificationEvidence :one
WITH original_members AS (
    SELECT member.url FROM crawl_issue_group_members AS member
    WHERE member.group_id = $2
), member_coverage AS (
    SELECT COUNT(*) >= 2 AND NOT EXISTS (
        SELECT 1 FROM original_members AS original
        WHERE NOT EXISTS (
            SELECT 1 FROM crawl_pages AS cp
            WHERE cp.crawl_id = $3
	          AND cp.url = original.url
	          AND cp.fetch_error IS NULL
	          AND cp.soft_404 = FALSE
	          AND cp.status_code BETWEEN 200 AND 299
        )
    ) AS all_members_observed
	FROM original_members
), exact_relationship AS (
    SELECT EXISTS (
        SELECT 1
        FROM crawl_issue_groups AS current_group
        INNER JOIN crawl_issue_group_members AS current_member ON current_member.group_id = current_group.id
        INNER JOIN original_members AS original ON original.url = current_member.url
        WHERE current_group.crawl_id = $3
          AND current_group.issue_type = $1
        GROUP BY current_group.id
        HAVING COUNT(DISTINCT original.url) >= 2
    ) AS remains
), near_relationship AS (
    SELECT EXISTS (
        SELECT 1
        FROM crawl_issue_relations AS current_relation
        INNER JOIN crawl_pages AS current_left ON current_left.id = current_relation.left_crawl_page_id
        INNER JOIN crawl_pages AS current_right ON current_right.id = current_relation.right_crawl_page_id
        WHERE current_relation.crawl_id = $3
          AND current_relation.issue_type = $1
          AND EXISTS (
			  SELECT 1
			  FROM crawl_issue_relations AS original_relation
			  INNER JOIN crawl_issue_groups AS source_group ON source_group.id = $2 AND source_group.crawl_id = original_relation.crawl_id
			  INNER JOIN crawl_pages AS original_left ON original_left.id = original_relation.left_crawl_page_id
			  INNER JOIN crawl_pages AS original_right ON original_right.id = original_relation.right_crawl_page_id
			  WHERE original_relation.issue_type = $1
			    AND original_left.url IN (SELECT url FROM original_members)
			    AND original_right.url IN (SELECT url FROM original_members)
			    AND LEAST(original_left.url, original_right.url) = LEAST(current_left.url, current_right.url)
			    AND GREATEST(original_left.url, original_right.url) = GREATEST(current_left.url, current_right.url)
		  )
    ) AS remains
)
SELECT
    member_coverage.all_members_observed,
    (CASE WHEN $1::text = 'near_duplicate_content'
         THEN near_relationship.remains ELSE exact_relationship.remains END)::boolean AS issue_present
FROM member_coverage, exact_relationship, near_relationship
`

type GetDuplicateGroupVerificationEvidenceParams struct {
	IssueType     string
	SourceGroupID pgtype.UUID
	CrawlID       pgtype.UUID
}

type GetDuplicateGroupVerificationEvidenceRow struct {
	AllMembersObserved pgtype.Bool
	IssuePresent       bool
}

func (q *Queries) GetDuplicateGroupVerificationEvidence(ctx context.Context, arg GetDuplicateGroupVerificationEvidenceParams) (GetDuplicateGroupVerificationEvidenceRow, error) {
	row := q.db.QueryRow(ctx, getDuplicateGroupVerificationEvidence, arg.IssueType, arg.SourceGroupID, arg.CrawlID)
	var i GetDuplicateGroupVerificationEvidenceRow
	err := row.Scan(&i.AllMembersObserved, &i.IssuePresent)
	return i, err
}

const getIssueWorkAttemptByIDForUser = `-- name: GetIssueWorkAttemptByIDForUser :one
SELECT wa.id, wa.work_item_id, wa.source_crawl_id, wa.status, wa.verification_crawl_id, wa.created_at, wa.locked_at, wa.verified_at, wi.project_id
FROM issue_work_attempts AS wa
INNER JOIN issue_work_items AS wi ON wi.id = wa.work_item_id
INNER JOIN projects AS p ON p.id = wi.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE wa.id = $1
  AND om.user_id = $2
LIMIT 1
FOR UPDATE OF wa
`

type GetIssueWorkAttemptByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetIssueWorkAttemptByIDForUserRow struct {
	ID                  pgtype.UUID
	WorkItemID          pgtype.UUID
	SourceCrawlID       pgtype.UUID
	Status              string
	VerificationCrawlID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	LockedAt            pgtype.Timestamptz
	VerifiedAt          pgtype.Timestamptz
	ProjectID           pgtype.UUID
}

func (q *Queries) GetIssueWorkAttemptByIDForUser(ctx context.Context, arg GetIssueWorkAttemptByIDForUserParams) (GetIssueWorkAttemptByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getIssueWorkAttemptByIDForUser, arg.ID, arg.UserID)
	var i GetIssueWorkAttemptByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.WorkItemID,
		&i.SourceCrawlID,
		&i.Status,
		&i.VerificationCrawlID,
		&i.CreatedAt,
		&i.LockedAt,
		&i.VerifiedAt,
		&i.ProjectID,
	)
	return i, err
}

const getPageIssueVerificationEvidence = `-- name: GetPageIssueVerificationEvidence :one
SELECT
    EXISTS (
        SELECT 1 FROM crawl_pages AS cp
        WHERE cp.crawl_id = $1
          AND cp.url = $2
          AND cp.fetch_error IS NULL
          AND cp.soft_404 = FALSE
          AND cp.status_code BETWEEN 200 AND 299
    ) AS page_observed,
    EXISTS (
        SELECT 1 FROM crawl_issues AS ci
        WHERE ci.crawl_id = $1
          AND ci.url = $2
          AND ci.pillar = $3
          AND ci.bucket = $4
          AND ci.issue_type = $5
    ) AS issue_present,
    CASE
        WHEN $4::text = 'psi_cwv' THEN COALESCE(c.google_psi_results #>> '{0,mobile,success}', 'false') = 'true'
        ELSE TRUE
    END AS required_evidence_observed
FROM crawls AS c
WHERE c.id = $1
`

type GetPageIssueVerificationEvidenceParams struct {
	CrawlID   pgtype.UUID
	Url       string
	Pillar    string
	Bucket    string
	IssueType string
}

type GetPageIssueVerificationEvidenceRow struct {
	PageObserved             bool
	IssuePresent             bool
	RequiredEvidenceObserved bool
}

func (q *Queries) GetPageIssueVerificationEvidence(ctx context.Context, arg GetPageIssueVerificationEvidenceParams) (GetPageIssueVerificationEvidenceRow, error) {
	row := q.db.QueryRow(ctx, getPageIssueVerificationEvidence,
		arg.CrawlID,
		arg.Url,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
	)
	var i GetPageIssueVerificationEvidenceRow
	err := row.Scan(&i.PageObserved, &i.IssuePresent, &i.RequiredEvidenceObserved)
	return i, err
}

const getSiteIssueVerificationEvidence = `-- name: GetSiteIssueVerificationEvidence :one
WITH coverage AS (
	SELECT EXISTS (
		SELECT 1 FROM crawl_pages AS baseline_page
		WHERE baseline_page.crawl_id = $5
		  AND baseline_page.fetch_error IS NULL AND baseline_page.soft_404 = FALSE
		  AND baseline_page.status_code BETWEEN 200 AND 299
	) AND NOT EXISTS (
		SELECT 1 FROM crawl_pages AS baseline_page
		WHERE baseline_page.crawl_id = $5
		  AND baseline_page.fetch_error IS NULL AND baseline_page.soft_404 = FALSE
		  AND baseline_page.status_code BETWEEN 200 AND 299
		  AND NOT EXISTS (
			SELECT 1 FROM crawl_pages AS current_page
			WHERE current_page.crawl_id = $1
			  AND current_page.url = baseline_page.url
			  AND current_page.fetch_error IS NULL AND current_page.soft_404 = FALSE
			  AND current_page.status_code BETWEEN 200 AND 299
		  )
	) AS coverage_observed
)
SELECT coverage.coverage_observed,
	EXISTS (
		SELECT 1 FROM crawl_issues AS issue
		WHERE issue.crawl_id = $1
		  AND issue.pillar = $2
		  AND issue.bucket = $3
		  AND issue.issue_type = $4
	) AS issue_present
FROM coverage
`

type GetSiteIssueVerificationEvidenceParams struct {
	CrawlID       pgtype.UUID
	Pillar        string
	Bucket        string
	IssueType     string
	SourceCrawlID pgtype.UUID
}

type GetSiteIssueVerificationEvidenceRow struct {
	CoverageObserved pgtype.Bool
	IssuePresent     bool
}

func (q *Queries) GetSiteIssueVerificationEvidence(ctx context.Context, arg GetSiteIssueVerificationEvidenceParams) (GetSiteIssueVerificationEvidenceRow, error) {
	row := q.db.QueryRow(ctx, getSiteIssueVerificationEvidence,
		arg.CrawlID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
		arg.SourceCrawlID,
	)
	var i GetSiteIssueVerificationEvidenceRow
	err := row.Scan(&i.CoverageObserved, &i.IssuePresent)
	return i, err
}

const getWorkableCrawlIssueByIDForUser = `-- name: GetWorkableCrawlIssueByIDForUser :one
SELECT
    ci.id,
    ci.crawl_id,
    ci.crawl_page_id,
    ci.url,
    ci.pillar,
    ci.bucket,
    ci.issue_type,
    ci.issue_group_id,
    p.id AS project_id
FROM crawl_issues AS ci
INNER JOIN crawls AS c ON c.id = ci.crawl_id
INNER JOIN projects AS p ON p.id = c.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE ci.id = $1
  AND om.user_id = $2
  AND c.status = 'completed'
  AND c.id = (
      SELECT latest.id FROM crawls AS latest
      WHERE latest.project_id = c.project_id AND latest.status = 'completed'
      ORDER BY latest.completed_at DESC NULLS LAST, latest.created_at DESC, latest.id DESC
      LIMIT 1
  )
LIMIT 1
`

type GetWorkableCrawlIssueByIDForUserParams struct {
	IssueID pgtype.UUID
	UserID  pgtype.UUID
}

type GetWorkableCrawlIssueByIDForUserRow struct {
	ID           pgtype.UUID
	CrawlID      pgtype.UUID
	CrawlPageID  pgtype.UUID
	Url          string
	Pillar       string
	Bucket       string
	IssueType    string
	IssueGroupID pgtype.UUID
	ProjectID    pgtype.UUID
}

func (q *Queries) GetWorkableCrawlIssueByIDForUser(ctx context.Context, arg GetWorkableCrawlIssueByIDForUserParams) (GetWorkableCrawlIssueByIDForUserRow, error) {
	row := q.db.QueryRow(ctx, getWorkableCrawlIssueByIDForUser, arg.IssueID, arg.UserID)
	var i GetWorkableCrawlIssueByIDForUserRow
	err := row.Scan(
		&i.ID,
		&i.CrawlID,
		&i.CrawlPageID,
		&i.Url,
		&i.Pillar,
		&i.Bucket,
		&i.IssueType,
		&i.IssueGroupID,
		&i.ProjectID,
	)
	return i, err
}

const listIssueWorkAttemptContributors = `-- name: ListIssueWorkAttemptContributors :many
SELECT attempt_id, user_id, marked_done_at
FROM issue_work_attempt_contributors
WHERE attempt_id = $1
ORDER BY marked_done_at ASC
`

func (q *Queries) ListIssueWorkAttemptContributors(ctx context.Context, attemptID pgtype.UUID) ([]IssueWorkAttemptContributor, error) {
	rows, err := q.db.Query(ctx, listIssueWorkAttemptContributors, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueWorkAttemptContributor
	for rows.Next() {
		var i IssueWorkAttemptContributor
		if err := rows.Scan(&i.AttemptID, &i.UserID, &i.MarkedDoneAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueWorkAttemptsForVerification = `-- name: ListIssueWorkAttemptsForVerification :many
SELECT
    wa.id AS attempt_id,
    wa.work_item_id,
    wa.source_crawl_id,
    wi.subject_kind,
    wi.subject_key,
    wi.pillar,
    wi.bucket,
    wi.issue_type,
    wi.source_issue_group_id
FROM issue_work_attempts AS wa
INNER JOIN issue_work_items AS wi ON wi.id = wa.work_item_id
INNER JOIN crawls AS c ON c.id = $1
WHERE wi.project_id = c.project_id
  AND wa.verification_crawl_id = c.id
  AND (wa.source_crawl_id IS NULL OR wa.source_crawl_id <> c.id)
  AND wa.status IN ('awaiting_verification', 'not_verified')
  AND wa.locked_at IS NOT NULL
ORDER BY wa.created_at, wa.id
`

type ListIssueWorkAttemptsForVerificationRow struct {
	AttemptID          pgtype.UUID
	WorkItemID         pgtype.UUID
	SourceCrawlID      pgtype.UUID
	SubjectKind        string
	SubjectKey         string
	Pillar             string
	Bucket             string
	IssueType          string
	SourceIssueGroupID pgtype.UUID
}

func (q *Queries) ListIssueWorkAttemptsForVerification(ctx context.Context, crawlID pgtype.UUID) ([]ListIssueWorkAttemptsForVerificationRow, error) {
	rows, err := q.db.Query(ctx, listIssueWorkAttemptsForVerification, crawlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueWorkAttemptsForVerificationRow
	for rows.Next() {
		var i ListIssueWorkAttemptsForVerificationRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.WorkItemID,
			&i.SourceCrawlID,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.SourceIssueGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueWorkspaceDiff = `-- name: ListIssueWorkspaceDiff :many
WITH baseline AS (
    SELECT ci.id, ci.url, ci.pillar, ci.bucket, ci.issue_type, ci.severity, ci.message, ci.details, ci.issue_group_id
    FROM crawl_issues ci
    JOIN crawls c ON c.id = ci.crawl_id
    JOIN projects p ON p.id = c.project_id
    JOIN organization_members om ON om.org_id = p.organization_id
    WHERE ci.crawl_id = $2
      AND om.user_id = $3
      AND ($4::text = '' OR ci.url = $4)
), current AS (
    SELECT ci.id, ci.url, ci.pillar, ci.bucket, ci.issue_type, ci.severity, ci.message, ci.details, ci.issue_group_id
    FROM crawl_issues ci
    JOIN crawls c ON c.id = ci.crawl_id
    JOIN projects p ON p.id = c.project_id
    JOIN organization_members om ON om.org_id = p.organization_id
    WHERE ci.crawl_id = $1
      AND om.user_id = $3
      AND ($4::text = '' OR ci.url = $4)
), identities AS (
    SELECT url, pillar, bucket, issue_type FROM baseline
    UNION
    SELECT url, pillar, bucket, issue_type FROM current
)
SELECT
    i.url AS url,
    i.pillar AS pillar,
    i.bucket AS bucket,
    i.issue_type AS issue_type,
    COALESCE(cur.severity, base.severity, '')::text AS severity,
    COALESCE(cur.message, base.message, '')::text AS message,
    COALESCE(cur.details, base.details, '')::text AS details,
    COALESCE(base.id::text, ''::text)::text AS baseline_issue_id,
    COALESCE(cur.id::text, ''::text)::text AS current_issue_id,
    CASE
        WHEN base.id IS NULL THEN 'new'
        WHEN cur.id IS NOT NULL THEN 'still_open'
        WHEN cp.id IS NULL OR cp.fetch_error IS NOT NULL OR cp.soft_404 OR cp.status_code NOT BETWEEN 200 AND 299 THEN 'not_verified'
        WHEN i.bucket = 'psi_cwv' AND NOT EXISTS (SELECT 1 FROM crawls evidence_crawl WHERE evidence_crawl.id = $1 AND COALESCE(evidence_crawl.google_psi_results #>> '{0,mobile,success}', 'false') = 'true') THEN 'not_verified'
        WHEN i.issue_type IN ('weak_open_graph_coverage', 'missing_website_schema', 'missing_org_identity_schema', 'missing_about_page', 'missing_contact_page', 'missing_policy_page', 'missing_llms_txt', 'homepage_missing_org_contact_trust_signals') AND EXISTS (
            SELECT 1 FROM crawl_pages baseline_coverage
            WHERE baseline_coverage.crawl_id = $2 AND baseline_coverage.fetch_error IS NULL AND baseline_coverage.soft_404 = FALSE AND baseline_coverage.status_code BETWEEN 200 AND 299
              AND NOT EXISTS (SELECT 1 FROM crawl_pages current_coverage WHERE current_coverage.crawl_id = $1 AND current_coverage.url = baseline_coverage.url AND current_coverage.fetch_error IS NULL AND current_coverage.soft_404 = FALSE AND current_coverage.status_code BETWEEN 200 AND 299)
        ) THEN 'not_verified'
        WHEN base.issue_group_id IS NOT NULL AND EXISTS (
            SELECT 1 FROM crawl_issue_group_members original_member
            WHERE original_member.group_id = base.issue_group_id
              AND NOT EXISTS (
                  SELECT 1 FROM crawl_pages member_page
                  WHERE member_page.crawl_id = $1
                    AND member_page.url = original_member.url
                    AND member_page.fetch_error IS NULL
                    AND member_page.soft_404 = FALSE
                    AND member_page.status_code BETWEEN 200 AND 299
              )
        ) THEN 'not_verified'
        ELSE 'no_longer_detected'
    END::text AS change_type,
    (cp.id IS NOT NULL AND cp.fetch_error IS NULL AND NOT cp.soft_404 AND cp.status_code BETWEEN 200 AND 299)::boolean AS current_page_seen
FROM identities i
LEFT JOIN baseline base USING (url, pillar, bucket, issue_type)
LEFT JOIN current cur USING (url, pillar, bucket, issue_type)
LEFT JOIN crawl_pages cp ON cp.crawl_id = $1 AND cp.url = i.url
ORDER BY i.url, i.pillar, i.bucket, i.issue_type
`

type ListIssueWorkspaceDiffParams struct {
	CurrentID  pgtype.UUID
	BaselineID pgtype.UUID
	UserID     pgtype.UUID
	UrlFilter  string
}

type ListIssueWorkspaceDiffRow struct {
	Url             string
	Pillar          string
	Bucket          string
	IssueType       string
	Severity        string
	Message         string
	Details         string
	BaselineIssueID string
	CurrentIssueID  string
	ChangeType      string
	CurrentPageSeen bool
}

func (q *Queries) ListIssueWorkspaceDiff(ctx context.Context, arg ListIssueWorkspaceDiffParams) ([]ListIssueWorkspaceDiffRow, error) {
	rows, err := q.db.Query(ctx, listIssueWorkspaceDiff,
		arg.CurrentID,
		arg.BaselineID,
		arg.UserID,
		arg.UrlFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueWorkspaceDiffRow
	for rows.Next() {
		var i ListIssueWorkspaceDiffRow
		if err := rows.Scan(
			&i.Url,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.Severity,
			&i.Message,
			&i.Details,
			&i.BaselineIssueID,
			&i.CurrentIssueID,
			&i.ChangeType,
			&i.CurrentPageSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueWorkspaceWork = `-- name: ListIssueWorkspaceWork :many
SELECT
    wi.id::text AS work_item_id,
    attempt.id::text AS attempt_id,
    COALESCE(member.url, wi.subject_key)::text AS url,
    wi.subject_kind AS subject_kind,
    wi.pillar AS pillar,
    wi.bucket AS bucket,
    wi.issue_type AS issue_type,
    attempt.status AS status,
    COALESCE(attempt.verification_crawl_id::text, ''::text)::text AS verification_crawl_id,
    COALESCE(array_agg(contributor.user_id::text) FILTER (WHERE contributor.user_id IS NOT NULL), ARRAY[]::text[])::text[] AS contributors
FROM issue_work_items wi
JOIN crawls current_crawl ON current_crawl.id = $1 AND current_crawl.project_id = wi.project_id
JOIN LATERAL (
    SELECT wa.id, wa.work_item_id, wa.source_crawl_id, wa.status, wa.verification_crawl_id, wa.created_at, wa.locked_at, wa.verified_at FROM issue_work_attempts wa
    WHERE wa.work_item_id = wi.id ORDER BY wa.created_at DESC, wa.id DESC LIMIT 1
) attempt ON TRUE
LEFT JOIN crawl_issue_group_members member ON wi.subject_kind = 'group' AND member.group_id = wi.source_issue_group_id
LEFT JOIN issue_work_attempt_contributors contributor ON contributor.attempt_id = attempt.id
WHERE (attempt.verification_crawl_id = $1 OR (
    attempt.status IN ('awaiting_verification', 'not_verified') AND current_crawl.id = (
        SELECT latest.id FROM crawls latest
        WHERE latest.project_id = current_crawl.project_id AND latest.status = 'completed'
        ORDER BY latest.completed_at DESC NULLS LAST, latest.created_at DESC, latest.id DESC LIMIT 1
    )
))
  AND ($2::text = '' OR COALESCE(member.url, wi.subject_key) = $2)
GROUP BY wi.id, attempt.id, attempt.status, attempt.verification_crawl_id, member.url
ORDER BY COALESCE(member.url, wi.subject_key), wi.pillar, wi.bucket, wi.issue_type
`

type ListIssueWorkspaceWorkParams struct {
	CurrentID pgtype.UUID
	UrlFilter string
}

type ListIssueWorkspaceWorkRow struct {
	WorkItemID          string
	AttemptID           string
	Url                 string
	SubjectKind         string
	Pillar              string
	Bucket              string
	IssueType           string
	Status              string
	VerificationCrawlID string
	Contributors        []string
}

func (q *Queries) ListIssueWorkspaceWork(ctx context.Context, arg ListIssueWorkspaceWorkParams) ([]ListIssueWorkspaceWorkRow, error) {
	rows, err := q.db.Query(ctx, listIssueWorkspaceWork, arg.CurrentID, arg.UrlFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueWorkspaceWorkRow
	for rows.Next() {
		var i ListIssueWorkspaceWorkRow
		if err := rows.Scan(
			&i.WorkItemID,
			&i.AttemptID,
			&i.Url,
			&i.SubjectKind,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.Status,
			&i.VerificationCrawlID,
			&i.Contributors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedIssueWorkAttemptsForProject = `-- name: ListVerifiedIssueWorkAttemptsForProject :many
SELECT
    wa.id AS attempt_id,
    wa.status,
    wa.verified_at,
    wa.verification_crawl_id,
    wi.id AS work_item_id,
    wi.subject_kind,
    wi.subject_key,
    wi.pillar,
    wi.bucket,
    wi.issue_type,
    COALESCE(array_agg(DISTINCT u.email) FILTER (WHERE u.id IS NOT NULL), ARRAY[]::text[])::text[] AS contributor_emails
FROM issue_work_attempts AS wa
INNER JOIN issue_work_items AS wi ON wi.id = wa.work_item_id
LEFT JOIN crawls AS vc ON vc.id = wa.verification_crawl_id
LEFT JOIN issue_work_attempt_contributors AS wc ON wc.attempt_id = wa.id
LEFT JOIN users AS u ON u.id = wc.user_id
WHERE wi.project_id = $1
  AND wa.status = 'fixed'
  AND wa.verified_at >= $2
  AND wa.verified_at < $3
  AND (
    $4::uuid IS NULL
    OR EXISTS (
        SELECT 1 FROM issue_work_attempt_contributors AS f
        WHERE f.attempt_id = wa.id AND f.user_id = $4
    )
  )
GROUP BY wa.id, wi.id
ORDER BY wa.verified_at DESC
`

type ListVerifiedIssueWorkAttemptsForProjectParams struct {
	ProjectID pgtype.UUID
	From      pgtype.Timestamptz
	To        pgtype.Timestamptz
	UserID    pgtype.UUID
}

type ListVerifiedIssueWorkAttemptsForProjectRow struct {
	AttemptID           pgtype.UUID
	Status              string
	VerifiedAt          pgtype.Timestamptz
	VerificationCrawlID pgtype.UUID
	WorkItemID          pgtype.UUID
	SubjectKind         string
	SubjectKey          string
	Pillar              string
	Bucket              string
	IssueType           string
	ContributorEmails   []string
}

func (q *Queries) ListVerifiedIssueWorkAttemptsForProject(ctx context.Context, arg ListVerifiedIssueWorkAttemptsForProjectParams) ([]ListVerifiedIssueWorkAttemptsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedIssueWorkAttemptsForProject,
		arg.ProjectID,
		arg.From,
		arg.To,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedIssueWorkAttemptsForProjectRow
	for rows.Next() {
		var i ListVerifiedIssueWorkAttemptsForProjectRow
		if err := rows.Scan(
			&i.AttemptID,
			&i.Status,
			&i.VerifiedAt,
			&i.VerificationCrawlID,
			&i.WorkItemID,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.ContributorEmails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIssueWorkAttemptsForCrawlStart = `-- name: LockIssueWorkAttemptsForCrawlStart :many
UPDATE issue_work_attempts AS wa
SET locked_at = now(), verification_crawl_id = c.id
FROM issue_work_items AS wi, crawls AS c
WHERE wi.id = wa.work_item_id
  AND c.id = $1
  AND wi.project_id = c.project_id
  AND wa.status IN ('awaiting_verification', 'not_verified')
  AND wa.locked_at IS NULL
  AND wa.created_at <= COALESCE(c.started_at, now())
RETURNING wa.id
`

func (q *Queries) LockIssueWorkAttemptsForCrawlStart(ctx context.Context, id pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, lockIssueWorkAttemptsForCrawlStart, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readIssueWorkItems = `-- name: ReadIssueWorkItems :many
SELECT
    wi.id AS id,
    wi.subject_kind AS subject_kind,
    COALESCE(member.url, wi.subject_key)::text AS subject_key,
    wi.pillar AS pillar,
    wi.bucket AS bucket,
    wi.issue_type AS issue_type,
    wi.status AS item_status,
    COALESCE(latest_attempt.status, ''::text)::text AS attempt_status,
    (SELECT COUNT(*)::bigint FROM issue_work_attempts wa WHERE wa.work_item_id = wi.id) AS attempt_count,
    latest_attempt.verified_at AS verified_at,
    wi.created_at AS item_created_at,
    wi.updated_at AS item_updated_at,
    latest_attempt.created_at AS attempt_created_at,
    COALESCE(array_agg(DISTINCT u.email) FILTER (WHERE u.id IS NOT NULL), ARRAY[]::text[])::text[] AS contributor_emails
FROM issue_work_items wi
LEFT JOIN LATERAL (
    SELECT wa.id, wa.work_item_id, wa.source_crawl_id, wa.status, wa.verification_crawl_id, wa.created_at, wa.locked_at, wa.verified_at FROM issue_work_attempts wa WHERE wa.work_item_id = wi.id ORDER BY wa.created_at DESC, wa.id DESC LIMIT 1
) latest_attempt ON TRUE
LEFT JOIN LATERAL (
    SELECT m.url
    FROM crawl_issue_group_members m
    WHERE wi.subject_kind = 'group' AND m.group_id = wi.source_issue_group_id
    ORDER BY m.url
    LIMIT 1
) member ON TRUE
LEFT JOIN issue_work_attempt_contributors wc ON wc.attempt_id = latest_attempt.id
LEFT JOIN users u ON u.id = wc.user_id
WHERE wi.project_id = $1
  AND ($2::text = '' OR wi.pillar = $2)
  AND ($3::text = '' OR wi.bucket = $3)
  AND ($4::text = '' OR wi.issue_type = $4)
GROUP BY wi.id, latest_attempt.id, latest_attempt.status, latest_attempt.verified_at, latest_attempt.created_at, member.url
ORDER BY wi.updated_at DESC, wi.id
`

type ReadIssueWorkItemsParams struct {
	ProjectID pgtype.UUID
	Pillar    string
	Bucket    string
	IssueType string
}

type ReadIssueWorkItemsRow struct {
	ID                pgtype.UUID
	SubjectKind       string
	SubjectKey        string
	Pillar            string
	Bucket            string
	IssueType         string
	ItemStatus        string
	AttemptStatus     string
	AttemptCount      int64
	VerifiedAt        pgtype.Timestamptz
	ItemCreatedAt     pgtype.Timestamptz
	ItemUpdatedAt     pgtype.Timestamptz
	AttemptCreatedAt  pgtype.Timestamptz
	ContributorEmails []string
}

func (q *Queries) ReadIssueWorkItems(ctx context.Context, arg ReadIssueWorkItemsParams) ([]ReadIssueWorkItemsRow, error) {
	rows, err := q.db.Query(ctx, readIssueWorkItems,
		arg.ProjectID,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadIssueWorkItemsRow
	for rows.Next() {
		var i ReadIssueWorkItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SubjectKind,
			&i.SubjectKey,
			&i.Pillar,
			&i.Bucket,
			&i.IssueType,
			&i.ItemStatus,
			&i.AttemptStatus,
			&i.AttemptCount,
			&i.VerifiedAt,
			&i.ItemCreatedAt,
			&i.ItemUpdatedAt,
			&i.AttemptCreatedAt,
			&i.ContributorEmails,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseIssueWorkAttemptsForFailedCrawl = `-- name: ReleaseIssueWorkAttemptsForFailedCrawl :exec
UPDATE issue_work_attempts
SET locked_at = NULL, verification_crawl_id = NULL
WHERE verification_crawl_id = $1
  AND status IN ('awaiting_verification', 'not_verified')
`

func (q *Queries) ReleaseIssueWorkAttemptsForFailedCrawl(ctx context.Context, verificationCrawlID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, releaseIssueWorkAttemptsForFailedCrawl, verificationCrawlID)
	return err
}

const removeIssueWorkAttemptContributor = `-- name: RemoveIssueWorkAttemptContributor :execrows
DELETE FROM issue_work_attempt_contributors AS contributor
USING issue_work_attempts AS attempt
WHERE contributor.attempt_id = $1
  AND contributor.user_id = $2
  AND attempt.id = contributor.attempt_id
  AND attempt.locked_at IS NULL
  AND attempt.status IN ('awaiting_verification', 'not_verified')
`

type RemoveIssueWorkAttemptContributorParams struct {
	AttemptID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) RemoveIssueWorkAttemptContributor(ctx context.Context, arg RemoveIssueWorkAttemptContributorParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeIssueWorkAttemptContributor, arg.AttemptID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIssueWorkAttemptVerification = `-- name: UpdateIssueWorkAttemptVerification :exec
UPDATE issue_work_attempts
SET status = $1,
    verification_crawl_id = $2,
    verified_at = now(),
    locked_at = CASE WHEN $1::text = 'not_verified' THEN NULL ELSE locked_at END
WHERE id = $3
`

type UpdateIssueWorkAttemptVerificationParams struct {
	Status              string
	VerificationCrawlID pgtype.UUID
	AttemptID           pgtype.UUID
}

func (q *Queries) UpdateIssueWorkAttemptVerification(ctx context.Context, arg UpdateIssueWorkAttemptVerificationParams) error {
	_, err := q.db.Exec(ctx, updateIssueWorkAttemptVerification, arg.Status, arg.VerificationCrawlID, arg.AttemptID)
	return err
}

const updateIssueWorkItemStatus = `-- name: UpdateIssueWorkItemStatus :exec
UPDATE issue_work_items
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateIssueWorkItemStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateIssueWorkItemStatus(ctx context.Context, arg UpdateIssueWorkItemStatusParams) error {
	_, err := q.db.Exec(ctx, updateIssueWorkItemStatus, arg.ID, arg.Status)
	return err
}

const updateIssueWorkItemStatusAfterVerification = `-- name: UpdateIssueWorkItemStatusAfterVerification :exec
UPDATE issue_work_items AS item
SET status = CASE WHEN EXISTS (
        SELECT 1 FROM issue_work_attempts AS newer
        WHERE newer.work_item_id = item.id
          AND newer.id <> $1
          AND newer.status IN ('awaiting_verification', 'not_verified')
    ) THEN 'awaiting_verification' ELSE $2::text END,
    updated_at = now()
WHERE item.id = $3
`

type UpdateIssueWorkItemStatusAfterVerificationParams struct {
	AttemptID  pgtype.UUID
	Status     string
	WorkItemID pgtype.UUID
}

func (q *Queries) UpdateIssueWorkItemStatusAfterVerification(ctx context.Context, arg UpdateIssueWorkItemStatusAfterVerificationParams) error {
	_, err := q.db.Exec(ctx, updateIssueWorkItemStatusAfterVerification, arg.AttemptID, arg.Status, arg.WorkItemID)
	return err
}

const upsertIssueWorkItem = `-- name: UpsertIssueWorkItem :one
INSERT INTO issue_work_items (
    project_id,
    subject_kind,
    subject_key,
    pillar,
    bucket,
    issue_type,
    source_crawl_issue_id,
    source_issue_group_id
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
ON CONFLICT (project_id, subject_kind, subject_key, pillar, bucket, issue_type)
DO UPDATE SET
    source_crawl_issue_id = EXCLUDED.source_crawl_issue_id,
    source_issue_group_id = EXCLUDED.source_issue_group_id,
    updated_at = now()
RETURNING id, project_id, subject_kind, subject_key, pillar, bucket, issue_type, source_crawl_issue_id, status, created_at, updated_at, source_issue_group_id
`

type UpsertIssueWorkItemParams struct {
	ProjectID          pgtype.UUID
	SubjectKind        string
	SubjectKey         string
	Pillar             string
	Bucket             string
	IssueType          string
	SourceCrawlIssueID pgtype.UUID
	SourceIssueGroupID pgtype.UUID
}

func (q *Queries) UpsertIssueWorkItem(ctx context.Context, arg UpsertIssueWorkItemParams) (IssueWorkItem, error) {
	row := q.db.QueryRow(ctx, upsertIssueWorkItem,
		arg.ProjectID,
		arg.SubjectKind,
		arg.SubjectKey,
		arg.Pillar,
		arg.Bucket,
		arg.IssueType,
		arg.SourceCrawlIssueID,
		arg.SourceIssueGroupID,
	)
	var i IssueWorkItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SubjectKind,
		&i.SubjectKey,
		&i.Pillar,
		&i.Bucket,
		&i.IssueType,
		&i.SourceCrawlIssueID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceIssueGroupID,
	)
	return i, err
}
