// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location_workspace.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestLocationWebsiteScopeRevision = `-- name: GetLatestLocationWebsiteScopeRevision :one
SELECT id, revision, url, match, created_at
    FROM location_website_scopes WHERE location_id = $1 ORDER BY revision DESC LIMIT 1
`

type GetLatestLocationWebsiteScopeRevisionRow struct {
	ID        pgtype.UUID
	Revision  int32
	Url       pgtype.Text
	Match     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetLatestLocationWebsiteScopeRevision(ctx context.Context, locationID pgtype.UUID) (GetLatestLocationWebsiteScopeRevisionRow, error) {
	row := q.db.QueryRow(ctx, getLatestLocationWebsiteScopeRevision, locationID)
	var i GetLatestLocationWebsiteScopeRevisionRow
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Url,
		&i.Match,
		&i.CreatedAt,
	)
	return i, err
}

const getLocationBusinessProfile = `-- name: GetLocationBusinessProfile :one
SELECT id, project_id, location_id, brand_name, website_url,
    primary_category, primary_location, business_description, product_description,
    target_audience, business_competitors, seed_prompts, services, created_at, updated_at
FROM location_business_profiles WHERE project_id = $1 AND location_id = $2 LIMIT 1
`

type GetLocationBusinessProfileParams struct {
	ProjectID  pgtype.UUID
	LocationID pgtype.UUID
}

func (q *Queries) GetLocationBusinessProfile(ctx context.Context, arg GetLocationBusinessProfileParams) (LocationBusinessProfile, error) {
	row := q.db.QueryRow(ctx, getLocationBusinessProfile, arg.ProjectID, arg.LocationID)
	var i LocationBusinessProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LocationID,
		&i.BrandName,
		&i.WebsiteUrl,
		&i.PrimaryCategory,
		&i.PrimaryLocation,
		&i.BusinessDescription,
		&i.ProductDescription,
		&i.TargetAudience,
		&i.BusinessCompetitors,
		&i.SeedPrompts,
		&i.Services,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLocationWebsiteScopeRevision = `-- name: InsertLocationWebsiteScopeRevision :one
INSERT INTO location_website_scopes
    (project_id, location_id, revision, url, match)
    SELECT $1, $2, COALESCE((SELECT MAX(revision) FROM location_website_scopes WHERE location_id = $2), 0) + 1, $3, $4
    RETURNING id, revision, created_at
`

type InsertLocationWebsiteScopeRevisionParams struct {
	ProjectID  pgtype.UUID
	LocationID pgtype.UUID
	Url        pgtype.Text
	Match      string
}

type InsertLocationWebsiteScopeRevisionRow struct {
	ID        pgtype.UUID
	Revision  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertLocationWebsiteScopeRevision(ctx context.Context, arg InsertLocationWebsiteScopeRevisionParams) (InsertLocationWebsiteScopeRevisionRow, error) {
	row := q.db.QueryRow(ctx, insertLocationWebsiteScopeRevision,
		arg.ProjectID,
		arg.LocationID,
		arg.Url,
		arg.Match,
	)
	var i InsertLocationWebsiteScopeRevisionRow
	err := row.Scan(&i.ID, &i.Revision, &i.CreatedAt)
	return i, err
}

const listLocationWebsiteScopeRevisions = `-- name: ListLocationWebsiteScopeRevisions :many
SELECT id, revision, url, match, created_at
    FROM location_website_scopes WHERE location_id = $1 ORDER BY revision DESC
`

type ListLocationWebsiteScopeRevisionsRow struct {
	ID        pgtype.UUID
	Revision  int32
	Url       pgtype.Text
	Match     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListLocationWebsiteScopeRevisions(ctx context.Context, locationID pgtype.UUID) ([]ListLocationWebsiteScopeRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listLocationWebsiteScopeRevisions, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationWebsiteScopeRevisionsRow
	for rows.Next() {
		var i ListLocationWebsiteScopeRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.Url,
			&i.Match,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocationBusinessProfile = `-- name: UpsertLocationBusinessProfile :one
INSERT INTO location_business_profiles
    (project_id, location_id, brand_name, website_url, primary_category, primary_location,
    business_description, product_description, target_audience, business_competitors, seed_prompts, services)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, COALESCE($12, '[]'::jsonb))
    ON CONFLICT (location_id) DO UPDATE SET
    brand_name = excluded.brand_name, website_url = excluded.website_url,
    primary_category = excluded.primary_category, primary_location = excluded.primary_location,
    business_description = excluded.business_description,
    product_description = excluded.product_description,
    target_audience = excluded.target_audience,
    business_competitors = excluded.business_competitors,
    seed_prompts = excluded.seed_prompts,
    services = CASE WHEN $12 IS NULL THEN location_business_profiles.services ELSE excluded.services END,
    updated_at = now()
    RETURNING id, project_id, location_id, brand_name, website_url,
    primary_category, primary_location, business_description, product_description,
    target_audience, business_competitors, seed_prompts, services, created_at, updated_at
`

type UpsertLocationBusinessProfileParams struct {
	ProjectID           pgtype.UUID
	LocationID          pgtype.UUID
	BrandName           string
	WebsiteUrl          string
	PrimaryCategory     pgtype.Text
	PrimaryLocation     pgtype.Text
	BusinessDescription pgtype.Text
	ProductDescription  pgtype.Text
	TargetAudience      pgtype.Text
	BusinessCompetitors []byte
	SeedPrompts         []byte
	Column12            interface{}
}

func (q *Queries) UpsertLocationBusinessProfile(ctx context.Context, arg UpsertLocationBusinessProfileParams) (LocationBusinessProfile, error) {
	row := q.db.QueryRow(ctx, upsertLocationBusinessProfile,
		arg.ProjectID,
		arg.LocationID,
		arg.BrandName,
		arg.WebsiteUrl,
		arg.PrimaryCategory,
		arg.PrimaryLocation,
		arg.BusinessDescription,
		arg.ProductDescription,
		arg.TargetAudience,
		arg.BusinessCompetitors,
		arg.SeedPrompts,
		arg.Column12,
	)
	var i LocationBusinessProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LocationID,
		&i.BrandName,
		&i.WebsiteUrl,
		&i.PrimaryCategory,
		&i.PrimaryLocation,
		&i.BusinessDescription,
		&i.ProductDescription,
		&i.TargetAudience,
		&i.BusinessCompetitors,
		&i.SeedPrompts,
		&i.Services,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
