// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: local_visibility.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLocalVisibilityRunResultsForUser = `-- name: CountLocalVisibilityRunResultsForUser :one
SELECT COUNT(*)::bigint FROM local_visibility_results res
JOIN local_visibility_runs r ON r.id = res.run_id
JOIN project_locations l ON l.id = r.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE res.run_id = $1 AND l.id = $2 AND p.id = $3 AND m.user_id = $4
`

type CountLocalVisibilityRunResultsForUserParams struct {
	RunID  pgtype.UUID
	ID     pgtype.UUID
	ID_2   pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) CountLocalVisibilityRunResultsForUser(ctx context.Context, arg CountLocalVisibilityRunResultsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLocalVisibilityRunResultsForUser,
		arg.RunID,
		arg.ID,
		arg.ID_2,
		arg.UserID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createLocalRunCells = `-- name: CreateLocalRunCells :exec
INSERT INTO local_run_cells(run_id,query_index,point_index)
SELECT $1, q::smallint, p::smallint
FROM generate_series(0,$2::integer-1) q,
generate_series(0,$3::integer-1) p
`

type CreateLocalRunCellsParams struct {
	RunID      pgtype.UUID
	QueryCount int32
	PointCount int32
}

func (q *Queries) CreateLocalRunCells(ctx context.Context, arg CreateLocalRunCellsParams) error {
	_, err := q.db.Exec(ctx, createLocalRunCells, arg.RunID, arg.QueryCount, arg.PointCount)
	return err
}

const createLocalVisibilityRun = `-- name: CreateLocalVisibilityRun :one
INSERT INTO local_visibility_runs(location_id,radius_m,snapshot,expected_credits,reserved_credits)
VALUES($1,$2,$3,$4,$4) RETURNING id, location_id, status, radius_m, snapshot, expected_credits, reserved_credits, credits_used, retry_credits, error, created_at, started_at, completed_at
`

type CreateLocalVisibilityRunParams struct {
	LocationID      pgtype.UUID
	RadiusM         int32
	Snapshot        []byte
	ExpectedCredits int32
}

func (q *Queries) CreateLocalVisibilityRun(ctx context.Context, arg CreateLocalVisibilityRunParams) (LocalVisibilityRun, error) {
	row := q.db.QueryRow(ctx, createLocalVisibilityRun,
		arg.LocationID,
		arg.RadiusM,
		arg.Snapshot,
		arg.ExpectedCredits,
	)
	var i LocalVisibilityRun
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Status,
		&i.RadiusM,
		&i.Snapshot,
		&i.ExpectedCredits,
		&i.ReservedCredits,
		&i.CreditsUsed,
		&i.RetryCredits,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const enqueueLocalVisibilityJob = `-- name: EnqueueLocalVisibilityJob :one
INSERT INTO ai_worker_jobs(job_type,project_id,local_run_id,status)
VALUES('local_visibility',$1,$2,'pending') RETURNING id
`

type EnqueueLocalVisibilityJobParams struct {
	ProjectID  pgtype.UUID
	LocalRunID pgtype.UUID
}

func (q *Queries) EnqueueLocalVisibilityJob(ctx context.Context, arg EnqueueLocalVisibilityJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueLocalVisibilityJob, arg.ProjectID, arg.LocalRunID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const finishLocalVisibilityRun = `-- name: FinishLocalVisibilityRun :exec
UPDATE local_visibility_runs SET status = $2,error = $3,completed_at = now() WHERE id = $1
`

type FinishLocalVisibilityRunParams struct {
	ID     pgtype.UUID
	Status string
	Error  pgtype.Text
}

func (q *Queries) FinishLocalVisibilityRun(ctx context.Context, arg FinishLocalVisibilityRunParams) error {
	_, err := q.db.Exec(ctx, finishLocalVisibilityRun, arg.ID, arg.Status, arg.Error)
	return err
}

const getLatestLocalVisibilityRunForUser = `-- name: GetLatestLocalVisibilityRunForUser :one
SELECT r.id, r.location_id, r.status, r.radius_m, r.snapshot, r.expected_credits, r.reserved_credits, r.credits_used, r.retry_credits, r.error, r.created_at, r.started_at, r.completed_at FROM local_visibility_runs r
JOIN project_locations l ON l.id = r.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $1 AND p.id = $2 AND m.user_id = $3
ORDER BY r.created_at DESC, r.id DESC LIMIT 1
`

type GetLatestLocalVisibilityRunForUserParams struct {
	ID     pgtype.UUID
	ID_2   pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetLatestLocalVisibilityRunForUser(ctx context.Context, arg GetLatestLocalVisibilityRunForUserParams) (LocalVisibilityRun, error) {
	row := q.db.QueryRow(ctx, getLatestLocalVisibilityRunForUser, arg.ID, arg.ID_2, arg.UserID)
	var i LocalVisibilityRun
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Status,
		&i.RadiusM,
		&i.Snapshot,
		&i.ExpectedCredits,
		&i.ReservedCredits,
		&i.CreditsUsed,
		&i.RetryCredits,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLocalRunCells = `-- name: GetLocalRunCells :many
SELECT c.query_index,c.point_index,c.started_at,
COALESCE(r.call_status,'pending')::text AS call_status,
COALESCE(r.match_status,'unknown')::text AS match_status,
r.rank,COALESCE(r.credits,0)::integer AS credits,
COALESCE(r.credit_known,FALSE)::boolean AS credit_known,r.error,
COALESCE(r.raw_response->>'ll','')::text AS echoed_ll,
COALESCE((r.raw_response->>'viewport_drift_m')::double precision,-1)::double precision AS viewport_drift_m
FROM local_run_cells c LEFT JOIN local_visibility_results r
ON r.run_id = c.run_id AND r.query_index = c.query_index AND r.point_index = c.point_index
WHERE c.run_id = $1 ORDER BY c.query_index,c.point_index
`

type GetLocalRunCellsRow struct {
	QueryIndex     int16
	PointIndex     int16
	StartedAt      pgtype.Timestamptz
	CallStatus     string
	MatchStatus    string
	Rank           pgtype.Int4
	Credits        int32
	CreditKnown    bool
	Error          pgtype.Text
	EchoedLl       string
	ViewportDriftM float64
}

func (q *Queries) GetLocalRunCells(ctx context.Context, runID pgtype.UUID) ([]GetLocalRunCellsRow, error) {
	rows, err := q.db.Query(ctx, getLocalRunCells, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocalRunCellsRow
	for rows.Next() {
		var i GetLocalRunCellsRow
		if err := rows.Scan(
			&i.QueryIndex,
			&i.PointIndex,
			&i.StartedAt,
			&i.CallStatus,
			&i.MatchStatus,
			&i.Rank,
			&i.Credits,
			&i.CreditKnown,
			&i.Error,
			&i.EchoedLl,
			&i.ViewportDriftM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocalVisibilityRun = `-- name: GetLocalVisibilityRun :one
SELECT r.id, r.location_id, r.status, r.radius_m, r.snapshot, r.expected_credits, r.reserved_credits, r.credits_used, r.retry_credits, r.error, r.created_at, r.started_at, r.completed_at,p.organization_id,l.project_id FROM local_visibility_runs r
JOIN project_locations l ON l.id = r.location_id
JOIN projects p ON p.id = l.project_id
WHERE r.id = $1
`

type GetLocalVisibilityRunRow struct {
	ID              pgtype.UUID
	LocationID      pgtype.UUID
	Status          string
	RadiusM         int32
	Snapshot        []byte
	ExpectedCredits int32
	ReservedCredits int32
	CreditsUsed     int32
	RetryCredits    int32
	Error           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	OrganizationID  pgtype.UUID
	ProjectID       pgtype.UUID
}

func (q *Queries) GetLocalVisibilityRun(ctx context.Context, id pgtype.UUID) (GetLocalVisibilityRunRow, error) {
	row := q.db.QueryRow(ctx, getLocalVisibilityRun, id)
	var i GetLocalVisibilityRunRow
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Status,
		&i.RadiusM,
		&i.Snapshot,
		&i.ExpectedCredits,
		&i.ReservedCredits,
		&i.CreditsUsed,
		&i.RetryCredits,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.OrganizationID,
		&i.ProjectID,
	)
	return i, err
}

const getLocalVisibilityRunForUser = `-- name: GetLocalVisibilityRunForUser :one
SELECT r.id, r.location_id, r.status, r.radius_m, r.snapshot, r.expected_credits, r.reserved_credits, r.credits_used, r.retry_credits, r.error, r.created_at, r.started_at, r.completed_at FROM local_visibility_runs r
JOIN project_locations l ON l.id = r.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE r.id = $1 AND l.id = $2 AND p.id = $3 AND m.user_id = $4
`

type GetLocalVisibilityRunForUserParams struct {
	ID     pgtype.UUID
	ID_2   pgtype.UUID
	ID_3   pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetLocalVisibilityRunForUser(ctx context.Context, arg GetLocalVisibilityRunForUserParams) (LocalVisibilityRun, error) {
	row := q.db.QueryRow(ctx, getLocalVisibilityRunForUser,
		arg.ID,
		arg.ID_2,
		arg.ID_3,
		arg.UserID,
	)
	var i LocalVisibilityRun
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Status,
		&i.RadiusM,
		&i.Snapshot,
		&i.ExpectedCredits,
		&i.ReservedCredits,
		&i.CreditsUsed,
		&i.RetryCredits,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOrganizationMapsCreditBudget = `-- name: GetOrganizationMapsCreditBudget :one
SELECT o.id AS organization_id,COALESCE(b.remaining_credits,0)::bigint AS remaining_credits,
COALESCE(b.reserved_credits,0)::bigint AS reserved_credits,COALESCE(b.spent_credits,0)::bigint AS spent_credits
FROM organizations o LEFT JOIN organization_maps_credit_budgets b ON b.organization_id = o.id
WHERE o.id = $1
`

type GetOrganizationMapsCreditBudgetRow struct {
	OrganizationID   pgtype.UUID
	RemainingCredits int64
	ReservedCredits  int64
	SpentCredits     int64
}

func (q *Queries) GetOrganizationMapsCreditBudget(ctx context.Context, id pgtype.UUID) (GetOrganizationMapsCreditBudgetRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMapsCreditBudget, id)
	var i GetOrganizationMapsCreditBudgetRow
	err := row.Scan(
		&i.OrganizationID,
		&i.RemainingCredits,
		&i.ReservedCredits,
		&i.SpentCredits,
	)
	return i, err
}

const getPlatformMapsCreditBudget = `-- name: GetPlatformMapsCreditBudget :one
SELECT id, remaining_credits, reserved_credits, spent_credits FROM platform_maps_credit_budget WHERE id = TRUE
`

func (q *Queries) GetPlatformMapsCreditBudget(ctx context.Context) (PlatformMapsCreditBudget, error) {
	row := q.db.QueryRow(ctx, getPlatformMapsCreditBudget)
	var i PlatformMapsCreditBudget
	err := row.Scan(
		&i.ID,
		&i.RemainingCredits,
		&i.ReservedCredits,
		&i.SpentCredits,
	)
	return i, err
}

const getProjectLocationForUser = `-- name: GetProjectLocationForUser :one
SELECT l.id, l.project_id, l.name, l.place_id, l.latitude, l.longitude, l.created_at, l.updated_at, l.address, l.locality, l.localities, p.organization_id FROM project_locations l
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $1 AND p.id = $2 AND m.user_id = $3
`

type GetProjectLocationForUserParams struct {
	ID     pgtype.UUID
	ID_2   pgtype.UUID
	UserID pgtype.UUID
}

type GetProjectLocationForUserRow struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	Name           string
	PlaceID        pgtype.Text
	Latitude       float64
	Longitude      float64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Address        string
	Locality       string
	Localities     []byte
	OrganizationID pgtype.UUID
}

func (q *Queries) GetProjectLocationForUser(ctx context.Context, arg GetProjectLocationForUserParams) (GetProjectLocationForUserRow, error) {
	row := q.db.QueryRow(ctx, getProjectLocationForUser, arg.ID, arg.ID_2, arg.UserID)
	var i GetProjectLocationForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.PlaceID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Address,
		&i.Locality,
		&i.Localities,
		&i.OrganizationID,
	)
	return i, err
}

const insertLocalVisibilityResult = `-- name: InsertLocalVisibilityResult :exec
INSERT INTO local_visibility_results(run_id,query_index,point_index,call_status,match_status,rank,credits,credit_known,raw_response,error)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertLocalVisibilityResultParams struct {
	RunID       pgtype.UUID
	QueryIndex  int16
	PointIndex  int16
	CallStatus  string
	MatchStatus string
	Rank        pgtype.Int4
	Credits     int32
	CreditKnown bool
	RawResponse []byte
	Error       pgtype.Text
}

func (q *Queries) InsertLocalVisibilityResult(ctx context.Context, arg InsertLocalVisibilityResultParams) error {
	_, err := q.db.Exec(ctx, insertLocalVisibilityResult,
		arg.RunID,
		arg.QueryIndex,
		arg.PointIndex,
		arg.CallStatus,
		arg.MatchStatus,
		arg.Rank,
		arg.Credits,
		arg.CreditKnown,
		arg.RawResponse,
		arg.Error,
	)
	return err
}

const listInterruptedLocalVisibilityRuns = `-- name: ListInterruptedLocalVisibilityRuns :many
SELECT r.id FROM local_visibility_runs r
JOIN ai_worker_jobs j ON j.local_run_id = r.id
WHERE j.status = 'failed' AND r.status IN ('queued','running')
`

func (q *Queries) ListInterruptedLocalVisibilityRuns(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listInterruptedLocalVisibilityRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLocalVisibilityRun = `-- name: LockLocalVisibilityRun :one
SELECT id, location_id, status, radius_m, snapshot, expected_credits, reserved_credits, credits_used, retry_credits, error, created_at, started_at, completed_at FROM local_visibility_runs WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockLocalVisibilityRun(ctx context.Context, id pgtype.UUID) (LocalVisibilityRun, error) {
	row := q.db.QueryRow(ctx, lockLocalVisibilityRun, id)
	var i LocalVisibilityRun
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Status,
		&i.RadiusM,
		&i.Snapshot,
		&i.ExpectedCredits,
		&i.ReservedCredits,
		&i.CreditsUsed,
		&i.RetryCredits,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const reserveOrganizationMapsCredits = `-- name: ReserveOrganizationMapsCredits :one
UPDATE organization_maps_credit_budgets SET reserved_credits = reserved_credits + $1::bigint
WHERE organization_id = $2 AND remaining_credits - reserved_credits >= $1::bigint
RETURNING organization_id, remaining_credits, reserved_credits, spent_credits
`

type ReserveOrganizationMapsCreditsParams struct {
	Credits        int64
	OrganizationID pgtype.UUID
}

func (q *Queries) ReserveOrganizationMapsCredits(ctx context.Context, arg ReserveOrganizationMapsCreditsParams) (OrganizationMapsCreditBudget, error) {
	row := q.db.QueryRow(ctx, reserveOrganizationMapsCredits, arg.Credits, arg.OrganizationID)
	var i OrganizationMapsCreditBudget
	err := row.Scan(
		&i.OrganizationID,
		&i.RemainingCredits,
		&i.ReservedCredits,
		&i.SpentCredits,
	)
	return i, err
}

const reservePlatformMapsCredits = `-- name: ReservePlatformMapsCredits :one
UPDATE platform_maps_credit_budget SET reserved_credits = reserved_credits + $1::bigint
WHERE id = TRUE AND remaining_credits - reserved_credits >= $1::bigint
RETURNING id, remaining_credits, reserved_credits, spent_credits
`

func (q *Queries) ReservePlatformMapsCredits(ctx context.Context, credits int64) (PlatformMapsCreditBudget, error) {
	row := q.db.QueryRow(ctx, reservePlatformMapsCredits, credits)
	var i PlatformMapsCreditBudget
	err := row.Scan(
		&i.ID,
		&i.RemainingCredits,
		&i.ReservedCredits,
		&i.SpentCredits,
	)
	return i, err
}

const settleLocalRunCredits = `-- name: SettleLocalRunCredits :exec
UPDATE local_visibility_runs SET reserved_credits = reserved_credits - $1::integer,
credits_used = credits_used + $2::integer
WHERE id = $3
`

type SettleLocalRunCreditsParams struct {
	Released int32
	Spent    int32
	ID       pgtype.UUID
}

func (q *Queries) SettleLocalRunCredits(ctx context.Context, arg SettleLocalRunCreditsParams) error {
	_, err := q.db.Exec(ctx, settleLocalRunCredits, arg.Released, arg.Spent, arg.ID)
	return err
}

const settleOrganizationMapsCredits = `-- name: SettleOrganizationMapsCredits :exec
UPDATE organization_maps_credit_budgets
SET reserved_credits = reserved_credits - $1::bigint,
remaining_credits = remaining_credits - $2::bigint,
spent_credits = spent_credits + $2::bigint
WHERE organization_id = $3
`

type SettleOrganizationMapsCreditsParams struct {
	Released       int64
	Spent          int64
	OrganizationID pgtype.UUID
}

func (q *Queries) SettleOrganizationMapsCredits(ctx context.Context, arg SettleOrganizationMapsCreditsParams) error {
	_, err := q.db.Exec(ctx, settleOrganizationMapsCredits, arg.Released, arg.Spent, arg.OrganizationID)
	return err
}

const settlePlatformMapsCredits = `-- name: SettlePlatformMapsCredits :exec
UPDATE platform_maps_credit_budget
SET reserved_credits = reserved_credits - $1::bigint,
remaining_credits = remaining_credits - $2::bigint,
spent_credits = spent_credits + $2::bigint
WHERE id = TRUE
`

type SettlePlatformMapsCreditsParams struct {
	Released int64
	Spent    int64
}

func (q *Queries) SettlePlatformMapsCredits(ctx context.Context, arg SettlePlatformMapsCreditsParams) error {
	_, err := q.db.Exec(ctx, settlePlatformMapsCredits, arg.Released, arg.Spent)
	return err
}

const startLocalRunCell = `-- name: StartLocalRunCell :one
UPDATE local_run_cells c SET started_at = now()
WHERE c.run_id = $1 AND c.query_index = $2 AND c.point_index = $3 AND c.started_at IS NULL
AND NOT EXISTS(SELECT 1 FROM local_visibility_results r WHERE r.run_id = c.run_id AND r.query_index = c.query_index AND r.point_index = c.point_index)
RETURNING run_id, query_index, point_index, started_at
`

type StartLocalRunCellParams struct {
	RunID      pgtype.UUID
	QueryIndex int16
	PointIndex int16
}

func (q *Queries) StartLocalRunCell(ctx context.Context, arg StartLocalRunCellParams) (LocalRunCell, error) {
	row := q.db.QueryRow(ctx, startLocalRunCell, arg.RunID, arg.QueryIndex, arg.PointIndex)
	var i LocalRunCell
	err := row.Scan(
		&i.RunID,
		&i.QueryIndex,
		&i.PointIndex,
		&i.StartedAt,
	)
	return i, err
}

const startLocalVisibilityRun = `-- name: StartLocalVisibilityRun :one
UPDATE local_visibility_runs SET status = 'running',started_at = now()
WHERE id = $1 AND status = 'queued' RETURNING id, location_id, status, radius_m, snapshot, expected_credits, reserved_credits, credits_used, retry_credits, error, created_at, started_at, completed_at
`

func (q *Queries) StartLocalVisibilityRun(ctx context.Context, id pgtype.UUID) (LocalVisibilityRun, error) {
	row := q.db.QueryRow(ctx, startLocalVisibilityRun, id)
	var i LocalVisibilityRun
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Status,
		&i.RadiusM,
		&i.Snapshot,
		&i.ExpectedCredits,
		&i.ReservedCredits,
		&i.CreditsUsed,
		&i.RetryCredits,
		&i.Error,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateOrganizationMapsCreditBudget = `-- name: UpdateOrganizationMapsCreditBudget :one
INSERT INTO organization_maps_credit_budgets(organization_id,remaining_credits)
SELECT o.id,$1::bigint FROM organizations o
LEFT JOIN organization_maps_credit_budgets b ON b.organization_id = o.id
WHERE o.id = $2 AND COALESCE(b.remaining_credits,0) = $3::bigint
ON CONFLICT(organization_id) DO UPDATE SET remaining_credits = EXCLUDED.remaining_credits
WHERE organization_maps_credit_budgets.remaining_credits = $3::bigint
RETURNING organization_id, remaining_credits, reserved_credits, spent_credits
`

type UpdateOrganizationMapsCreditBudgetParams struct {
	RemainingCredits         int64
	OrganizationID           pgtype.UUID
	ExpectedRemainingCredits int64
}

func (q *Queries) UpdateOrganizationMapsCreditBudget(ctx context.Context, arg UpdateOrganizationMapsCreditBudgetParams) (OrganizationMapsCreditBudget, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMapsCreditBudget, arg.RemainingCredits, arg.OrganizationID, arg.ExpectedRemainingCredits)
	var i OrganizationMapsCreditBudget
	err := row.Scan(
		&i.OrganizationID,
		&i.RemainingCredits,
		&i.ReservedCredits,
		&i.SpentCredits,
	)
	return i, err
}

const updatePlatformMapsCreditBudget = `-- name: UpdatePlatformMapsCreditBudget :one
UPDATE platform_maps_credit_budget SET remaining_credits = $1::bigint
WHERE id = TRUE AND remaining_credits = $2::bigint RETURNING id, remaining_credits, reserved_credits, spent_credits
`

type UpdatePlatformMapsCreditBudgetParams struct {
	RemainingCredits         int64
	ExpectedRemainingCredits int64
}

func (q *Queries) UpdatePlatformMapsCreditBudget(ctx context.Context, arg UpdatePlatformMapsCreditBudgetParams) (PlatformMapsCreditBudget, error) {
	row := q.db.QueryRow(ctx, updatePlatformMapsCreditBudget, arg.RemainingCredits, arg.ExpectedRemainingCredits)
	var i PlatformMapsCreditBudget
	err := row.Scan(
		&i.ID,
		&i.RemainingCredits,
		&i.ReservedCredits,
		&i.SpentCredits,
	)
	return i, err
}
