// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location_landmarks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRemovedLocationLandmarksForUser = `-- name: DeleteRemovedLocationLandmarksForUser :execrows
DELETE FROM location_landmarks ll
USING project_locations l, projects p, organization_members m
WHERE ll.location_id = l.id AND l.id = $1::uuid
  AND l.project_id = p.id AND p.id = $2::uuid
  AND m.org_id = p.organization_id AND m.user_id = $3::uuid
  AND NOT (ll.provider_ref = ANY($4::text[]))
`

type DeleteRemovedLocationLandmarksForUserParams struct {
	LocationID       pgtype.UUID
	ProjectID        pgtype.UUID
	UserID           pgtype.UUID
	KeepProviderRefs []string
}

// Caller runs this only after a successful fetch, passing the full set of provider_refs to retain.
func (q *Queries) DeleteRemovedLocationLandmarksForUser(ctx context.Context, arg DeleteRemovedLocationLandmarksForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRemovedLocationLandmarksForUser,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
		arg.KeepProviderRefs,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listLocationLandmarksForUser = `-- name: ListLocationLandmarksForUser :many
SELECT ll.id, ll.location_id, ll.name, ll.latitude, ll.longitude, ll.straight_line_m, ll.provider, ll.provider_ref, ll.categories, ll.fetched_at, ll.selected FROM location_landmarks ll
JOIN project_locations l ON l.id = ll.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE ll.location_id = $1::uuid
  AND l.project_id = $2::uuid
  AND m.user_id = $3::uuid
ORDER BY ll.name, ll.id
`

type ListLocationLandmarksForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) ListLocationLandmarksForUser(ctx context.Context, arg ListLocationLandmarksForUserParams) ([]LocationLandmark, error) {
	rows, err := q.db.Query(ctx, listLocationLandmarksForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocationLandmark
	for rows.Next() {
		var i LocationLandmark
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.Latitude,
			&i.Longitude,
			&i.StraightLineM,
			&i.Provider,
			&i.ProviderRef,
			&i.Categories,
			&i.FetchedAt,
			&i.Selected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectLocationForLandmarkRefreshForUser = `-- name: LockProjectLocationForLandmarkRefreshForUser :one
SELECT l.id, l.project_id, l.place_id, l.latitude, l.longitude, l.name
FROM project_locations l
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $1::uuid AND p.id = $2::uuid
  AND m.user_id = $3::uuid
FOR NO KEY UPDATE OF l
`

type LockProjectLocationForLandmarkRefreshForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

type LockProjectLocationForLandmarkRefreshForUserRow struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	PlaceID   pgtype.Text
	Latitude  float64
	Longitude float64
	Name      string
}

func (q *Queries) LockProjectLocationForLandmarkRefreshForUser(ctx context.Context, arg LockProjectLocationForLandmarkRefreshForUserParams) (LockProjectLocationForLandmarkRefreshForUserRow, error) {
	row := q.db.QueryRow(ctx, lockProjectLocationForLandmarkRefreshForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	var i LockProjectLocationForLandmarkRefreshForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlaceID,
		&i.Latitude,
		&i.Longitude,
		&i.Name,
	)
	return i, err
}

const updateLocationLandmarkSelectionForUser = `-- name: UpdateLocationLandmarkSelectionForUser :one
UPDATE location_landmarks ll SET selected = $1::boolean
FROM project_locations l, projects p, organization_members m
WHERE ll.id = $2::uuid AND ll.location_id = l.id AND l.project_id = p.id
  AND ll.location_id = $3::uuid
  AND p.id = $4::uuid
  AND m.org_id = p.organization_id AND m.user_id = $5::uuid
RETURNING ll.id, ll.location_id, ll.name, ll.latitude, ll.longitude, ll.straight_line_m, ll.provider, ll.provider_ref, ll.categories, ll.fetched_at, ll.selected
`

type UpdateLocationLandmarkSelectionForUserParams struct {
	Selected   bool
	ID         pgtype.UUID
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) UpdateLocationLandmarkSelectionForUser(ctx context.Context, arg UpdateLocationLandmarkSelectionForUserParams) (LocationLandmark, error) {
	row := q.db.QueryRow(ctx, updateLocationLandmarkSelectionForUser,
		arg.Selected,
		arg.ID,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	var i LocationLandmark
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.StraightLineM,
		&i.Provider,
		&i.ProviderRef,
		&i.Categories,
		&i.FetchedAt,
		&i.Selected,
	)
	return i, err
}

const upsertLocationLandmarkForUser = `-- name: UpsertLocationLandmarkForUser :one
INSERT INTO location_landmarks(location_id, name, latitude, longitude, straight_line_m, provider, provider_ref, categories, fetched_at)
SELECT l.id, $1::text, $2::double precision,
       $3::double precision, $4::integer,
       $5::text,
       $6::text, $7::text[],
       $8::timestamptz
FROM project_locations l
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $9::uuid AND p.id = $10::uuid
  AND m.user_id = $11::uuid
ON CONFLICT (location_id, provider_ref) DO UPDATE SET
    name = EXCLUDED.name,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    straight_line_m = EXCLUDED.straight_line_m,
    provider = EXCLUDED.provider,
    categories = EXCLUDED.categories,
    fetched_at = EXCLUDED.fetched_at
RETURNING id, location_id, name, latitude, longitude, straight_line_m, provider, provider_ref, categories, fetched_at, selected
`

type UpsertLocationLandmarkForUserParams struct {
	Name          string
	Latitude      float64
	Longitude     float64
	StraightLineM int32
	Provider      string
	ProviderRef   string
	Categories    []string
	FetchedAt     pgtype.Timestamptz
	LocationID    pgtype.UUID
	ProjectID     pgtype.UUID
	UserID        pgtype.UUID
}

// selected is absent from the SET list, so a user's tick survives a refresh.
func (q *Queries) UpsertLocationLandmarkForUser(ctx context.Context, arg UpsertLocationLandmarkForUserParams) (LocationLandmark, error) {
	row := q.db.QueryRow(ctx, upsertLocationLandmarkForUser,
		arg.Name,
		arg.Latitude,
		arg.Longitude,
		arg.StraightLineM,
		arg.Provider,
		arg.ProviderRef,
		arg.Categories,
		arg.FetchedAt,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	var i LocationLandmark
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Name,
		&i.Latitude,
		&i.Longitude,
		&i.StraightLineM,
		&i.Provider,
		&i.ProviderRef,
		&i.Categories,
		&i.FetchedAt,
		&i.Selected,
	)
	return i, err
}
