// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteObsoleteGeneratedProjectLocationQueryForUser = `-- name: DeleteObsoleteGeneratedProjectLocationQueryForUser :execrows
DELETE FROM project_location_queries q
USING project_locations l, projects p, organization_members m
WHERE q.location_id = l.id AND l.project_id = p.id
  AND p.id = $1::uuid
  AND l.id = $2::uuid
  AND q.kind = $3::text AND q.normalized = $4::text
  AND q.source = 'generated'
  AND m.org_id = p.organization_id AND m.user_id = $5::uuid
`

type DeleteObsoleteGeneratedProjectLocationQueryForUserParams struct {
	ProjectID  pgtype.UUID
	LocationID pgtype.UUID
	Kind       string
	Normalized string
	UserID     pgtype.UUID
}

func (q *Queries) DeleteObsoleteGeneratedProjectLocationQueryForUser(ctx context.Context, arg DeleteObsoleteGeneratedProjectLocationQueryForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteObsoleteGeneratedProjectLocationQueryForUser,
		arg.ProjectID,
		arg.LocationID,
		arg.Kind,
		arg.Normalized,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectLocationQueryForUser = `-- name: DeleteProjectLocationQueryForUser :execrows
DELETE FROM project_location_queries q
USING project_locations l, projects p, organization_members m
WHERE q.id = $1::uuid AND q.location_id = l.id AND l.project_id = p.id
  AND q.location_id = $2::uuid
  AND p.id = $3::uuid
  AND m.org_id = p.organization_id AND m.user_id = $4::uuid
  AND q.source = 'manual'
`

type DeleteProjectLocationQueryForUserParams struct {
	ID         pgtype.UUID
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

// Manual rows only: an omission that targets a generated query disables it instead of deleting.
func (q *Queries) DeleteProjectLocationQueryForUser(ctx context.Context, arg DeleteProjectLocationQueryForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectLocationQueryForUser,
		arg.ID,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableProjectLocationQueryForUser = `-- name: DisableProjectLocationQueryForUser :one
UPDATE project_location_queries q SET enabled = FALSE, updated_at = now()
FROM project_locations l, projects p, organization_members m
WHERE q.id = $1::uuid AND q.location_id = l.id AND l.project_id = p.id
  AND q.location_id = $2::uuid
  AND p.id = $3::uuid
  AND m.org_id = p.organization_id AND m.user_id = $4::uuid
  AND q.source = 'generated'
RETURNING q.id, q.location_id, q.text, q.normalized, q.ordinal, q.enabled, q.kind, q.source, q.origin, q.landmark_id, q.created_at, q.updated_at
`

type DisableProjectLocationQueryForUserParams struct {
	ID         pgtype.UUID
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) DisableProjectLocationQueryForUser(ctx context.Context, arg DisableProjectLocationQueryForUserParams) (ProjectLocationQuery, error) {
	row := q.db.QueryRow(ctx, disableProjectLocationQueryForUser,
		arg.ID,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectLocationQuery
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Text,
		&i.Normalized,
		&i.Ordinal,
		&i.Enabled,
		&i.Kind,
		&i.Source,
		&i.Origin,
		&i.LandmarkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocationForAIAuditWorker = `-- name: GetLocationForAIAuditWorker :one
SELECT id, project_id, name, place_id, latitude, longitude, created_at, updated_at, address, locality, localities FROM project_locations
WHERE id = $1::uuid
  AND project_id = $2::uuid
`

type GetLocationForAIAuditWorkerParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
}

func (q *Queries) GetLocationForAIAuditWorker(ctx context.Context, arg GetLocationForAIAuditWorkerParams) (ProjectLocation, error) {
	row := q.db.QueryRow(ctx, getLocationForAIAuditWorker, arg.LocationID, arg.ProjectID)
	var i ProjectLocation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.PlaceID,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Address,
		&i.Locality,
		&i.Localities,
	)
	return i, err
}

const insertMissingGeneratedProjectLocationQueryForUser = `-- name: InsertMissingGeneratedProjectLocationQueryForUser :one
INSERT INTO project_location_queries(location_id, text, normalized, ordinal, enabled, kind, source, origin, landmark_id)
SELECT l.id, $1::text, $2::text, $3::integer,
       TRUE, $4::text, 'generated', $5::text, $6::uuid
FROM project_locations l
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $7::uuid AND p.id = $8::uuid
  AND m.user_id = $9::uuid
  AND ($6::uuid IS NULL
       OR EXISTS (SELECT 1 FROM location_landmarks ll
                  WHERE ll.id = $6::uuid AND ll.location_id = l.id))
ON CONFLICT (location_id, kind, normalized) DO NOTHING
RETURNING id, location_id, text, normalized, ordinal, enabled, kind, source, origin, landmark_id, created_at, updated_at
`

type InsertMissingGeneratedProjectLocationQueryForUserParams struct {
	Text       string
	Normalized string
	Ordinal    int32
	Kind       string
	Origin     string
	LandmarkID pgtype.UUID
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) InsertMissingGeneratedProjectLocationQueryForUser(ctx context.Context, arg InsertMissingGeneratedProjectLocationQueryForUserParams) (ProjectLocationQuery, error) {
	row := q.db.QueryRow(ctx, insertMissingGeneratedProjectLocationQueryForUser,
		arg.Text,
		arg.Normalized,
		arg.Ordinal,
		arg.Kind,
		arg.Origin,
		arg.LandmarkID,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectLocationQuery
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Text,
		&i.Normalized,
		&i.Ordinal,
		&i.Enabled,
		&i.Kind,
		&i.Source,
		&i.Origin,
		&i.LandmarkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectLocationQueryForUser = `-- name: InsertProjectLocationQueryForUser :one
INSERT INTO project_location_queries(location_id, text, normalized, ordinal, enabled, kind, source, origin, landmark_id)
SELECT l.id, $1::text, $2::text, $3::integer,
       $4::boolean, $5::text, $6::text,
       $7::text, $8::uuid
FROM project_locations l
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $9::uuid AND p.id = $10::uuid
  AND m.user_id = $11::uuid
  AND ($8::uuid IS NULL
       OR EXISTS (SELECT 1 FROM location_landmarks ll
                  WHERE ll.id = $8::uuid AND ll.location_id = l.id))
RETURNING id, location_id, text, normalized, ordinal, enabled, kind, source, origin, landmark_id, created_at, updated_at
`

type InsertProjectLocationQueryForUserParams struct {
	Text       string
	Normalized string
	Ordinal    int32
	Enabled    bool
	Kind       string
	Source     string
	Origin     string
	LandmarkID pgtype.UUID
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) InsertProjectLocationQueryForUser(ctx context.Context, arg InsertProjectLocationQueryForUserParams) (ProjectLocationQuery, error) {
	row := q.db.QueryRow(ctx, insertProjectLocationQueryForUser,
		arg.Text,
		arg.Normalized,
		arg.Ordinal,
		arg.Enabled,
		arg.Kind,
		arg.Source,
		arg.Origin,
		arg.LandmarkID,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectLocationQuery
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Text,
		&i.Normalized,
		&i.Ordinal,
		&i.Enabled,
		&i.Kind,
		&i.Source,
		&i.Origin,
		&i.LandmarkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledMapQueriesForLocation = `-- name: ListEnabledMapQueriesForLocation :many
SELECT q.id, q.location_id, q.text, q.normalized, q.ordinal, q.enabled, q.kind, q.source, q.origin, q.landmark_id, q.created_at, q.updated_at FROM project_location_queries q
JOIN project_locations l ON l.id = q.location_id
WHERE q.location_id = $1::uuid
  AND l.project_id = $2::uuid
  AND q.kind = 'map' AND q.enabled = TRUE
ORDER BY q.ordinal, q.id
`

type ListEnabledMapQueriesForLocationParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
}

func (q *Queries) ListEnabledMapQueriesForLocation(ctx context.Context, arg ListEnabledMapQueriesForLocationParams) ([]ProjectLocationQuery, error) {
	rows, err := q.db.Query(ctx, listEnabledMapQueriesForLocation, arg.LocationID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectLocationQuery
	for rows.Next() {
		var i ProjectLocationQuery
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Text,
			&i.Normalized,
			&i.Ordinal,
			&i.Enabled,
			&i.Kind,
			&i.Source,
			&i.Origin,
			&i.LandmarkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledMapQueriesForUser = `-- name: ListEnabledMapQueriesForUser :many
SELECT q.id, q.location_id, q.text, q.normalized, q.ordinal, q.enabled, q.kind, q.source, q.origin, q.landmark_id, q.created_at, q.updated_at FROM project_location_queries q
JOIN project_locations l ON l.id = q.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE q.location_id = $1::uuid
  AND l.project_id = $2::uuid
  AND m.user_id = $3::uuid
  AND q.kind = 'map' AND q.enabled = TRUE
ORDER BY q.ordinal, q.id
`

type ListEnabledMapQueriesForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) ListEnabledMapQueriesForUser(ctx context.Context, arg ListEnabledMapQueriesForUserParams) ([]ProjectLocationQuery, error) {
	rows, err := q.db.Query(ctx, listEnabledMapQueriesForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectLocationQuery
	for rows.Next() {
		var i ProjectLocationQuery
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Text,
			&i.Normalized,
			&i.Ordinal,
			&i.Enabled,
			&i.Kind,
			&i.Source,
			&i.Origin,
			&i.LandmarkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLocationQueriesForUser = `-- name: ListProjectLocationQueriesForUser :many

SELECT q.id, q.location_id, q.text, q.normalized, q.ordinal, q.enabled, q.kind, q.source, q.origin, q.landmark_id, q.created_at, q.updated_at FROM project_location_queries q
JOIN project_locations l ON l.id = q.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE q.location_id = $1::uuid
  AND l.project_id = $2::uuid
  AND m.user_id = $3::uuid
ORDER BY q.kind, q.ordinal, q.id
`

type ListProjectLocationQueriesForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

// Draft rows for a location. A run reads its own frozen snapshot, never this table.
func (q *Queries) ListProjectLocationQueriesForUser(ctx context.Context, arg ListProjectLocationQueriesForUserParams) ([]ProjectLocationQuery, error) {
	rows, err := q.db.Query(ctx, listProjectLocationQueriesForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectLocationQuery
	for rows.Next() {
		var i ProjectLocationQuery
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Text,
			&i.Normalized,
			&i.Ordinal,
			&i.Enabled,
			&i.Kind,
			&i.Source,
			&i.Origin,
			&i.LandmarkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectLocationForQueryDraftForUser = `-- name: LockProjectLocationForQueryDraftForUser :one
SELECT l.id, l.project_id, l.place_id, l.latitude, l.longitude, l.name, p.organization_id
FROM project_locations l
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $1::uuid AND p.id = $2::uuid
  AND m.user_id = $3::uuid
FOR NO KEY UPDATE OF l
`

type LockProjectLocationForQueryDraftForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

type LockProjectLocationForQueryDraftForUserRow struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	PlaceID        pgtype.Text
	Latitude       float64
	Longitude      float64
	Name           string
	OrganizationID pgtype.UUID
}

// Locks the parent location so concurrent draft writes for it serialize, including inserts into an empty draft.
func (q *Queries) LockProjectLocationForQueryDraftForUser(ctx context.Context, arg LockProjectLocationForQueryDraftForUserParams) (LockProjectLocationForQueryDraftForUserRow, error) {
	row := q.db.QueryRow(ctx, lockProjectLocationForQueryDraftForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	var i LockProjectLocationForQueryDraftForUserRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PlaceID,
		&i.Latitude,
		&i.Longitude,
		&i.Name,
		&i.OrganizationID,
	)
	return i, err
}

const lockProjectLocationQueriesForUser = `-- name: LockProjectLocationQueriesForUser :many
SELECT q.id, q.location_id, q.text, q.normalized, q.ordinal, q.enabled, q.kind, q.source, q.origin, q.landmark_id, q.created_at, q.updated_at FROM project_location_queries q
JOIN project_locations l ON l.id = q.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE q.location_id = $1::uuid
  AND l.project_id = $2::uuid
  AND m.user_id = $3::uuid
ORDER BY q.kind, q.ordinal, q.id
FOR UPDATE OF q
`

type LockProjectLocationQueriesForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) LockProjectLocationQueriesForUser(ctx context.Context, arg LockProjectLocationQueriesForUserParams) ([]ProjectLocationQuery, error) {
	rows, err := q.db.Query(ctx, lockProjectLocationQueriesForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectLocationQuery
	for rows.Next() {
		var i ProjectLocationQuery
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Text,
			&i.Normalized,
			&i.Ordinal,
			&i.Enabled,
			&i.Kind,
			&i.Source,
			&i.Origin,
			&i.LandmarkID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectLocationQueryForUser = `-- name: UpdateProjectLocationQueryForUser :one
UPDATE project_location_queries q SET text = $1::text,
    normalized = $2::text, ordinal = $3::integer,
    enabled = $4::boolean, kind = $5::text,
    source = $6::text, origin = $7::text,
    landmark_id = $8::uuid, updated_at = now()
FROM project_locations l, projects p, organization_members m
WHERE q.id = $9::uuid AND q.location_id = l.id AND l.project_id = p.id
  AND q.location_id = $10::uuid
  AND p.id = $11::uuid
  AND m.org_id = p.organization_id AND m.user_id = $12::uuid
  AND ($8::uuid IS NULL
       OR EXISTS (SELECT 1 FROM location_landmarks ll
                  WHERE ll.id = $8::uuid AND ll.location_id = l.id))
RETURNING q.id, q.location_id, q.text, q.normalized, q.ordinal, q.enabled, q.kind, q.source, q.origin, q.landmark_id, q.created_at, q.updated_at
`

type UpdateProjectLocationQueryForUserParams struct {
	Text       string
	Normalized string
	Ordinal    int32
	Enabled    bool
	Kind       string
	Source     string
	Origin     string
	LandmarkID pgtype.UUID
	ID         pgtype.UUID
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) UpdateProjectLocationQueryForUser(ctx context.Context, arg UpdateProjectLocationQueryForUserParams) (ProjectLocationQuery, error) {
	row := q.db.QueryRow(ctx, updateProjectLocationQueryForUser,
		arg.Text,
		arg.Normalized,
		arg.Ordinal,
		arg.Enabled,
		arg.Kind,
		arg.Source,
		arg.Origin,
		arg.LandmarkID,
		arg.ID,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectLocationQuery
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Text,
		&i.Normalized,
		&i.Ordinal,
		&i.Enabled,
		&i.Kind,
		&i.Source,
		&i.Origin,
		&i.LandmarkID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
