// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: location_services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectServiceForUser = `-- name: CreateProjectServiceForUser :one
INSERT INTO project_services(project_id, label, normalized_label)
SELECT p.id, $1::text, $2::text
FROM projects p
JOIN organization_members m ON m.org_id = p.organization_id
WHERE p.id = $3::uuid AND m.user_id = $4::uuid
RETURNING id, project_id, label, normalized_label, created_at, updated_at
`

type CreateProjectServiceForUserParams struct {
	Label           string
	NormalizedLabel string
	ProjectID       pgtype.UUID
	UserID          pgtype.UUID
}

func (q *Queries) CreateProjectServiceForUser(ctx context.Context, arg CreateProjectServiceForUserParams) (ProjectService, error) {
	row := q.db.QueryRow(ctx, createProjectServiceForUser,
		arg.Label,
		arg.NormalizedLabel,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectService
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Label,
		&i.NormalizedLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectLocationServiceOverridesForUser = `-- name: DeleteProjectLocationServiceOverridesForUser :execrows
DELETE FROM project_location_services o
USING project_locations l, projects p, organization_members m
WHERE o.location_id = l.id AND l.project_id = p.id
  AND l.id = $1::uuid AND p.id = $2::uuid
  AND m.org_id = p.organization_id AND m.user_id = $3::uuid
`

type DeleteProjectLocationServiceOverridesForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) DeleteProjectLocationServiceOverridesForUser(ctx context.Context, arg DeleteProjectLocationServiceOverridesForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectLocationServiceOverridesForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProjectServiceForUser = `-- name: DeleteProjectServiceForUser :execrows
DELETE FROM project_services s
USING projects p, organization_members m
WHERE s.id = $1::uuid AND s.project_id = p.id
  AND p.id = $2::uuid
  AND m.org_id = p.organization_id AND m.user_id = $3::uuid
`

type DeleteProjectServiceForUserParams struct {
	ServiceID pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteProjectServiceForUser(ctx context.Context, arg DeleteProjectServiceForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectServiceForUser, arg.ServiceID, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProjectLocationServiceOverrideForUser = `-- name: InsertProjectLocationServiceOverrideForUser :one
INSERT INTO project_location_services(location_id, project_id, service_id, service_label, normalized_service_label, mode)
SELECT l.id, l.project_id, $1::uuid, $2::text,
       $3::text, $4::text
FROM project_locations l
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE l.id = $5::uuid AND p.id = $6::uuid
  AND m.user_id = $7::uuid
RETURNING id, location_id, project_id, service_id, service_label, normalized_service_label, mode, created_at
`

type InsertProjectLocationServiceOverrideForUserParams struct {
	ServiceID              pgtype.UUID
	ServiceLabel           pgtype.Text
	NormalizedServiceLabel pgtype.Text
	Mode                   string
	LocationID             pgtype.UUID
	ProjectID              pgtype.UUID
	UserID                 pgtype.UUID
}

func (q *Queries) InsertProjectLocationServiceOverrideForUser(ctx context.Context, arg InsertProjectLocationServiceOverrideForUserParams) (ProjectLocationService, error) {
	row := q.db.QueryRow(ctx, insertProjectLocationServiceOverrideForUser,
		arg.ServiceID,
		arg.ServiceLabel,
		arg.NormalizedServiceLabel,
		arg.Mode,
		arg.LocationID,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectLocationService
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.ProjectID,
		&i.ServiceID,
		&i.ServiceLabel,
		&i.NormalizedServiceLabel,
		&i.Mode,
		&i.CreatedAt,
	)
	return i, err
}

const listEffectiveProjectLocationServiceLabelsForUser = `-- name: ListEffectiveProjectLocationServiceLabelsForUser :many
SELECT label, normalized_label
FROM (
    SELECT DISTINCT ON (normalized_label) label, normalized_label, bucket
    FROM (
        SELECT s.label, s.normalized_label, 0 AS bucket
        FROM project_services s
        JOIN project_locations l
          ON l.id = $1::uuid AND l.project_id = s.project_id
        JOIN projects p ON p.id = l.project_id
        JOIN organization_members m ON m.org_id = p.organization_id
        WHERE s.project_id = $2::uuid
          AND m.user_id = $3::uuid
          AND NOT EXISTS (
              SELECT 1 FROM project_location_services o
              WHERE o.location_id = l.id AND o.service_id = s.id AND o.mode = 'exclude'
          )
        UNION ALL
        SELECT o.service_label, o.normalized_service_label, 1 AS bucket
        FROM project_location_services o
        JOIN project_locations l ON l.id = o.location_id
        JOIN projects p ON p.id = l.project_id
        JOIN organization_members m ON m.org_id = p.organization_id
        WHERE o.location_id = $1::uuid
          AND l.project_id = $2::uuid
          AND o.service_label IS NOT NULL AND o.mode = 'include'
          AND m.user_id = $3::uuid
    ) combined
    ORDER BY normalized_label, bucket
) deduped
ORDER BY bucket, normalized_label
`

type ListEffectiveProjectLocationServiceLabelsForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

type ListEffectiveProjectLocationServiceLabelsForUserRow struct {
	Label           string
	NormalizedLabel string
}

func (q *Queries) ListEffectiveProjectLocationServiceLabelsForUser(ctx context.Context, arg ListEffectiveProjectLocationServiceLabelsForUserParams) ([]ListEffectiveProjectLocationServiceLabelsForUserRow, error) {
	rows, err := q.db.Query(ctx, listEffectiveProjectLocationServiceLabelsForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEffectiveProjectLocationServiceLabelsForUserRow
	for rows.Next() {
		var i ListEffectiveProjectLocationServiceLabelsForUserRow
		if err := rows.Scan(&i.Label, &i.NormalizedLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLocationOnlyServiceLabelsForUser = `-- name: ListProjectLocationOnlyServiceLabelsForUser :many
SELECT o.id, o.service_label, o.normalized_service_label
FROM project_location_services o
JOIN project_locations l ON l.id = o.location_id
JOIN projects p ON p.id = l.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE o.location_id = $1::uuid
  AND l.project_id = $2::uuid
  AND o.service_label IS NOT NULL AND o.mode = 'include'
  AND m.user_id = $3::uuid
ORDER BY o.normalized_service_label, o.id
`

type ListProjectLocationOnlyServiceLabelsForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

type ListProjectLocationOnlyServiceLabelsForUserRow struct {
	ID                     pgtype.UUID
	ServiceLabel           pgtype.Text
	NormalizedServiceLabel pgtype.Text
}

func (q *Queries) ListProjectLocationOnlyServiceLabelsForUser(ctx context.Context, arg ListProjectLocationOnlyServiceLabelsForUserParams) ([]ListProjectLocationOnlyServiceLabelsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectLocationOnlyServiceLabelsForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectLocationOnlyServiceLabelsForUserRow
	for rows.Next() {
		var i ListProjectLocationOnlyServiceLabelsForUserRow
		if err := rows.Scan(&i.ID, &i.ServiceLabel, &i.NormalizedServiceLabel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLocationServiceEditorRowsForUser = `-- name: ListProjectLocationServiceEditorRowsForUser :many
SELECT s.id AS service_id, s.label, s.normalized_label,
    (o.id IS NOT NULL)::boolean AS excluded
FROM project_services s
JOIN projects p ON p.id = s.project_id
JOIN organization_members m ON m.org_id = p.organization_id
JOIN project_locations l
  ON l.id = $1::uuid AND l.project_id = p.id
LEFT JOIN project_location_services o
  ON o.location_id = l.id AND o.service_id = s.id AND o.mode = 'exclude'
WHERE s.project_id = $2::uuid AND m.user_id = $3::uuid
ORDER BY s.normalized_label, s.id
`

type ListProjectLocationServiceEditorRowsForUserParams struct {
	LocationID pgtype.UUID
	ProjectID  pgtype.UUID
	UserID     pgtype.UUID
}

type ListProjectLocationServiceEditorRowsForUserRow struct {
	ServiceID       pgtype.UUID
	Label           string
	NormalizedLabel string
	Excluded        bool
}

func (q *Queries) ListProjectLocationServiceEditorRowsForUser(ctx context.Context, arg ListProjectLocationServiceEditorRowsForUserParams) ([]ListProjectLocationServiceEditorRowsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectLocationServiceEditorRowsForUser, arg.LocationID, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectLocationServiceEditorRowsForUserRow
	for rows.Next() {
		var i ListProjectLocationServiceEditorRowsForUserRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.Label,
			&i.NormalizedLabel,
			&i.Excluded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectServicesForUser = `-- name: ListProjectServicesForUser :many
SELECT s.id, s.project_id, s.label, s.normalized_label, s.created_at, s.updated_at FROM project_services s
JOIN projects p ON p.id = s.project_id
JOIN organization_members m ON m.org_id = p.organization_id
WHERE s.project_id = $1::uuid AND m.user_id = $2::uuid
ORDER BY s.normalized_label, s.id
`

type ListProjectServicesForUserParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListProjectServicesForUser(ctx context.Context, arg ListProjectServicesForUserParams) ([]ProjectService, error) {
	rows, err := q.db.Query(ctx, listProjectServicesForUser, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectService
	for rows.Next() {
		var i ProjectService
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Label,
			&i.NormalizedLabel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameProjectServiceForUser = `-- name: RenameProjectServiceForUser :one
UPDATE project_services s SET label = $1::text,
    normalized_label = $2::text, updated_at = now()
FROM projects p, organization_members m
WHERE s.id = $3::uuid AND s.project_id = p.id
  AND p.id = $4::uuid
  AND m.org_id = p.organization_id AND m.user_id = $5::uuid
RETURNING s.id, s.project_id, s.label, s.normalized_label, s.created_at, s.updated_at
`

type RenameProjectServiceForUserParams struct {
	Label           string
	NormalizedLabel string
	ServiceID       pgtype.UUID
	ProjectID       pgtype.UUID
	UserID          pgtype.UUID
}

func (q *Queries) RenameProjectServiceForUser(ctx context.Context, arg RenameProjectServiceForUserParams) (ProjectService, error) {
	row := q.db.QueryRow(ctx, renameProjectServiceForUser,
		arg.Label,
		arg.NormalizedLabel,
		arg.ServiceID,
		arg.ProjectID,
		arg.UserID,
	)
	var i ProjectService
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Label,
		&i.NormalizedLabel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
