// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maps_visibility.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMapsVisibilityCheck = `-- name: CreateMapsVisibilityCheck :one
INSERT INTO maps_visibility_checks (project_id, question, status)
VALUES ($1, $2, 'queued')
RETURNING id, project_id, question, status, ll, zoom, our_rank, our_match_basis, credits_used, error, results, listing, created_at, updated_at, completed_at
`

type CreateMapsVisibilityCheckParams struct {
	ProjectID pgtype.UUID
	Question  string
}

func (q *Queries) CreateMapsVisibilityCheck(ctx context.Context, arg CreateMapsVisibilityCheckParams) (MapsVisibilityCheck, error) {
	row := q.db.QueryRow(ctx, createMapsVisibilityCheck, arg.ProjectID, arg.Question)
	var i MapsVisibilityCheck
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Question,
		&i.Status,
		&i.Ll,
		&i.Zoom,
		&i.OurRank,
		&i.OurMatchBasis,
		&i.CreditsUsed,
		&i.Error,
		&i.Results,
		&i.Listing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestMapsVisibilityCheckByProject = `-- name: GetLatestMapsVisibilityCheckByProject :one
SELECT id, project_id, question, status, ll, zoom, our_rank, our_match_basis, credits_used, error, results, listing, created_at, updated_at, completed_at FROM maps_visibility_checks
WHERE project_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMapsVisibilityCheckByProject(ctx context.Context, projectID pgtype.UUID) (MapsVisibilityCheck, error) {
	row := q.db.QueryRow(ctx, getLatestMapsVisibilityCheckByProject, projectID)
	var i MapsVisibilityCheck
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Question,
		&i.Status,
		&i.Ll,
		&i.Zoom,
		&i.OurRank,
		&i.OurMatchBasis,
		&i.CreditsUsed,
		&i.Error,
		&i.Results,
		&i.Listing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMapsListingRef = `-- name: GetMapsListingRef :one
SELECT project_id, cid, place_id, title, website, address, resolved_at, updated_at
FROM maps_listing_refs
WHERE project_id = $1
`

func (q *Queries) GetMapsListingRef(ctx context.Context, projectID pgtype.UUID) (MapsListingRef, error) {
	row := q.db.QueryRow(ctx, getMapsListingRef, projectID)
	var i MapsListingRef
	err := row.Scan(
		&i.ProjectID,
		&i.Cid,
		&i.PlaceID,
		&i.Title,
		&i.Website,
		&i.Address,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapsVisibilityCheck = `-- name: GetMapsVisibilityCheck :one
SELECT id, project_id, question, status, ll, zoom, our_rank, our_match_basis, credits_used, error, results, listing, created_at, updated_at, completed_at FROM maps_visibility_checks WHERE id = $1
`

func (q *Queries) GetMapsVisibilityCheck(ctx context.Context, id pgtype.UUID) (MapsVisibilityCheck, error) {
	row := q.db.QueryRow(ctx, getMapsVisibilityCheck, id)
	var i MapsVisibilityCheck
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Question,
		&i.Status,
		&i.Ll,
		&i.Zoom,
		&i.OurRank,
		&i.OurMatchBasis,
		&i.CreditsUsed,
		&i.Error,
		&i.Results,
		&i.Listing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getMapsVisibilityCheckInFlight = `-- name: GetMapsVisibilityCheckInFlight :one
SELECT id, project_id, question, status, ll, zoom, our_rank, our_match_basis, credits_used, error, results, listing, created_at, updated_at, completed_at FROM maps_visibility_checks
WHERE project_id = $1 AND status IN ('queued', 'running')
LIMIT 1
`

func (q *Queries) GetMapsVisibilityCheckInFlight(ctx context.Context, projectID pgtype.UUID) (MapsVisibilityCheck, error) {
	row := q.db.QueryRow(ctx, getMapsVisibilityCheckInFlight, projectID)
	var i MapsVisibilityCheck
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Question,
		&i.Status,
		&i.Ll,
		&i.Zoom,
		&i.OurRank,
		&i.OurMatchBasis,
		&i.CreditsUsed,
		&i.Error,
		&i.Results,
		&i.Listing,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const markMapsVisibilityCheckCompleted = `-- name: MarkMapsVisibilityCheckCompleted :exec
UPDATE maps_visibility_checks
SET status = 'completed',
    ll = $2,
    zoom = $3,
    our_rank = $4,
    our_match_basis = $5,
    credits_used = $6,
    results = $7,
    listing = $8,
    completed_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type MarkMapsVisibilityCheckCompletedParams struct {
	ID            pgtype.UUID
	Ll            pgtype.Text
	Zoom          pgtype.Int4
	OurRank       pgtype.Int4
	OurMatchBasis pgtype.Text
	CreditsUsed   pgtype.Int4
	Results       []byte
	Listing       []byte
}

func (q *Queries) MarkMapsVisibilityCheckCompleted(ctx context.Context, arg MarkMapsVisibilityCheckCompletedParams) error {
	_, err := q.db.Exec(ctx, markMapsVisibilityCheckCompleted,
		arg.ID,
		arg.Ll,
		arg.Zoom,
		arg.OurRank,
		arg.OurMatchBasis,
		arg.CreditsUsed,
		arg.Results,
		arg.Listing,
	)
	return err
}

const markMapsVisibilityCheckFailed = `-- name: MarkMapsVisibilityCheckFailed :exec
UPDATE maps_visibility_checks
SET status = 'failed', error = $2, completed_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type MarkMapsVisibilityCheckFailedParams struct {
	ID    pgtype.UUID
	Error pgtype.Text
}

func (q *Queries) MarkMapsVisibilityCheckFailed(ctx context.Context, arg MarkMapsVisibilityCheckFailedParams) error {
	_, err := q.db.Exec(ctx, markMapsVisibilityCheckFailed, arg.ID, arg.Error)
	return err
}

const markMapsVisibilityCheckRunning = `-- name: MarkMapsVisibilityCheckRunning :exec
UPDATE maps_visibility_checks
SET status = 'running', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkMapsVisibilityCheckRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markMapsVisibilityCheckRunning, id)
	return err
}

const upsertMapsListingRef = `-- name: UpsertMapsListingRef :one
INSERT INTO maps_listing_refs (project_id, cid, place_id, title, website, address, resolved_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (project_id) DO UPDATE SET
    cid = EXCLUDED.cid,
    place_id = EXCLUDED.place_id,
    title = EXCLUDED.title,
    website = EXCLUDED.website,
    address = EXCLUDED.address,
    resolved_at = NOW(),
    updated_at = NOW()
RETURNING project_id, cid, place_id, title, website, address, resolved_at, updated_at
`

type UpsertMapsListingRefParams struct {
	ProjectID pgtype.UUID
	Cid       pgtype.Text
	PlaceID   pgtype.Text
	Title     pgtype.Text
	Website   pgtype.Text
	Address   pgtype.Text
}

func (q *Queries) UpsertMapsListingRef(ctx context.Context, arg UpsertMapsListingRefParams) (MapsListingRef, error) {
	row := q.db.QueryRow(ctx, upsertMapsListingRef,
		arg.ProjectID,
		arg.Cid,
		arg.PlaceID,
		arg.Title,
		arg.Website,
		arg.Address,
	)
	var i MapsListingRef
	err := row.Scan(
		&i.ProjectID,
		&i.Cid,
		&i.PlaceID,
		&i.Title,
		&i.Website,
		&i.Address,
		&i.ResolvedAt,
		&i.UpdatedAt,
	)
	return i, err
}
