// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProjectMCPConnection = `-- name: CreateProjectMCPConnection :one
INSERT INTO project_mcp_connections (
    project_id,
    name,
    service,
    endpoint_url,
    encrypted_token,
    tools,
    last_checked_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    now()
)
RETURNING id, project_id, name, service, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
`

type CreateProjectMCPConnectionParams struct {
	ProjectID      pgtype.UUID
	Name           string
	Service        string
	EndpointUrl    string
	EncryptedToken string
	Tools          []byte
}

func (q *Queries) CreateProjectMCPConnection(ctx context.Context, arg CreateProjectMCPConnectionParams) (ProjectMcpConnection, error) {
	row := q.db.QueryRow(ctx, createProjectMCPConnection,
		arg.ProjectID,
		arg.Name,
		arg.Service,
		arg.EndpointUrl,
		arg.EncryptedToken,
		arg.Tools,
	)
	var i ProjectMcpConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Service,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPToolPermission = `-- name: DeleteMCPToolPermission :exec
DELETE FROM project_mcp_tool_permissions
WHERE connection_id = $1 AND tool_name = $2
`

type DeleteMCPToolPermissionParams struct {
	ConnectionID pgtype.UUID
	ToolName     string
}

func (q *Queries) DeleteMCPToolPermission(ctx context.Context, arg DeleteMCPToolPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteMCPToolPermission, arg.ConnectionID, arg.ToolName)
	return err
}

const deleteProjectMCPConnection = `-- name: DeleteProjectMCPConnection :execrows
DELETE FROM project_mcp_connections
WHERE id = $1 AND project_id = $2
`

type DeleteProjectMCPConnectionParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) DeleteProjectMCPConnection(ctx context.Context, arg DeleteProjectMCPConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectMCPConnection, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMCPConnectionForCall = `-- name: GetMCPConnectionForCall :one
SELECT c.revision::text AS revision, c.service AS service, COALESCE(p.permission, 'ask') AS permission, c.tools
FROM project_mcp_connections AS c
JOIN projects AS pr ON pr.id = c.project_id
JOIN organization_members AS om ON om.org_id = pr.organization_id AND om.user_id = $1
LEFT JOIN organization_features AS f ON f.org_id = pr.organization_id
LEFT JOIN project_mcp_tool_permissions AS p ON p.connection_id = c.id AND p.tool_name = $2
WHERE c.id = $3
  AND c.project_id = $4
  AND COALESCE(f.integrations, TRUE)
`

type GetMCPConnectionForCallParams struct {
	UserID       pgtype.UUID
	ToolName     string
	ConnectionID pgtype.UUID
	ProjectID    pgtype.UUID
}

type GetMCPConnectionForCallRow struct {
	Revision   string
	Service    string
	Permission string
	Tools      []byte
}

func (q *Queries) GetMCPConnectionForCall(ctx context.Context, arg GetMCPConnectionForCallParams) (GetMCPConnectionForCallRow, error) {
	row := q.db.QueryRow(ctx, getMCPConnectionForCall,
		arg.UserID,
		arg.ToolName,
		arg.ConnectionID,
		arg.ProjectID,
	)
	var i GetMCPConnectionForCallRow
	err := row.Scan(
		&i.Revision,
		&i.Service,
		&i.Permission,
		&i.Tools,
	)
	return i, err
}

const getProjectMCPConnectionByID = `-- name: GetProjectMCPConnectionByID :one
SELECT id, project_id, name, service, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
FROM project_mcp_connections
WHERE id = $1 AND project_id = $2
LIMIT 1
`

type GetProjectMCPConnectionByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

func (q *Queries) GetProjectMCPConnectionByID(ctx context.Context, arg GetProjectMCPConnectionByIDParams) (ProjectMcpConnection, error) {
	row := q.db.QueryRow(ctx, getProjectMCPConnectionByID, arg.ID, arg.ProjectID)
	var i ProjectMcpConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Service,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPConnectionsForTurn = `-- name: ListMCPConnectionsForTurn :many
SELECT c.id, c.project_id, c.name, c.service, c.endpoint_url, c.encrypted_token, c.revision::text AS revision, c.tools
FROM project_mcp_connections AS c
JOIN projects AS pr ON pr.id = c.project_id
JOIN organization_members AS om ON om.org_id = pr.organization_id AND om.user_id = $1
LEFT JOIN organization_features AS f ON f.org_id = pr.organization_id
WHERE c.project_id = $2
  AND COALESCE(f.integrations, TRUE)
ORDER BY c.name ASC, c.id ASC
`

type ListMCPConnectionsForTurnParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

type ListMCPConnectionsForTurnRow struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	Name           string
	Service        string
	EndpointUrl    string
	EncryptedToken string
	Revision       string
	Tools          []byte
}

func (q *Queries) ListMCPConnectionsForTurn(ctx context.Context, arg ListMCPConnectionsForTurnParams) ([]ListMCPConnectionsForTurnRow, error) {
	rows, err := q.db.Query(ctx, listMCPConnectionsForTurn, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPConnectionsForTurnRow
	for rows.Next() {
		var i ListMCPConnectionsForTurnRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Service,
			&i.EndpointUrl,
			&i.EncryptedToken,
			&i.Revision,
			&i.Tools,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPToolPermissionsForConnection = `-- name: ListMCPToolPermissionsForConnection :many
SELECT connection_id, tool_name, permission, updated_at
FROM project_mcp_tool_permissions
WHERE connection_id = $1
`

func (q *Queries) ListMCPToolPermissionsForConnection(ctx context.Context, connectionID pgtype.UUID) ([]ProjectMcpToolPermission, error) {
	rows, err := q.db.Query(ctx, listMCPToolPermissionsForConnection, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMcpToolPermission
	for rows.Next() {
		var i ProjectMcpToolPermission
		if err := rows.Scan(
			&i.ConnectionID,
			&i.ToolName,
			&i.Permission,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMCPConnectionsByProjectID = `-- name: ListProjectMCPConnectionsByProjectID :many
SELECT id, project_id, name, service, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
FROM project_mcp_connections
WHERE project_id = $1
ORDER BY name ASC, id ASC
`

func (q *Queries) ListProjectMCPConnectionsByProjectID(ctx context.Context, projectID pgtype.UUID) ([]ProjectMcpConnection, error) {
	rows, err := q.db.Query(ctx, listProjectMCPConnectionsByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMcpConnection
	for rows.Next() {
		var i ProjectMcpConnection
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Service,
			&i.EndpointUrl,
			&i.EncryptedToken,
			&i.Revision,
			&i.Tools,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProjectMCPConnectionByID = `-- name: LockProjectMCPConnectionByID :one
SELECT id, project_id, name, service, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
FROM project_mcp_connections
WHERE id = $1 AND project_id = $2
LIMIT 1
FOR UPDATE
`

type LockProjectMCPConnectionByIDParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
}

// Lock ordering with the decision, permission, and replace paths is always
// the connection row first, then approval rows, so concurrent writers
// serialize instead of deadlocking.
func (q *Queries) LockProjectMCPConnectionByID(ctx context.Context, arg LockProjectMCPConnectionByIDParams) (ProjectMcpConnection, error) {
	row := q.db.QueryRow(ctx, lockProjectMCPConnectionByID, arg.ID, arg.ProjectID)
	var i ProjectMcpConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Service,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameProjectMCPConnection = `-- name: RenameProjectMCPConnection :one
UPDATE project_mcp_connections
SET name = $3,
    updated_at = now()
WHERE id = $1
  AND project_id = $2
RETURNING id, project_id, name, service, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
`

type RenameProjectMCPConnectionParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Name      string
}

func (q *Queries) RenameProjectMCPConnection(ctx context.Context, arg RenameProjectMCPConnectionParams) (ProjectMcpConnection, error) {
	row := q.db.QueryRow(ctx, renameProjectMCPConnection, arg.ID, arg.ProjectID, arg.Name)
	var i ProjectMcpConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Service,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceProjectMCPConnection = `-- name: ReplaceProjectMCPConnection :one
UPDATE project_mcp_connections
SET name = $3,
    endpoint_url = $4,
    encrypted_token = $5,
    revision = gen_random_uuid(),
    tools = $6,
    last_checked_at = now(),
    updated_at = now()
WHERE id = $1
  AND project_id = $2
  AND revision = $7
RETURNING id, project_id, name, service, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
`

type ReplaceProjectMCPConnectionParams struct {
	ID             pgtype.UUID
	ProjectID      pgtype.UUID
	Name           string
	EndpointUrl    string
	EncryptedToken string
	Tools          []byte
	Revision       pgtype.UUID
}

func (q *Queries) ReplaceProjectMCPConnection(ctx context.Context, arg ReplaceProjectMCPConnectionParams) (ProjectMcpConnection, error) {
	row := q.db.QueryRow(ctx, replaceProjectMCPConnection,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.EndpointUrl,
		arg.EncryptedToken,
		arg.Tools,
		arg.Revision,
	)
	var i ProjectMcpConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Service,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectMCPConnectionChecked = `-- name: UpdateProjectMCPConnectionChecked :one
UPDATE project_mcp_connections
SET tools = $3,
    last_checked_at = now(),
    updated_at = now()
WHERE id = $1
  AND project_id = $2
  AND revision = $4
RETURNING id, project_id, name, service, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
`

type UpdateProjectMCPConnectionCheckedParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Tools     []byte
	Revision  pgtype.UUID
}

func (q *Queries) UpdateProjectMCPConnectionChecked(ctx context.Context, arg UpdateProjectMCPConnectionCheckedParams) (ProjectMcpConnection, error) {
	row := q.db.QueryRow(ctx, updateProjectMCPConnectionChecked,
		arg.ID,
		arg.ProjectID,
		arg.Tools,
		arg.Revision,
	)
	var i ProjectMcpConnection
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Service,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMCPToolPermission = `-- name: UpsertMCPToolPermission :exec
INSERT INTO project_mcp_tool_permissions (connection_id, tool_name, permission, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (connection_id, tool_name) DO UPDATE SET
    permission = excluded.permission,
    updated_at = now()
`

type UpsertMCPToolPermissionParams struct {
	ConnectionID pgtype.UUID
	ToolName     string
	Permission   string
}

func (q *Queries) UpsertMCPToolPermission(ctx context.Context, arg UpsertMCPToolPermissionParams) error {
	_, err := q.db.Exec(ctx, upsertMCPToolPermission, arg.ConnectionID, arg.ToolName, arg.Permission)
	return err
}
