// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Crawl struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	Status           string
	ConfigSnapshot   []byte
	SeoScore         pgtype.Int4
	AeoScore         pgtype.Int4
	PagespeedScore   pgtype.Int4
	OverallScore     pgtype.Int4
	StartedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UrlsDiscovered   int32
	UrlsCrawled      int32
	MaxDepthReached  int32
	GooglePsiResults []byte
	HasLlmsTxt       pgtype.Bool
}

type CrawlLink struct {
	ID           pgtype.UUID
	CrawlID      pgtype.UUID
	SourceUrl    string
	TargetUrl    string
	AnchorText   pgtype.Text
	IsInternal   pgtype.Bool
	TargetStatus pgtype.Int4
	Nofollow     pgtype.Bool
	CreatedAt    pgtype.Timestamptz
}

type CrawlPage struct {
	ID                      pgtype.UUID
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	CreatedAt               pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	BaseUrl        string
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	AuthProvider string
	AuthSubject  string
	Email        string
	Name         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
