// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	BaseUrl        string
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	AuthProvider string
	AuthSubject  string
	Email        string
	Name         pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
