// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiAudit struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	CrawlID      pgtype.UUID
	Status       string
	Score        pgtype.Int4
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AiAuditRun struct {
	ID                 pgtype.UUID
	AuditID            pgtype.UUID
	QuestionText       string
	DisplayOrder       int32
	ModelName          string
	Status             string
	RawResponse        pgtype.Text
	ParsedResponseJson []byte
	MentionedTarget    pgtype.Bool
	TargetRank         pgtype.Int4
	VisibilityScore    pgtype.Int4
	ErrorMessage       pgtype.Text
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AiConversation struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	CrawlID         pgtype.UUID
	CreatedByUserID pgtype.UUID
	Title           pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	OrgID           pgtype.UUID
}

type AiMessage struct {
	ID               pgtype.UUID
	ConversationID   pgtype.UUID
	Role             string
	Content          string
	CrawlID          pgtype.UUID
	Scope            []byte
	Model            pgtype.Text
	CreatedAt        pgtype.Timestamptz
	ReasoningContent pgtype.Text
	ToolCalls        []byte
	ToolCallID       pgtype.Text
	ToolName         pgtype.Text
}

type AiPromptConfig struct {
	ID                       int64
	ContextPrompt            string
	GuidelinesPrompt         string
	OtherNotesPrompt         string
	UpdatedByUserID          pgtype.UUID
	UpdatedAt                pgtype.Timestamptz
	QuestionGenerationPrompt string
}

type AiWorkerJob struct {
	ID           pgtype.UUID
	JobType      string
	ProjectID    pgtype.UUID
	Status       string
	ErrorMessage pgtype.Text
	StartedAt    pgtype.Timestamptz
	CompletedAt  pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	AuditID      pgtype.UUID
}

type Crawl struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	Status            string
	ConfigSnapshot    []byte
	SeoScore          pgtype.Int4
	AeoScore          pgtype.Int4
	PagespeedScore    pgtype.Int4
	OverallScore      pgtype.Int4
	StartedAt         pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UrlsDiscovered    int32
	UrlsCrawled       int32
	MaxDepthReached   int32
	GooglePsiResults  []byte
	HasLlmsTxt        pgtype.Bool
	RequestedByUserID pgtype.UUID
	Source            string
	Phase             pgtype.Text
}

type CrawlIssue struct {
	ID          pgtype.UUID
	CrawlID     pgtype.UUID
	CrawlPageID pgtype.UUID
	Url         string
	Severity    string
	Message     string
	Details     string
	CreatedAt   pgtype.Timestamptz
	Pillar      string
	Bucket      string
	IssueType   string
}

type CrawlLink struct {
	ID           pgtype.UUID
	CrawlID      pgtype.UUID
	SourceUrl    string
	TargetUrl    string
	AnchorText   pgtype.Text
	IsInternal   pgtype.Bool
	TargetStatus pgtype.Int4
	Nofollow     pgtype.Bool
	CreatedAt    pgtype.Timestamptz
}

type CrawlPage struct {
	ID                      pgtype.UUID
	CrawlID                 pgtype.UUID
	Url                     string
	StatusCode              pgtype.Int4
	ContentType             pgtype.Text
	SizeBytes               pgtype.Int4
	IsInternal              pgtype.Bool
	Depth                   pgtype.Int4
	Title                   pgtype.Text
	MetaDescription         pgtype.Text
	H1                      pgtype.Text
	H1Count                 pgtype.Int4
	H2Count                 pgtype.Int4
	H3Count                 pgtype.Int4
	WordCount               pgtype.Int4
	Author                  pgtype.Text
	CanonicalUrl            pgtype.Text
	Lang                    pgtype.Text
	Viewport                pgtype.Text
	Robots                  pgtype.Text
	ImageCount              pgtype.Int4
	ImagesWithoutAltCount   pgtype.Int4
	ImagesWithoutDimensions pgtype.Int4
	ExternalLinks           pgtype.Int4
	InternalLinks           pgtype.Int4
	ResponseTimeMs          pgtype.Int4
	JavascriptRendered      pgtype.Bool
	H2Headings              []byte
	H3Headings              []byte
	HeadingOutline          []byte
	OgTags                  []byte
	JsonLd                  []byte
	CreatedAt               pgtype.Timestamptz
	VisibleText             pgtype.Text
	ContentSha256           pgtype.Text
	Etag                    pgtype.Text
	LastModified            pgtype.Text
	Soft404                 bool
	FetchError              pgtype.Text
}

type CrawlScoreBreakdown struct {
	CrawlID        pgtype.UUID
	ScoringVersion string
	BreakdownJson  []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type GoogleConnection struct {
	ID                    pgtype.UUID
	OrganizationID        pgtype.UUID
	ConnectedByUserID     pgtype.UUID
	GoogleAccountEmail    pgtype.Text
	GoogleAccountSubject  pgtype.Text
	EncryptedRefreshToken string
	EncryptedAccessToken  pgtype.Text
	AccessTokenExpiresAt  pgtype.Timestamptz
	Scope                 string
	Status                string
	LastError             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type GoogleOauthState struct {
	ID             pgtype.UUID
	StateTokenHash string
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
	ProjectID      pgtype.UUID
	ReturnPath     string
	ExpiresAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationInvite struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	CreatedByUserID pgtype.UUID
	TokenHash       string
	MaxUses         int32
	UsedCount       int32
	ExpiresAt       pgtype.Timestamptz
	RevokedAt       pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type OrganizationMember struct {
	OrgID     pgtype.UUID
	UserID    pgtype.UUID
	Role      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	Name           string
	BaseUrl        string
	CreatedAt      pgtype.Timestamptz
}

type ProjectAiQuestion struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	Questions       []byte
	GenerationModel string
	GeneratedAt     pgtype.Timestamptz
}

type ProjectAutoCrawlSetting struct {
	ProjectID      pgtype.UUID
	Enabled        bool
	ConfigSnapshot []byte
	LastEnqueuedAt pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	FrequencyDays  int32
	RunAt          pgtype.Time
	Timezone       string
	NextRunAt      pgtype.Timestamptz
}

type ProjectBusinessProfile struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	BrandName           string
	WebsiteUrl          string
	PrimaryCategory     pgtype.Text
	PrimaryLocation     pgtype.Text
	BusinessDescription pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	SeedPrompts         []byte
}

type ProjectGscConnection struct {
	ID                 pgtype.UUID
	ProjectID          pgtype.UUID
	GoogleConnectionID pgtype.UUID
	SiteUrl            string
	PermissionLevel    pgtype.Text
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ScoringConfig struct {
	ID              int64
	ConfigJson      []byte
	UpdatedByUserID pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
}

type Session struct {
	ID                           pgtype.UUID
	UserID                       pgtype.UUID
	SessionTokenHash             string
	SupabaseAccessToken          string
	SupabaseRefreshToken         string
	SupabaseAccessTokenExpiresAt pgtype.Timestamptz
	ActiveOrgID                  pgtype.UUID
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	LastUsedAt                   pgtype.Timestamptz
	ExpiresAt                    pgtype.Timestamptz
	RevokedAt                    pgtype.Timestamptz
}

type User struct {
	ID               pgtype.UUID
	AuthProvider     string
	AuthSubject      string
	Email            string
	Name             pgtype.Text
	CreatedAt        pgtype.Timestamptz
	IsPlatformAdmin  bool
	Status           string
	SuspendedAt      pgtype.Timestamptz
	SuspensionReason pgtype.Text
}
