// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: org_invites.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationInvite = `-- name: CreateOrganizationInvite :one
INSERT INTO organization_invites (
    organization_id,
    created_by_user_id,
    token_hash,
    max_uses,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, organization_id, created_by_user_id, token_hash, max_uses, used_count, expires_at, revoked_at, created_at
`

type CreateOrganizationInviteParams struct {
	OrganizationID  pgtype.UUID
	CreatedByUserID pgtype.UUID
	TokenHash       string
	MaxUses         int32
	ExpiresAt       pgtype.Timestamptz
}

func (q *Queries) CreateOrganizationInvite(ctx context.Context, arg CreateOrganizationInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, createOrganizationInvite,
		arg.OrganizationID,
		arg.CreatedByUserID,
		arg.TokenHash,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.TokenHash,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationInviteByID = `-- name: GetOrganizationInviteByID :one
SELECT
    id,
    organization_id,
    created_by_user_id,
    token_hash,
    max_uses,
    used_count,
    expires_at,
    revoked_at,
    created_at
FROM organization_invites
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOrganizationInviteByID(ctx context.Context, id pgtype.UUID) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, getOrganizationInviteByID, id)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.TokenHash,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationInviteByTokenHash = `-- name: GetOrganizationInviteByTokenHash :one
SELECT
    oi.id,
    oi.organization_id,
    oi.created_by_user_id,
    oi.token_hash,
    oi.max_uses,
    oi.used_count,
    oi.expires_at,
    oi.revoked_at,
    oi.created_at,
    o.name AS organization_name
FROM organization_invites AS oi
INNER JOIN organizations AS o ON o.id = oi.organization_id
WHERE oi.token_hash = $1
LIMIT 1
`

type GetOrganizationInviteByTokenHashRow struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	CreatedByUserID  pgtype.UUID
	TokenHash        string
	MaxUses          int32
	UsedCount        int32
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	OrganizationName string
}

func (q *Queries) GetOrganizationInviteByTokenHash(ctx context.Context, tokenHash string) (GetOrganizationInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationInviteByTokenHash, tokenHash)
	var i GetOrganizationInviteByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.TokenHash,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.OrganizationName,
	)
	return i, err
}

const getOrganizationInviteByTokenHashForUpdate = `-- name: GetOrganizationInviteByTokenHashForUpdate :one
SELECT
    id,
    organization_id,
    created_by_user_id,
    token_hash,
    max_uses,
    used_count,
    expires_at,
    revoked_at,
    created_at
FROM organization_invites
WHERE token_hash = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetOrganizationInviteByTokenHashForUpdate(ctx context.Context, tokenHash string) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, getOrganizationInviteByTokenHashForUpdate, tokenHash)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.CreatedByUserID,
		&i.TokenHash,
		&i.MaxUses,
		&i.UsedCount,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOrganizationInviteUsedCount = `-- name: IncrementOrganizationInviteUsedCount :exec
UPDATE organization_invites
SET used_count = used_count + 1
WHERE id = $1
`

func (q *Queries) IncrementOrganizationInviteUsedCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementOrganizationInviteUsedCount, id)
	return err
}

const listOrganizationInvites = `-- name: ListOrganizationInvites :many
SELECT
    id,
    organization_id,
    created_by_user_id,
    token_hash,
    max_uses,
    used_count,
    expires_at,
    revoked_at,
    created_at
FROM organization_invites
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizationInvites(ctx context.Context, organizationID pgtype.UUID) ([]OrganizationInvite, error) {
	rows, err := q.db.Query(ctx, listOrganizationInvites, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationInvite
	for rows.Next() {
		var i OrganizationInvite
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.CreatedByUserID,
			&i.TokenHash,
			&i.MaxUses,
			&i.UsedCount,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOrganizationInvite = `-- name: RevokeOrganizationInvite :execrows
UPDATE organization_invites
SET revoked_at = now()
WHERE id = $1
  AND organization_id = $2
  AND revoked_at IS NULL
`

type RevokeOrganizationInviteParams struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) RevokeOrganizationInvite(ctx context.Context, arg RevokeOrganizationInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOrganizationInvite, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
