// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_features.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationFeatures = `-- name: GetOrganizationFeatures :one

SELECT
    COALESCE(f.auto_crawl, TRUE)::boolean AS auto_crawl,
    COALESCE(f.gsc_connector, TRUE)::boolean AS gsc_connector,
    COALESCE(f.ai_chat, TRUE)::boolean AS ai_chat,
    COALESCE(f.ai_use_internal_prompt, FALSE)::boolean AS ai_use_internal_prompt,
    COALESCE(f.ai_monthly_message_limit, 50)::integer AS ai_monthly_message_limit,
    COALESCE(f.ai_concurrent_turn_limit_per_user, 2)::integer AS ai_concurrent_turn_limit_per_user,
    COALESCE(f.ai_visibility_audit_monthly_limit, 10)::integer AS ai_visibility_audit_monthly_limit,
    COALESCE(
        f.ai_allowed_reasoning_efforts,
        ARRAY['none', 'low', 'high', 'max']::TEXT[]
    ) AS ai_allowed_reasoning_efforts
FROM organizations AS o
LEFT JOIN organization_features AS f ON f.org_id = o.id
WHERE o.id = $1
`

type GetOrganizationFeaturesRow struct {
	AutoCrawl                     bool
	GscConnector                  bool
	AiChat                        bool
	AiUseInternalPrompt           bool
	AiMonthlyMessageLimit         int32
	AiConcurrentTurnLimitPerUser  int32
	AiVisibilityAuditMonthlyLimit int32
	AiAllowedReasoningEfforts     []string
}

// A workspace with no organization_features row resolves to all features on.
func (q *Queries) GetOrganizationFeatures(ctx context.Context, orgID pgtype.UUID) (GetOrganizationFeaturesRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationFeatures, orgID)
	var i GetOrganizationFeaturesRow
	err := row.Scan(
		&i.AutoCrawl,
		&i.GscConnector,
		&i.AiChat,
		&i.AiUseInternalPrompt,
		&i.AiMonthlyMessageLimit,
		&i.AiConcurrentTurnLimitPerUser,
		&i.AiVisibilityAuditMonthlyLimit,
		&i.AiAllowedReasoningEfforts,
	)
	return i, err
}

const getOrganizationFeaturesByConversationID = `-- name: GetOrganizationFeaturesByConversationID :one
SELECT
    COALESCE(f.auto_crawl, TRUE)::boolean AS auto_crawl,
    COALESCE(f.gsc_connector, TRUE)::boolean AS gsc_connector,
    COALESCE(f.ai_chat, TRUE)::boolean AS ai_chat,
    COALESCE(f.ai_use_internal_prompt, FALSE)::boolean AS ai_use_internal_prompt,
    COALESCE(f.ai_monthly_message_limit, 50)::integer AS ai_monthly_message_limit,
    COALESCE(f.ai_concurrent_turn_limit_per_user, 2)::integer AS ai_concurrent_turn_limit_per_user,
    COALESCE(f.ai_visibility_audit_monthly_limit, 10)::integer AS ai_visibility_audit_monthly_limit,
    COALESCE(
        f.ai_allowed_reasoning_efforts,
        ARRAY['none', 'low', 'high', 'max']::TEXT[]
    ) AS ai_allowed_reasoning_efforts
FROM ai_conversations AS ac
INNER JOIN projects AS p ON p.id = ac.project_id
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    AND om.user_id = $1
LEFT JOIN organization_features AS f ON f.org_id = p.organization_id
WHERE ac.id = $2
`

type GetOrganizationFeaturesByConversationIDParams struct {
	UserID         pgtype.UUID
	ConversationID pgtype.UUID
}

type GetOrganizationFeaturesByConversationIDRow struct {
	AutoCrawl                     bool
	GscConnector                  bool
	AiChat                        bool
	AiUseInternalPrompt           bool
	AiMonthlyMessageLimit         int32
	AiConcurrentTurnLimitPerUser  int32
	AiVisibilityAuditMonthlyLimit int32
	AiAllowedReasoningEfforts     []string
}

func (q *Queries) GetOrganizationFeaturesByConversationID(ctx context.Context, arg GetOrganizationFeaturesByConversationIDParams) (GetOrganizationFeaturesByConversationIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationFeaturesByConversationID, arg.UserID, arg.ConversationID)
	var i GetOrganizationFeaturesByConversationIDRow
	err := row.Scan(
		&i.AutoCrawl,
		&i.GscConnector,
		&i.AiChat,
		&i.AiUseInternalPrompt,
		&i.AiMonthlyMessageLimit,
		&i.AiConcurrentTurnLimitPerUser,
		&i.AiVisibilityAuditMonthlyLimit,
		&i.AiAllowedReasoningEfforts,
	)
	return i, err
}

const getOrganizationFeaturesByProjectID = `-- name: GetOrganizationFeaturesByProjectID :one
SELECT
    COALESCE(f.auto_crawl, TRUE)::boolean AS auto_crawl,
    COALESCE(f.gsc_connector, TRUE)::boolean AS gsc_connector,
    COALESCE(f.ai_chat, TRUE)::boolean AS ai_chat,
    COALESCE(f.ai_use_internal_prompt, FALSE)::boolean AS ai_use_internal_prompt,
    COALESCE(f.ai_monthly_message_limit, 50)::integer AS ai_monthly_message_limit,
    COALESCE(f.ai_concurrent_turn_limit_per_user, 2)::integer AS ai_concurrent_turn_limit_per_user,
    COALESCE(f.ai_visibility_audit_monthly_limit, 10)::integer AS ai_visibility_audit_monthly_limit,
    COALESCE(
        f.ai_allowed_reasoning_efforts,
        ARRAY['none', 'low', 'high', 'max']::TEXT[]
    ) AS ai_allowed_reasoning_efforts
FROM projects AS p
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    AND om.user_id = $1
LEFT JOIN organization_features AS f ON f.org_id = p.organization_id
WHERE p.id = $2
`

type GetOrganizationFeaturesByProjectIDParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
}

type GetOrganizationFeaturesByProjectIDRow struct {
	AutoCrawl                     bool
	GscConnector                  bool
	AiChat                        bool
	AiUseInternalPrompt           bool
	AiMonthlyMessageLimit         int32
	AiConcurrentTurnLimitPerUser  int32
	AiVisibilityAuditMonthlyLimit int32
	AiAllowedReasoningEfforts     []string
}

func (q *Queries) GetOrganizationFeaturesByProjectID(ctx context.Context, arg GetOrganizationFeaturesByProjectIDParams) (GetOrganizationFeaturesByProjectIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationFeaturesByProjectID, arg.UserID, arg.ProjectID)
	var i GetOrganizationFeaturesByProjectIDRow
	err := row.Scan(
		&i.AutoCrawl,
		&i.GscConnector,
		&i.AiChat,
		&i.AiUseInternalPrompt,
		&i.AiMonthlyMessageLimit,
		&i.AiConcurrentTurnLimitPerUser,
		&i.AiVisibilityAuditMonthlyLimit,
		&i.AiAllowedReasoningEfforts,
	)
	return i, err
}

const listOrganizationFeaturesForAdmin = `-- name: ListOrganizationFeaturesForAdmin :many
SELECT
    o.id AS org_id,
    o.name AS org_name,
    COALESCE(f.auto_crawl, TRUE)::boolean AS auto_crawl,
    COALESCE(f.gsc_connector, TRUE)::boolean AS gsc_connector,
    COALESCE(f.ai_chat, TRUE)::boolean AS ai_chat,
    COALESCE(f.ai_use_internal_prompt, FALSE)::boolean AS ai_use_internal_prompt,
    COALESCE(f.ai_monthly_message_limit, 50)::integer AS ai_monthly_message_limit,
    COALESCE(f.ai_concurrent_turn_limit_per_user, 2)::integer AS ai_concurrent_turn_limit_per_user,
    COALESCE(f.ai_visibility_audit_monthly_limit, 10)::integer AS ai_visibility_audit_monthly_limit,
    COALESCE(
        f.ai_allowed_reasoning_efforts,
        ARRAY['none', 'low', 'high', 'max']::TEXT[]
    ) AS ai_allowed_reasoning_efforts,
    COALESCE(f.disabled_ai_tools, ARRAY[]::TEXT[]) AS disabled_ai_tools,
    f.updated_at
FROM organizations AS o
LEFT JOIN organization_features AS f ON f.org_id = o.id
ORDER BY o.name ASC
`

type ListOrganizationFeaturesForAdminRow struct {
	OrgID                         pgtype.UUID
	OrgName                       string
	AutoCrawl                     bool
	GscConnector                  bool
	AiChat                        bool
	AiUseInternalPrompt           bool
	AiMonthlyMessageLimit         int32
	AiConcurrentTurnLimitPerUser  int32
	AiVisibilityAuditMonthlyLimit int32
	AiAllowedReasoningEfforts     []string
	DisabledAiTools               []string
	UpdatedAt                     pgtype.Timestamptz
}

func (q *Queries) ListOrganizationFeaturesForAdmin(ctx context.Context) ([]ListOrganizationFeaturesForAdminRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationFeaturesForAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationFeaturesForAdminRow
	for rows.Next() {
		var i ListOrganizationFeaturesForAdminRow
		if err := rows.Scan(
			&i.OrgID,
			&i.OrgName,
			&i.AutoCrawl,
			&i.GscConnector,
			&i.AiChat,
			&i.AiUseInternalPrompt,
			&i.AiMonthlyMessageLimit,
			&i.AiConcurrentTurnLimitPerUser,
			&i.AiVisibilityAuditMonthlyLimit,
			&i.AiAllowedReasoningEfforts,
			&i.DisabledAiTools,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrganizationFeatures = `-- name: UpsertOrganizationFeatures :exec
INSERT INTO organization_features (
    org_id, auto_crawl, gsc_connector, ai_chat, ai_use_internal_prompt,
    ai_monthly_message_limit, ai_concurrent_turn_limit_per_user,
    ai_visibility_audit_monthly_limit, ai_allowed_reasoning_efforts,
    disabled_ai_tools, updated_by_user_id, updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    ARRAY(
        SELECT effort
        FROM unnest($9::TEXT[]) AS effort
        ORDER BY array_position(ARRAY['none', 'low', 'high', 'max']::TEXT[], effort)
    ),
    COALESCE($10::TEXT[], ARRAY[]::TEXT[]),
    $11,
    now()
)
ON CONFLICT (org_id) DO UPDATE SET
    auto_crawl = EXCLUDED.auto_crawl,
    gsc_connector = EXCLUDED.gsc_connector,
    ai_chat = EXCLUDED.ai_chat,
    ai_use_internal_prompt = EXCLUDED.ai_use_internal_prompt,
    ai_monthly_message_limit = EXCLUDED.ai_monthly_message_limit,
    ai_concurrent_turn_limit_per_user = EXCLUDED.ai_concurrent_turn_limit_per_user,
    ai_visibility_audit_monthly_limit = EXCLUDED.ai_visibility_audit_monthly_limit,
    ai_allowed_reasoning_efforts = EXCLUDED.ai_allowed_reasoning_efforts,
    disabled_ai_tools = EXCLUDED.disabled_ai_tools,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = now()
`

type UpsertOrganizationFeaturesParams struct {
	OrgID                         pgtype.UUID
	AutoCrawl                     bool
	GscConnector                  bool
	AiChat                        bool
	AiUseInternalPrompt           bool
	AiMonthlyMessageLimit         int32
	AiConcurrentTurnLimitPerUser  int32
	AiVisibilityAuditMonthlyLimit int32
	AiAllowedReasoningEfforts     []string
	DisabledAiTools               []string
	UpdatedByUserID               pgtype.UUID
}

func (q *Queries) UpsertOrganizationFeatures(ctx context.Context, arg UpsertOrganizationFeaturesParams) error {
	_, err := q.db.Exec(ctx, upsertOrganizationFeatures,
		arg.OrgID,
		arg.AutoCrawl,
		arg.GscConnector,
		arg.AiChat,
		arg.AiUseInternalPrompt,
		arg.AiMonthlyMessageLimit,
		arg.AiConcurrentTurnLimitPerUser,
		arg.AiVisibilityAuditMonthlyLimit,
		arg.AiAllowedReasoningEfforts,
		arg.DisabledAiTools,
		arg.UpdatedByUserID,
	)
	return err
}
