// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOrganizationEventsBefore = `-- name: DeleteOrganizationEventsBefore :execrows
DELETE FROM organization_events
WHERE id IN (
    SELECT oe.id FROM organization_events AS oe
    WHERE oe.created_at < $1
    ORDER BY oe.id ASC
    LIMIT $2
)
`

type DeleteOrganizationEventsBeforeParams struct {
	Cutoff    pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) DeleteOrganizationEventsBefore(ctx context.Context, arg DeleteOrganizationEventsBeforeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOrganizationEventsBefore, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrganizationEventHeadForUser = `-- name: GetOrganizationEventHeadForUser :one
SELECT COALESCE(MAX(oe.id), 0)::bigint AS head
FROM organization_events AS oe
INNER JOIN organization_members AS om
    ON om.org_id = oe.organization_id
   AND om.user_id = $1
WHERE oe.organization_id = $2
`

type GetOrganizationEventHeadForUserParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
}

func (q *Queries) GetOrganizationEventHeadForUser(ctx context.Context, arg GetOrganizationEventHeadForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, getOrganizationEventHeadForUser, arg.UserID, arg.OrganizationID)
	var head int64
	err := row.Scan(&head)
	return head, err
}

const listOrganizationEventsForUser = `-- name: ListOrganizationEventsForUser :many
SELECT
    oe.id,
    oe.organization_id,
    oe.project_id,
    oe.event_type,
    oe.resource_id,
    oe.payload,
    oe.created_at
FROM organization_events AS oe
INNER JOIN organization_members AS om
    ON om.org_id = oe.organization_id
   AND om.user_id = $1
WHERE oe.organization_id = $2
  AND oe.id > $3
ORDER BY oe.id ASC
LIMIT $4
`

type ListOrganizationEventsForUserParams struct {
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	AfterID        int64
	MaxRows        int32
}

func (q *Queries) ListOrganizationEventsForUser(ctx context.Context, arg ListOrganizationEventsForUserParams) ([]OrganizationEvent, error) {
	rows, err := q.db.Query(ctx, listOrganizationEventsForUser,
		arg.UserID,
		arg.OrganizationID,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrganizationEvent
	for rows.Next() {
		var i OrganizationEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.EventType,
			&i.ResourceID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryOrganizationEventsCleanupLock = `-- name: TryOrganizationEventsCleanupLock :one
SELECT pg_try_advisory_xact_lock(918273645, 1) AS locked
`

func (q *Queries) TryOrganizationEventsCleanupLock(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, tryOrganizationEventsCleanupLock)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
