// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_setup.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceProjectSetupFromCrawling = `-- name: AdvanceProjectSetupFromCrawling :one
UPDATE project_setup
SET status = $1,
    error = $2,
    failed_step = $3,
    updated_at = now(),
    completed_at = CASE WHEN $1 IN ('completed', 'failed') THEN now() ELSE NULL END
WHERE crawl_id = $4
  AND status = 'crawling'
RETURNING id, organization_id, project_id, requested_by_user_id, crawl_id, status, error, failed_step, visibility_skip_reason, created_at, updated_at, completed_at
`

type AdvanceProjectSetupFromCrawlingParams struct {
	Status     string
	Error      pgtype.Text
	FailedStep pgtype.Text
	CrawlID    pgtype.UUID
}

// Crawl-to-profile transition used by crawl finalization. The WHERE clause is
// the idempotency guard: only a setup still in 'crawling' linked to this exact
// crawl can move, so duplicate terminal handling and unrelated crawls update
// zero rows (pgx.ErrNoRows). Callers enqueue the profile bootstrap job only when
// a row is returned, inside the same transaction as the crawl status write.
func (q *Queries) AdvanceProjectSetupFromCrawling(ctx context.Context, arg AdvanceProjectSetupFromCrawlingParams) (ProjectSetup, error) {
	row := q.db.QueryRow(ctx, advanceProjectSetupFromCrawling,
		arg.Status,
		arg.Error,
		arg.FailedStep,
		arg.CrawlID,
	)
	var i ProjectSetup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.CrawlID,
		&i.Status,
		&i.Error,
		&i.FailedStep,
		&i.VisibilitySkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createProjectSetup = `-- name: CreateProjectSetup :one
INSERT INTO project_setup (
    organization_id,
    project_id,
    requested_by_user_id,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4
)
ON CONFLICT (project_id) DO NOTHING
RETURNING id, organization_id, project_id, requested_by_user_id, crawl_id, status, error, failed_step, visibility_skip_reason, created_at, updated_at, completed_at
`

type CreateProjectSetupParams struct {
	OrganizationID    pgtype.UUID
	ProjectID         pgtype.UUID
	RequestedByUserID pgtype.UUID
	Status            string
}

// Insert-only: the unique project_id index makes a re-click a no-op, so calling
// this twice never creates a second setup row.
func (q *Queries) CreateProjectSetup(ctx context.Context, arg CreateProjectSetupParams) (ProjectSetup, error) {
	row := q.db.QueryRow(ctx, createProjectSetup,
		arg.OrganizationID,
		arg.ProjectID,
		arg.RequestedByUserID,
		arg.Status,
	)
	var i ProjectSetup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.CrawlID,
		&i.Status,
		&i.Error,
		&i.FailedStep,
		&i.VisibilitySkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProjectSetupByProjectID = `-- name: GetProjectSetupByProjectID :one
SELECT
    id,
    organization_id,
    project_id,
    requested_by_user_id,
    crawl_id,
    status,
    error,
    failed_step,
    visibility_skip_reason,
    created_at,
    updated_at,
    completed_at
FROM project_setup
WHERE project_id = $1
LIMIT 1
`

func (q *Queries) GetProjectSetupByProjectID(ctx context.Context, projectID pgtype.UUID) (ProjectSetup, error) {
	row := q.db.QueryRow(ctx, getProjectSetupByProjectID, projectID)
	var i ProjectSetup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.CrawlID,
		&i.Status,
		&i.Error,
		&i.FailedStep,
		&i.VisibilitySkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getProjectSetupByProjectIDForUpdate = `-- name: GetProjectSetupByProjectIDForUpdate :one
SELECT
    id,
    organization_id,
    project_id,
    requested_by_user_id,
    crawl_id,
    status,
    error,
    failed_step,
    visibility_skip_reason,
    created_at,
    updated_at,
    completed_at
FROM project_setup
WHERE project_id = $1
LIMIT 1
FOR UPDATE
`

// Row-locks the setup for the duration of a worker transaction so two workers
// cannot both advance the same setup step. The guard lives in
// UpdateProjectSetupStatus(expected_status); this only serializes the decision.
func (q *Queries) GetProjectSetupByProjectIDForUpdate(ctx context.Context, projectID pgtype.UUID) (ProjectSetup, error) {
	row := q.db.QueryRow(ctx, getProjectSetupByProjectIDForUpdate, projectID)
	var i ProjectSetup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.CrawlID,
		&i.Status,
		&i.Error,
		&i.FailedStep,
		&i.VisibilitySkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const startProjectSetup = `-- name: StartProjectSetup :one
UPDATE project_setup
SET requested_by_user_id = $1,
    status = 'crawling',
    crawl_id = $2,
    error = NULL,
    failed_step = NULL,
    visibility_skip_reason = NULL,
    completed_at = NULL,
    updated_at = now()
WHERE project_id = $3
  AND status = 'ready'
RETURNING id, organization_id, project_id, requested_by_user_id, crawl_id, status, error, failed_step, visibility_skip_reason, created_at, updated_at, completed_at
`

type StartProjectSetupParams struct {
	RequestedByUserID pgtype.UUID
	CrawlID           pgtype.UUID
	ProjectID         pgtype.UUID
}

// Ready-to-crawling start used by the owner's setup POST. It stamps the acting
// owner as requested_by_user_id and links the first crawl in one guarded
// UPDATE. The status = 'ready' guard makes a concurrent or repeated start
// update zero rows (pgx.ErrNoRows), so the crawl it was handed rolls back
// with the transaction and never leaks.
func (q *Queries) StartProjectSetup(ctx context.Context, arg StartProjectSetupParams) (ProjectSetup, error) {
	row := q.db.QueryRow(ctx, startProjectSetup, arg.RequestedByUserID, arg.CrawlID, arg.ProjectID)
	var i ProjectSetup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.CrawlID,
		&i.Status,
		&i.Error,
		&i.FailedStep,
		&i.VisibilitySkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateProjectSetupStatus = `-- name: UpdateProjectSetupStatus :one
UPDATE project_setup
SET status = $1,
    -- A retry by a different current owner re-stamps the requester; worker
    -- transitions leave it NULL and keep the existing owner. Later profile and
    -- feature checks then never run as a stale or deleted user.
    requested_by_user_id = COALESCE($2, requested_by_user_id),
    error = CASE WHEN $1 = 'failed' THEN $3 ELSE NULL END,
    failed_step = CASE WHEN $1 = 'failed' THEN $4 ELSE NULL END,
    visibility_skip_reason = $5,
    crawl_id = COALESCE($6, crawl_id),
    updated_at = now(),
    completed_at = CASE WHEN $1 IN ('completed', 'failed') THEN now() ELSE NULL END
WHERE project_id = $7
  AND status = $8
RETURNING id, organization_id, project_id, requested_by_user_id, crawl_id, status, error, failed_step, visibility_skip_reason, created_at, updated_at, completed_at
`

type UpdateProjectSetupStatusParams struct {
	Status               string
	RequestedByUserID    pgtype.UUID
	Error                pgtype.Text
	FailedStep           pgtype.Text
	VisibilitySkipReason pgtype.Text
	CrawlID              pgtype.UUID
	ProjectID            pgtype.UUID
	ExpectedStatus       string
}

// Worker entry point for non-crawl transitions. The expected_status guard makes
// a stale or out-of-order event update zero rows instead of moving the workflow
// backward. Non-failed transitions clear the prior error, failed_step and
// completed_at; a failed transition keeps the supplied failed_step and error and
// stamps completed_at.
func (q *Queries) UpdateProjectSetupStatus(ctx context.Context, arg UpdateProjectSetupStatusParams) (ProjectSetup, error) {
	row := q.db.QueryRow(ctx, updateProjectSetupStatus,
		arg.Status,
		arg.RequestedByUserID,
		arg.Error,
		arg.FailedStep,
		arg.VisibilitySkipReason,
		arg.CrawlID,
		arg.ProjectID,
		arg.ExpectedStatus,
	)
	var i ProjectSetup
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.RequestedByUserID,
		&i.CrawlID,
		&i.Status,
		&i.Error,
		&i.FailedStep,
		&i.VisibilitySkipReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
