// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_ai_questions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectAIQuestions = `-- name: GetProjectAIQuestions :one
SELECT id, project_id, questions, location_questions, generation_model, generated_at
FROM project_ai_questions
WHERE project_id = $1
`

type GetProjectAIQuestionsRow struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	Questions         []byte
	LocationQuestions []byte
	GenerationModel   string
	GeneratedAt       pgtype.Timestamptz
}

func (q *Queries) GetProjectAIQuestions(ctx context.Context, projectID pgtype.UUID) (GetProjectAIQuestionsRow, error) {
	row := q.db.QueryRow(ctx, getProjectAIQuestions, projectID)
	var i GetProjectAIQuestionsRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Questions,
		&i.LocationQuestions,
		&i.GenerationModel,
		&i.GeneratedAt,
	)
	return i, err
}

const upsertProjectAIQuestions = `-- name: UpsertProjectAIQuestions :one
INSERT INTO project_ai_questions (project_id, questions, location_questions, generation_model)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id) DO UPDATE SET
    questions = EXCLUDED.questions,
    location_questions = EXCLUDED.location_questions,
    generation_model = EXCLUDED.generation_model,
    generated_at = NOW()
RETURNING id, project_id, questions, location_questions, generation_model, generated_at
`

type UpsertProjectAIQuestionsParams struct {
	ProjectID         pgtype.UUID
	Questions         []byte
	LocationQuestions []byte
	GenerationModel   string
}

type UpsertProjectAIQuestionsRow struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	Questions         []byte
	LocationQuestions []byte
	GenerationModel   string
	GeneratedAt       pgtype.Timestamptz
}

func (q *Queries) UpsertProjectAIQuestions(ctx context.Context, arg UpsertProjectAIQuestionsParams) (UpsertProjectAIQuestionsRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectAIQuestions,
		arg.ProjectID,
		arg.Questions,
		arg.LocationQuestions,
		arg.GenerationModel,
	)
	var i UpsertProjectAIQuestionsRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Questions,
		&i.LocationQuestions,
		&i.GenerationModel,
		&i.GeneratedAt,
	)
	return i, err
}
