// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    organization_id,
    name,
    base_url
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, organization_id, name, base_url, created_at
`

type CreateProjectParams struct {
	OrganizationID pgtype.UUID
	Name           string
	BaseUrl        string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrganizationID, arg.Name, arg.BaseUrl)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.BaseUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectByIDForUser = `-- name: DeleteProjectByIDForUser :execrows
DELETE FROM projects AS p
USING organization_members AS om
WHERE p.id = $1
  AND om.org_id = p.organization_id
  AND om.user_id = $2
`

type DeleteProjectByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteProjectByIDForUser(ctx context.Context, arg DeleteProjectByIDForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectByIDForUser, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectByIDForUser = `-- name: GetProjectByIDForUser :one
SELECT
    p.id,
    p.organization_id,
    p.name,
    p.base_url,
    p.created_at
FROM projects AS p
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE p.id = $1
  AND om.user_id = $2
LIMIT 1
`

type GetProjectByIDForUserParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetProjectByIDForUser(ctx context.Context, arg GetProjectByIDForUserParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDForUser, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.BaseUrl,
		&i.CreatedAt,
	)
	return i, err
}

const hasActiveCrawlForProject = `-- name: HasActiveCrawlForProject :one
SELECT EXISTS (
    SELECT 1
    FROM crawls AS c
    INNER JOIN projects AS p ON p.id = c.project_id
    INNER JOIN organization_members AS om ON om.org_id = p.organization_id
    WHERE c.project_id = $1
      AND om.user_id = $2
      AND c.status IN ('queued', 'running')
) AS has_active_crawl
`

type HasActiveCrawlForProjectParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) HasActiveCrawlForProject(ctx context.Context, arg HasActiveCrawlForProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveCrawlForProject, arg.ProjectID, arg.UserID)
	var has_active_crawl bool
	err := row.Scan(&has_active_crawl)
	return has_active_crawl, err
}

const listProjectsForOrganization = `-- name: ListProjectsForOrganization :many
SELECT
    p.id,
    p.organization_id,
    p.name,
    p.base_url,
    p.created_at
FROM projects AS p
WHERE p.organization_id = $1
ORDER BY p.created_at ASC
`

func (q *Queries) ListProjectsForOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.BaseUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForOrganizationForUser = `-- name: ListProjectsForOrganizationForUser :many
SELECT
    p.id,
    p.organization_id,
    p.name,
    p.base_url,
    p.created_at
FROM projects AS p
INNER JOIN organization_members AS om ON om.org_id = p.organization_id
WHERE p.organization_id = $1
  AND om.user_id = $2
ORDER BY p.created_at ASC
`

type ListProjectsForOrganizationForUserParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) ListProjectsForOrganizationForUser(ctx context.Context, arg ListProjectsForOrganizationForUserParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForOrganizationForUser, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.BaseUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
