// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_ai_questions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectAIQuestions = `-- name: GetProjectAIQuestions :one
SELECT id, project_id, questions, generation_model, generated_at
FROM project_ai_questions
WHERE project_id = $1
`

func (q *Queries) GetProjectAIQuestions(ctx context.Context, projectID pgtype.UUID) (ProjectAiQuestion, error) {
	row := q.db.QueryRow(ctx, getProjectAIQuestions, projectID)
	var i ProjectAiQuestion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Questions,
		&i.GenerationModel,
		&i.GeneratedAt,
	)
	return i, err
}

const upsertProjectAIQuestions = `-- name: UpsertProjectAIQuestions :one
INSERT INTO project_ai_questions (project_id, questions, generation_model)
VALUES ($1, $2, $3)
ON CONFLICT (project_id) DO UPDATE SET
    questions = EXCLUDED.questions,
    generation_model = EXCLUDED.generation_model,
    generated_at = NOW()
RETURNING id, project_id, questions, generation_model, generated_at
`

type UpsertProjectAIQuestionsParams struct {
	ProjectID       pgtype.UUID
	Questions       []byte
	GenerationModel string
}

func (q *Queries) UpsertProjectAIQuestions(ctx context.Context, arg UpsertProjectAIQuestionsParams) (ProjectAiQuestion, error) {
	row := q.db.QueryRow(ctx, upsertProjectAIQuestions, arg.ProjectID, arg.Questions, arg.GenerationModel)
	var i ProjectAiQuestion
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Questions,
		&i.GenerationModel,
		&i.GeneratedAt,
	)
	return i, err
}
