// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runecms.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProjectRuneConnectionByProjectID = `-- name: DeleteProjectRuneConnectionByProjectID :execrows
DELETE FROM project_rune_connections
WHERE project_id = $1
`

func (q *Queries) DeleteProjectRuneConnectionByProjectID(ctx context.Context, projectID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProjectRuneConnectionByProjectID, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectRuneConnectionByProjectID = `-- name: GetProjectRuneConnectionByProjectID :one
SELECT project_id, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
FROM project_rune_connections
WHERE project_id = $1
LIMIT 1
`

func (q *Queries) GetProjectRuneConnectionByProjectID(ctx context.Context, projectID pgtype.UUID) (ProjectRuneConnection, error) {
	row := q.db.QueryRow(ctx, getProjectRuneConnectionByProjectID, projectID)
	var i ProjectRuneConnection
	err := row.Scan(
		&i.ProjectID,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectRuneConnectionChecked = `-- name: UpdateProjectRuneConnectionChecked :one
UPDATE project_rune_connections
SET tools = $2,
    last_checked_at = now(),
    updated_at = now()
WHERE project_id = $1
  AND revision = $3
RETURNING project_id, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
`

type UpdateProjectRuneConnectionCheckedParams struct {
	ProjectID pgtype.UUID
	Tools     []byte
	Revision  pgtype.UUID
}

func (q *Queries) UpdateProjectRuneConnectionChecked(ctx context.Context, arg UpdateProjectRuneConnectionCheckedParams) (ProjectRuneConnection, error) {
	row := q.db.QueryRow(ctx, updateProjectRuneConnectionChecked, arg.ProjectID, arg.Tools, arg.Revision)
	var i ProjectRuneConnection
	err := row.Scan(
		&i.ProjectID,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProjectRuneConnection = `-- name: UpsertProjectRuneConnection :one
INSERT INTO project_rune_connections (
    project_id,
    endpoint_url,
    encrypted_token,
    tools,
    last_checked_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    now()
)
ON CONFLICT (project_id) DO UPDATE SET
    endpoint_url = excluded.endpoint_url,
    encrypted_token = excluded.encrypted_token,
    revision = gen_random_uuid(),
    tools = excluded.tools,
    last_checked_at = excluded.last_checked_at,
    updated_at = now()
RETURNING project_id, endpoint_url, encrypted_token, revision, tools, last_checked_at, created_at, updated_at
`

type UpsertProjectRuneConnectionParams struct {
	ProjectID      pgtype.UUID
	EndpointUrl    string
	EncryptedToken string
	Tools          []byte
}

func (q *Queries) UpsertProjectRuneConnection(ctx context.Context, arg UpsertProjectRuneConnectionParams) (ProjectRuneConnection, error) {
	row := q.db.QueryRow(ctx, upsertProjectRuneConnection,
		arg.ProjectID,
		arg.EndpointUrl,
		arg.EncryptedToken,
		arg.Tools,
	)
	var i ProjectRuneConnection
	err := row.Scan(
		&i.ProjectID,
		&i.EndpointUrl,
		&i.EncryptedToken,
		&i.Revision,
		&i.Tools,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
