// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scoring_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveScoringConfig = `-- name: GetActiveScoringConfig :one
SELECT id, config_json, updated_by_user_id, updated_at
FROM scoring_configs
WHERE id = 1
`

func (q *Queries) GetActiveScoringConfig(ctx context.Context) (ScoringConfig, error) {
	row := q.db.QueryRow(ctx, getActiveScoringConfig)
	var i ScoringConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigJson,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertActiveScoringConfig = `-- name: UpsertActiveScoringConfig :one
INSERT INTO scoring_configs (
    id,
    config_json,
    updated_by_user_id
) VALUES (
    1,
    $1,
    $2
)
ON CONFLICT (id) DO UPDATE SET
    config_json = EXCLUDED.config_json,
    updated_by_user_id = EXCLUDED.updated_by_user_id,
    updated_at = NOW()
RETURNING id, config_json, updated_by_user_id, updated_at
`

type UpsertActiveScoringConfigParams struct {
	ConfigJson      []byte
	UpdatedByUserID pgtype.UUID
}

func (q *Queries) UpsertActiveScoringConfig(ctx context.Context, arg UpsertActiveScoringConfigParams) (ScoringConfig, error) {
	row := q.db.QueryRow(ctx, upsertActiveScoringConfig, arg.ConfigJson, arg.UpdatedByUserID)
	var i ScoringConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigJson,
		&i.UpdatedByUserID,
		&i.UpdatedAt,
	)
	return i, err
}
