// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id,
    session_token_hash,
    supabase_access_token,
    supabase_refresh_token,
    supabase_access_token_expires_at,
    active_org_id,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, user_id, session_token_hash, supabase_access_token, supabase_refresh_token, supabase_access_token_expires_at, active_org_id, created_at, updated_at, last_used_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID                       pgtype.UUID
	SessionTokenHash             string
	SupabaseAccessToken          string
	SupabaseRefreshToken         string
	SupabaseAccessTokenExpiresAt pgtype.Timestamptz
	ActiveOrgID                  pgtype.UUID
	ExpiresAt                    pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.SessionTokenHash,
		arg.SupabaseAccessToken,
		arg.SupabaseRefreshToken,
		arg.SupabaseAccessTokenExpiresAt,
		arg.ActiveOrgID,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.SupabaseAccessToken,
		&i.SupabaseRefreshToken,
		&i.SupabaseAccessTokenExpiresAt,
		&i.ActiveOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    id,
    user_id,
    session_token_hash,
    supabase_access_token,
    supabase_refresh_token,
    supabase_access_token_expires_at,
    active_org_id,
    created_at,
    updated_at,
    last_used_at,
    expires_at,
    revoked_at
FROM sessions
WHERE session_token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, sessionTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, sessionTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.SupabaseAccessToken,
		&i.SupabaseRefreshToken,
		&i.SupabaseAccessTokenExpiresAt,
		&i.ActiveOrgID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions
SET revoked_at = now(),
    updated_at = now(),
    last_used_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now(),
    updated_at = now(),
    last_used_at = now()
WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const updateSessionActiveOrganization = `-- name: UpdateSessionActiveOrganization :exec
UPDATE sessions
SET active_org_id = $2,
    updated_at = now(),
    last_used_at = now()
WHERE id = $1 AND user_id = $3
`

type UpdateSessionActiveOrganizationParams struct {
	ID          pgtype.UUID
	ActiveOrgID pgtype.UUID
	UserID      pgtype.UUID
}

func (q *Queries) UpdateSessionActiveOrganization(ctx context.Context, arg UpdateSessionActiveOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateSessionActiveOrganization, arg.ID, arg.ActiveOrgID, arg.UserID)
	return err
}

const updateSessionTokens = `-- name: UpdateSessionTokens :exec
UPDATE sessions
SET supabase_access_token = $2,
    supabase_refresh_token = $3,
    supabase_access_token_expires_at = $4,
    updated_at = now(),
    last_used_at = now()
WHERE id = $1
`

type UpdateSessionTokensParams struct {
	ID                           pgtype.UUID
	SupabaseAccessToken          string
	SupabaseRefreshToken         string
	SupabaseAccessTokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpdateSessionTokens(ctx context.Context, arg UpdateSessionTokensParams) error {
	_, err := q.db.Exec(ctx, updateSessionTokens,
		arg.ID,
		arg.SupabaseAccessToken,
		arg.SupabaseRefreshToken,
		arg.SupabaseAccessTokenExpiresAt,
	)
	return err
}
