// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    auth_provider,
    auth_subject,
    email,
    name
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, auth_provider, auth_subject, email, name, created_at
`

type CreateUserParams struct {
	AuthProvider string
	AuthSubject  string
	Email        string
	Name         pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.AuthProvider,
		arg.AuthSubject,
		arg.Email,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByAuthSubject = `-- name: GetUserByAuthSubject :one
SELECT id, auth_provider, auth_subject, email, name, created_at
FROM users
WHERE auth_provider = $1 AND auth_subject = $2
LIMIT 1
`

type GetUserByAuthSubjectParams struct {
	AuthProvider string
	AuthSubject  string
}

func (q *Queries) GetUserByAuthSubject(ctx context.Context, arg GetUserByAuthSubjectParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthSubject, arg.AuthProvider, arg.AuthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
