@supabase_url = https://bxqpoqsaiznfwfmernyv.supabase.co
@supabase_anon_key = sb_publishable_kK00_LANb8I7VwSAQrzpFQ_t1WhQ2_z 
@email1 = wizardly.ways.69@gmail.com
@password1 = password12345
@email2 = p.swoyam.1@gmail.com
@password2 = password12345

@access_token1 = eyJhbGciOiJFUzI1NiIsImtpZCI6IjgyMWQ0ODE3LTNlNmUtNDFkMi04MmVmLTg4OGI4ZjE0ZGY0YSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2J4cXBvcXNhaXpuZndmbWVybnl2LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJjZjBkZTg2MC1kMTdmLTQ4NWItYjU4ZC0zNWI2ZDc3YmI2YjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc5OTcxODUyLCJpYXQiOjE3Nzk5NjgyNTIsImVtYWlsIjoid2l6YXJkbHkud2F5cy42OUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoid2l6YXJkbHkud2F5cy42OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IlRlc3QgVXNlciIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiY2YwZGU4NjAtZDE3Zi00ODViLWI1OGQtMzViNmQ3N2JiNmIyIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3Nzk5NjgyNTJ9XSwic2Vzc2lvbl9pZCI6ImJkNmY3OWU1LTIzNTQtNGI5Zi1hODFjLTBlMjI2ZGUzNWMzYSIsImlzX2Fub255bW91cyI6ZmFsc2V9.6CApT0Sg_iPOriDApkdVj4C4HOK0DYG4J-oJq2w0e55WWKy3Sq2r2uieMKAm5pCVNkiI0pEOhphWBqKP9nJcdQ
@access_token2 =eyJhbGciOiJFUzI1NiIsImtpZCI6IjgyMWQ0ODE3LTNlNmUtNDFkMi04MmVmLTg4OGI4ZjE0ZGY0YSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2J4cXBvcXNhaXpuZndmbWVybnl2LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIxOWNlY2VlYi1jZWRjLTRjODYtODU2OC1mOGQ0YmFjMjA4MjYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc5OTcxODg2LCJpYXQiOjE3Nzk5NjgyODYsImVtYWlsIjoicC5zd295YW0uMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoicC5zd295YW0uMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IlRlc3QgVXNlciIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiMTljZWNlZWItY2VkYy00Yzg2LTg1NjgtZjhkNGJhYzIwODI2In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3Nzk5NjgyODZ9XSwic2Vzc2lvbl9pZCI6ImM0NzllMGI5LTA0NzQtNDM2OS04YzMxLThmNjVjMTc1ZjZmNiIsImlzX2Fub255bW91cyI6ZmFsc2V9.Lz6ab4BYwv-kvMn__IEo9fglOOvtz1mlH4ncRLNSMdnQGuhhts6JcxU1GWmj1_QDxZzeAlnUagTFr0jKVVyftg 

### Signup user 1
POST {{supabase_url}}/auth/v1/signup
apikey: {{supabase_anon_key}}
Authorization: Bearer {{supabase_anon_key}}
Content-Type: application/json

{
  "email": "{{email1}}",
  "password": "{{password1}}",
  "data": {
    "name": "Test User 1"
  }
}

### Login user 1
POST {{supabase_url}}/auth/v1/token?grant_type=password
apikey: {{supabase_anon_key}}
Authorization: Bearer {{supabase_anon_key}}
Content-Type: application/json

{
  "email": "{{email1}}",
  "password": "{{password1}}"
}

### Signup user 2
POST {{supabase_url}}/auth/v1/signup
apikey: {{supabase_anon_key}}
Authorization: Bearer {{supabase_anon_key}}
Content-Type: application/json

{
  "email": "{{email2}}",
  "password": "{{password2}}",
  "data": {
    "name": "Test User 2"
  }
}

### Login user 2
POST {{supabase_url}}/auth/v1/token?grant_type=password
apikey: {{supabase_anon_key}}
Authorization: Bearer {{supabase_anon_key}}
Content-Type: application/json

{
  "email": "{{email2}}",
  "password": "{{password2}}"
}
