@api_url = http://localhost:8080

@access_token1 = eyJhbGciOiJFUzI1NiIsImtpZCI6IjgyMWQ0ODE3LTNlNmUtNDFkMi04MmVmLTg4OGI4ZjE0ZGY0YSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2J4cXBvcXNhaXpuZndmbWVybnl2LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJjZjBkZTg2MC1kMTdmLTQ4NWItYjU4ZC0zNWI2ZDc3YmI2YjIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc5OTcxODUyLCJpYXQiOjE3Nzk5NjgyNTIsImVtYWlsIjoid2l6YXJkbHkud2F5cy42OUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoid2l6YXJkbHkud2F5cy42OUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IlRlc3QgVXNlciIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiY2YwZGU4NjAtZDE3Zi00ODViLWI1OGQtMzViNmQ3N2JiNmIyIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3Nzk5NjgyNTJ9XSwic2Vzc2lvbl9pZCI6ImJkNmY3OWU1LTIzNTQtNGI5Zi1hODFjLTBlMjI2ZGUzNWMzYSIsImlzX2Fub255bW91cyI6ZmFsc2V9.6CApT0Sg_iPOriDApkdVj4C4HOK0DYG4J-oJq2w0e55WWKy3Sq2r2uieMKAm5pCVNkiI0pEOhphWBqKP9nJcdQ
@access_token2 =eyJhbGciOiJFUzI1NiIsImtpZCI6IjgyMWQ0ODE3LTNlNmUtNDFkMi04MmVmLTg4OGI4ZjE0ZGY0YSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2J4cXBvcXNhaXpuZndmbWVybnl2LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIxOWNlY2VlYi1jZWRjLTRjODYtODU2OC1mOGQ0YmFjMjA4MjYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzc5OTcxODg2LCJpYXQiOjE3Nzk5NjgyODYsImVtYWlsIjoicC5zd295YW0uMUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoicC5zd295YW0uMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IlRlc3QgVXNlciIsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiMTljZWNlZWItY2VkYy00Yzg2LTg1NjgtZjhkNGJhYzIwODI2In0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3Nzk5NjgyODZ9XSwic2Vzc2lvbl9pZCI6ImM0NzllMGI5LTA0NzQtNDM2OS04YzMxLThmNjVjMTc1ZjZmNiIsImlzX2Fub255bW91cyI6ZmFsc2V9.Lz6ab4BYwv-kvMn__IEo9fglOOvtz1mlH4ncRLNSMdnQGuhhts6JcxU1GWmj1_QDxZzeAlnUagTFr0jKVVyftg 

@project_id1 = f9910158-4aef-46bc-9c05-2cf1ac7a79bc 
@crawl_id1 = 474b57dc-1821-4afc-a47f-4f3123db7a5d 

### Create crawl for user 1 project
POST {{api_url}}/projects/{{project_id1}}/crawls
Authorization: Bearer {{access_token1}}
Content-Type: application/json

{
  "config_snapshot": {
    "max_depth": 3,
    "respect_robots_txt": true,
    "enable_javascript": false
  }
}

### List crawls for user 1 project
GET {{api_url}}/projects/{{project_id1}}/crawls
Authorization: Bearer {{access_token1}}

### Get one crawl as user 1
GET {{api_url}}/crawls/{{crawl_id1}}
Authorization: Bearer {{access_token1}}

### Forbidden create in user 1 project as user 2
POST {{api_url}}/projects/{{project_id1}}/crawls
Authorization: Bearer {{access_token2}}
Content-Type: application/json

{
  "config_snapshot": {
    "max_depth": 1
  }
}

### Forbidden list in user 1 project as user 2
GET {{api_url}}/projects/{{project_id1}}/crawls
Authorization: Bearer {{access_token2}}

### Hidden crawl as user 2
GET {{api_url}}/crawls/{{crawl_id1}}
Authorization: Bearer {{access_token2}}
